// P4-B2c-01 补丁器：权限与设置（非资金面）—— src/database.ts + src/index.ts
// 口径（沿用 B2a/B2b 先例）：逐条「起止标记」跨度替换，**标记不唯一/找不到即中止不写文件**；
//   落盘前备份改动前原文到 .p4-artifacts/<run>/orig/；落盘后断言「端点注册点 = 51」「src 内无 JWT 三段式」。
import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '..');
const RUN = process.env.P4_RUN || 'b2c-manual';
const ART = path.join(ROOT, '.p4-artifacts', RUN);
fs.mkdirSync(path.join(ART, 'orig'), { recursive: true });

type Span = { name: string; file: string; start: string; end: string; replace: string };

const L = (...lines: string[]) => lines.join('\n');

// ---------------------------------------------------------------------------------------------
// src/database.ts
// ---------------------------------------------------------------------------------------------
const DB_EDITS: Span[] = [
  {
    name: 'DB1 listPersistedPermissionGroups+getPermissionsForUser → admin_role*（+4 读辅助方法）',
    file: 'src/database.ts',
    start: L('  static async listPersistedPermissionGroups(): Promise<PermissionGroupRecord[]> {'),
    end: L('    return uniqueStrings(permissions);', '  }'),
    replace: L(
      '  // P4-B2c（§1 #35 / DL72 / 0017 §B）：数据源换接 `admin_role*` 三表（旧 `permission_group` 已废弃 ⇒ 零引用）。',
      '  // 三表当前 0 行 = **预期空态**（种子留批 6 走迁移；本片**禁插任何 admin 种子**）。',
      '  static async listPersistedPermissionGroups(): Promise<PermissionGroupRecord[]> {',
      '    const sql = getSql();',
      '    const rows = extractRows(await sql`',
      '      SELECT',
      '        r.role_key AS id,',
      "        COALESCE(r.name, '') AS name,",
      "        ''::text AS description,",
      '        COALESCE((',
      '          SELECT jsonb_agg(rp.permission_key ORDER BY rp.permission_key)',
      '          FROM public.admin_role_permission AS rp',
      '          WHERE rp.role_key = r.role_key',
      "        ), '[]'::jsonb) AS permissions,",
      '        COALESCE((',
      '          SELECT jsonb_agg(ur.uid ORDER BY ur.uid)',
      '          FROM public.admin_user_role AS ur',
      '          WHERE ur.role_key = r.role_key',
      "        ), '[]'::jsonb) AS user_ids,",
      '        false AS readonly,',
      '        r.time_created,',
      '        r.time_created AS time_updated',
      '      FROM public.admin_role AS r',
      '      ORDER BY r.role_key',
      '    `);',
      '    return rows.map(normalizePermissionGroup);',
      '  }',
      '',
      '  // P4-B2c（§6.1 / DL72）：can_access_admin 的「角色行」一支 ⇒ 权限位 = admin_user_role ⋈ admin_role_permission。',
      '  static async getPermissionsForUser(uID: number): Promise<string[]> {',
      '    const sql = getSql();',
      '    const rows = extractRows(await sql`',
      '      SELECT DISTINCT rp.permission_key',
      '      FROM public.admin_user_role AS ur',
      '      JOIN public.admin_role_permission AS rp ON rp.role_key = ur.role_key',
      '      WHERE ur.uid = ${uID}',
      '      ORDER BY rp.permission_key',
      '    `);',
      "    return uniqueStrings(rows.map((row) => toStringValue(getValue(row, 'permission_key'))));",
      '  }',
      '',
      '  // P4-B2c（§6.1 第二支）：EXISTS(admin_user_role.uid = :uid) —— 与「有无权限位」解耦',
      '  //（角色行存在但该角色 0 权限位时，can_access_admin 仍应为 true）。',
      '  static async hasAdminRoleRow(uID: number): Promise<boolean> {',
      '    const sql = getSql();',
      '    const row = firstRow(await sql`',
      '      SELECT 1 AS present',
      '      FROM public.admin_user_role AS ur',
      '      WHERE ur.uid = ${uID}',
      '      LIMIT 1',
      '    `);',
      '    return Boolean(row);',
      '  }',
      '',
      '  // P4-B2c（§6.3 / DL72）：角色是否存在（admin_role PK）。',
      '  static async roleExists(roleKey: string): Promise<boolean> {',
      '    const sql = getSql();',
      '    const row = firstRow(await sql`',
      '      SELECT 1 AS present',
      '      FROM public.admin_role AS r',
      '      WHERE r.role_key = ${roleKey}',
      '      LIMIT 1',
      '    `);',
      '    return Boolean(row);',
      '  }',
      '',
      '  // P4-B2c（§1.3-5 / DL72）：admin_role_permission.permission_key 有 FK ⇒ 落行前先判，',
      '  // 使 miss 走 404 LEDGER_REF_NOT_FOUND 而**不是**裸 23503（§3.3-4）。',
      '  static async findMissingPermissions(permissionKeys: string[]): Promise<string[]> {',
      '    if (permissionKeys.length === 0) {',
      '      return [];',
      '    }',
      '    const sql = getSql();',
      '    const rows = extractRows(await sql`',
      '      SELECT x AS permission_key',
      '      FROM unnest(${permissionKeys}::text[]) AS x',
      '      WHERE NOT EXISTS (',
      '        SELECT 1 FROM public.admin_permission AS p WHERE p.permission_key = x',
      '      )',
      '      ORDER BY x',
      '    `);',
      "    return rows.map((row) => toStringValue(getValue(row, 'permission_key')));",
      '  }',
      '',
      '  // P4-B2c（§1 #38 / DL72）：用户 → 角色的读侧（**不**经 mapper 出对外键，键集冻结）。',
      '  static async listUserRoles(uID: number): Promise<string[]> {',
      '    const sql = getSql();',
      '    const rows = extractRows(await sql`',
      '      SELECT ur.role_key',
      '      FROM public.admin_user_role AS ur',
      '      WHERE ur.uid = ${uID}',
      '      ORDER BY ur.role_key',
      '    `);',
      "    return uniqueStrings(rows.map((row) => toStringValue(getValue(row, 'role_key'))));",
      '  }',
      '',
      '  // P4-B2c（§1 #38）：整体替换该用户的角色分配（单事务；admin_user_role 的 PK 对 DELETE 允许，§6.3）。',
      '  static async replaceUserRoles(uID: number, roleKeys: string[]): Promise<string[]> {',
      '    const sql = getSql();',
      '    await sql.transaction([',
      '      sql`DELETE FROM public.admin_user_role WHERE uid = ${uID}`,',
      '      sql`',
      '        INSERT INTO public.admin_user_role (uid, role_key)',
      '        SELECT ${uID}, x FROM unnest(${roleKeys}::text[]) AS x',
      '      `,',
      '    ]);',
      '    return this.listUserRoles(uID);',
      '  }',
    ),
  },
  {
    name: 'DB2 resolveAdminAccess（单一真源）+ listPermissionGroups（换数据源、撤合成组）',
    file: 'src/database.ts',
    start: L('  static async resolveAdminAccess(user: UserRecord, isAdminAddress: boolean): Promise<AdminAccessRecord> {'),
    end: L(
      "      ...groups.filter((group) => !['admin_access', 'task_publishers', 'prize_publishers'].includes(group.id)),",
      '    ];',
      '  }',
    ),
    replace: L(
      '  static async resolveAdminAccess(user: UserRecord, isAdminAddress: boolean): Promise<AdminAccessRecord> {',
      '    // P4-B2c（§6.1 / DL72 单一真源）：can_access_admin = users.is_admin OR EXISTS(admin_user_role.uid = :uid)。',
      '    // 非 admin 时并行取「角色行存在」与「权限位集合」（后者不是前者的子集 ⇒ 两者都要）。',
      '    const bypass = user.is_admin || isAdminAddress;',
      '    const [hasRoleRow, extraPermissions] = bypass',
      '      ? [false, [] as string[]]',
      '      : await Promise.all([this.hasAdminRoleRow(user.uID), this.getPermissionsForUser(user.uID)]);',
      '',
      '    return this.buildAdminAccess(user, isAdminAddress, extraPermissions, hasRoleRow);',
      '  }',
      '',
      '  // P4-B2c（§1 #35 / §5.1「撤销 deprecated」）：唯一数据源 = **admin_role* 三表**（DL72）。',
      '  // 撤销 B1-c 的 3 个内置合成组（admin_access / task_publishers / prize_publishers）——',
      '  // 它们是旧 permission_group 语义的替身；新口径下「角色」的唯一定义在 admin_role。',
      '  static async listPermissionGroups(): Promise<PermissionGroupRecord[]> {',
      '    return this.listPersistedPermissionGroups();',
      '  }',
    ),
  },
  {
    name: 'DB3 savePermissionGroup → admin_role* 单事务',
    file: 'src/database.ts',
    start: L('  static async savePermissionGroup(input: {'),
    end: L('    return normalizePermissionGroup(row);', '  }'),
    replace: L(
      '  // P4-B2c（§1 #36 / §4.1 #39 / DL72）：换接 admin_role* 三表（单事务、原子重建）。',
      '  // 旧 permission_group 表已废弃（B7：已 DROP）⇒ 本函数零引用旧表。',
      '  static async savePermissionGroup(input: {',
      '    id?: string;',
      '    name?: string;',
      '    description?: string | null;',
      '    permissions?: string[];',
      '    user_ids?: number[];',
      '  }): Promise<PermissionGroupRecord> {',
      "    const id = String(input.id || '').trim() || slugify(input.name || '') || `group-${Date.now()}`;",
      '',
      "    const name = String(input.name || '').trim();",
      '    if (!name) {',
      "      throw new Error('Permission group name is required');",
      '    }',
      '',
      '    const permissions = uniqueStrings(',
      "      (input.permissions || []).map((value) => String(value ?? '').trim()).filter(Boolean),",
      '    );',
      '    if (permissions.length === 0) {',
      "      throw new Error('At least one valid permission is required');",
      '    }',
      '',
      '    const userIDs = uniqueNumbers(',
      '      (input.user_ids || [])',
      '        .map((value) => Number(value))',
      '        .filter((value) => Number.isFinite(value))',
      '        .map((value) => Math.trunc(value)),',
      '    );',
      '',
      '    const sql = getSql();',
      '    // 单事务（顺序执行，避免同语句 CTE 互不可见导致 FK/唯一键误判）：',
      '    // upsert 角色 → 清子行 → 重建「角色→权限」/「用户→角色」。',
      '    await sql.transaction([',
      '      sql`',
      '        INSERT INTO public.admin_role AS r (role_key, name, time_created)',
      '        VALUES (${id}, ${name}, NOW())',
      '        ON CONFLICT (role_key) DO UPDATE SET name = EXCLUDED.name',
      '      `,',
      '      sql`DELETE FROM public.admin_role_permission WHERE role_key = ${id}`,',
      '      sql`DELETE FROM public.admin_user_role WHERE role_key = ${id}`,',
      '      sql`',
      '        INSERT INTO public.admin_role_permission (role_key, permission_key)',
      '        SELECT ${id}, x FROM unnest(${permissions}::text[]) AS x',
      '      `,',
      '      sql`',
      '        INSERT INTO public.admin_user_role (uid, role_key)',
      '        SELECT x, ${id} FROM unnest(${userIDs}::bigint[]) AS x',
      '      `,',
      '    ]);',
      '',
      '    const row = firstRow(await sql`',
      '      SELECT',
      '        r.role_key AS id,',
      "        COALESCE(r.name, '') AS name,",
      "        ''::text AS description,",
      '        COALESCE((',
      '          SELECT jsonb_agg(rp.permission_key ORDER BY rp.permission_key)',
      '          FROM public.admin_role_permission AS rp',
      '          WHERE rp.role_key = r.role_key',
      "        ), '[]'::jsonb) AS permissions,",
      '        COALESCE((',
      '          SELECT jsonb_agg(ur.uid ORDER BY ur.uid)',
      '          FROM public.admin_user_role AS ur',
      '          WHERE ur.role_key = r.role_key',
      "        ), '[]'::jsonb) AS user_ids,",
      '        false AS readonly,',
      '        r.time_created,',
      '        r.time_created AS time_updated',
      '      FROM public.admin_role AS r',
      '      WHERE r.role_key = ${id}',
      '      LIMIT 1',
      '    `);',
      '',
      '    if (!row) {',
      "      throw new Error('Failed to save permission group');",
      '    }',
      '',
      '    return normalizePermissionGroup(row);',
      '  }',
    ),
  },
  {
    name: 'DB4 deletePermissionGroup → admin_role*（无在用用户才可删）',
    file: 'src/database.ts',
    start: L('  static async deletePermissionGroup(id: string): Promise<boolean> {'),
    end: L('    return true;', '  }'),
    replace: L(
      '  // P4-B2c（§1 #37 / §4.1 #40 / DL72）：删 admin_role（先清子行）；**该角色下无在用用户才可删**。',
      '  static async deletePermissionGroup(id: string): Promise<"deleted" | "in_use" | "not_found"> {',
      '    const sql = getSql();',
      '    const existing = firstRow(await sql`',
      '      SELECT r.role_key AS id FROM public.admin_role AS r WHERE r.role_key = ${id} LIMIT 1',
      '    `);',
      '    if (!existing) {',
      "      return 'not_found';",
      '    }',
      '    const inUse = firstRow(await sql`',
      '      SELECT ur.uid AS uid FROM public.admin_user_role AS ur WHERE ur.role_key = ${id} LIMIT 1',
      '    `);',
      '    if (inUse) {',
      "      return 'in_use';",
      '    }',
      '    await sql.transaction([',
      '      sql`DELETE FROM public.admin_role_permission WHERE role_key = ${id}`,',
      '      sql`DELETE FROM public.admin_user_role WHERE role_key = ${id}`,',
      '      sql`DELETE FROM public.admin_role WHERE role_key = ${id}`,',
      '    ]);',
      "    return 'deleted';",
      '  }',
    ),
  },
  {
    name: 'DB5 getSystemSettings/saveSystemSettings（public. + updated_by）/ reset 保留',
    file: 'src/database.ts',
    start: L('  static async getSystemSettings(): Promise<SystemSettingsRecord> {'),
    end: L(
      '  static async resetSystemSettings(): Promise<SystemSettingsRecord> {',
      '    return this.saveSystemSettings({ ...DEFAULT_SYSTEM_SETTINGS });',
      '  }',
    ),
    replace: L(
      '  // P4-B2c（§1 #32 / DL71 / DL151）：显式 public. 限定；`app_config` 是**单列 key/value**（**无 privacy 列**）。',
      '  static async getSystemSettings(): Promise<SystemSettingsRecord> {',
      '    const sql = getSql();',
      '    const rows = asItems<{ value: unknown }>(await sql`',
      '      SELECT value',
      '      FROM public.app_config',
      "      WHERE key = 'system_settings'",
      '      LIMIT 1',
      '    `);',
      '',
      '    return normalizeSystemSettings(rows[0]?.value || DEFAULT_SYSTEM_SETTINGS);',
      '  }',
      '',
      '  // P4-B2c（§1 #33 / DL36 / DL71）：补 `updated_by`（**NOT NULL 无默认** ⇒ 旧实现必违约）+ 显式 public.。',
      '  static async saveSystemSettings(input: Partial<SystemSettingsRecord>, updatedBy = 0): Promise<SystemSettingsRecord> {',
      '    const current = await this.getSystemSettings();',
      '    const next = normalizeSystemSettings({',
      '      ...current,',
      '      ...(input || {}),',
      '    });',
      '    const sql = getSql();',
      '',
      '    const rows = asItems<{ value: unknown }>(await sql`',
      '      INSERT INTO public.app_config (key, value, updated_by, time_updated)',
      "      VALUES ('system_settings', ${JSON.stringify(next)}::jsonb, ${Number(updatedBy) || 0}::bigint, NOW())",
      '      ON CONFLICT (key) DO UPDATE SET',
      '        value = EXCLUDED.value,',
      '        updated_by = EXCLUDED.updated_by,',
      '        time_updated = NOW()',
      '      RETURNING value',
      '    `);',
      '',
      '    return normalizeSystemSettings(rows[0]?.value || next);',
      '  }',
      '',
      '  // P4-B2c：**不再有路由**（§1 #34 ⇒ 410；C3 ② 删除）。保留方法体仅作回退点（DL42 可切换点）。',
      '  static async resetSystemSettings(): Promise<SystemSettingsRecord> {',
      '    return this.saveSystemSettings({ ...DEFAULT_SYSTEM_SETTINGS });',
      '  }',
    ),
  },
  {
    name: 'DB6 buildAdminAccess 增 hasRoleRow（§6.1 第二支；返回键集不变）',
    file: 'src/database.ts',
    start: L('  static buildAdminAccess('),
    end: L('    const canAccessAdmin = isAdmin || permissions.length > 0;'),
    replace: L(
      '  static buildAdminAccess(',
      '    user: UserRecord,',
      '    isAdminAddress: boolean,',
      '    extraPermissions: string[] = [],',
      '    hasRoleRow = false,',
      '  ): AdminAccessRecord {',
      '    const isAdmin = user.is_admin || isAdminAddress;',
      '    const permissions = isAdmin',
      '      ? [...ALL_ADMIN_PERMISSIONS]',
      '      : uniqueStrings(extraPermissions);',
      '    // P4-B2c（§6.1）：can_access_admin = is_admin OR EXISTS(admin_user_role.uid) OR 有权限位。',
      '    const canAccessAdmin = isAdmin || hasRoleRow || permissions.length > 0;',
    ),
  },
];

// ---------------------------------------------------------------------------------------------
// src/index.ts
// ---------------------------------------------------------------------------------------------
const IDX_EDITS: Span[] = [
  {
    name: 'IX1 import：ledgerErrorBody + admin-service',
    file: 'src/index.ts',
    start: L("import { healthCheck } from './db';"),
    end: L("import { sendGone, sendVerbError, submitWork } from './job-service';"),
    replace: L(
      "import { healthCheck } from './db';",
      "import { ledgerErrorBody, sendGone, sendVerbError, submitWork } from './job-service';",
      '// P4-B2c：权限与设置（非资金面）service（§1 #36/#37/#38 的 verb + DL36 的 ops: 幂等键）',
      'import {',
      '  adminPermissionDeleteVerb,',
      '  adminPermissionSaveVerb,',
      '  adminUserUpdateVerb,',
      '  adminVerbError,',
      '  findFeeRateKey,',
      '  resolveAdminOpsKey,',
      "} from './admin-service';",
    ),
  },
  {
    name: 'IX2 requireActor 401 → AUTH_UNAUTHORIZED（R107 形状）',
    file: 'src/index.ts',
    start: L('const requireActor = async (req: Request, res: Response) => {'),
    end: L('  return actor;', '};'),
    replace: L(
      '// P4-B2c（§3.3-1 / §3.3-6 / §6.2 / DL105 v0.2 / DL122 / DL147）：401/403 一律 R107 形状，',
      '// 码域 = AUTH_*（**不**进 LEDGER_* 33 码关闭集；i18n_key 域 = auth.err.*）。',
      '// DL147③：reason 只准取 §11.3.2 登记值（ACTOR_NOT_ALLOWED / NOT_ADMIN / PERMISSION_NOT_GRANTED）。',
      "const AUTH_REASONS = ['ACTOR_NOT_ALLOWED', 'NOT_ADMIN', 'PERMISSION_NOT_GRANTED'] as const;",
      '',
      'const sendAuthError = (res: Response, statusCode: 401 | 403, reason?: string) => {',
      "  const code = statusCode === 401 ? 'AUTH_UNAUTHORIZED' : 'AUTH_FORBIDDEN';",
      '  const details: Record<string, unknown> = {};',
      '  if (reason && (AUTH_REASONS as readonly string[]).includes(reason)) {',
      '    details.reason = reason;',
      '  }',
      '  return res.status(statusCode).json(ledgerErrorBody(code, code, details, \'auth\'));',
      '};',
      '',
      'const requireActor = async (req: Request, res: Response) => {',
      '  const actor = await resolveActor(req);',
      '  if (!actor) {',
      '    sendAuthError(res, 401);',
      '    return null;',
      '  }',
      '',
      '  return actor;',
      '};',
    ),
  },
  {
    name: 'IX3 requireAdmin 403 → AUTH_FORBIDDEN + reason（NOT_ADMIN / PERMISSION_NOT_GRANTED）',
    file: 'src/index.ts',
    start: L('const requireAdmin = async (req: Request, res: Response, requiredPermission?: string | string[]) => {'),
    end: L('  return actor;', '};'),
    replace: L(
      'const requireAdmin = async (req: Request, res: Response, requiredPermission?: string | string[]) => {',
      '  const actor = await requireActor(req, res);',
      '  if (!actor) {',
      '    return null;',
      '  }',
      '',
      '  if (!actor.adminAccess.can_access_admin) {',
      '    // §6.2 步 2 / DL105② / DL147③：reason=NOT_ADMIN',
      "    sendAuthError(res, 403, 'NOT_ADMIN');",
      '    return null;',
      '  }',
      '',
      '  if (!actor.adminAccess.is_admin && !hasRequiredPermission(actor, requiredPermission)) {',
      '    // §6.2 步 4 / DL105④ / DL147③：reason=PERMISSION_NOT_GRANTED',
      "    sendAuthError(res, 403, 'PERMISSION_NOT_GRANTED');",
      '    return null;',
      '  }',
      '',
      '  return actor;',
      '};',
    ),
  },
  {
    name: 'IX4 GET /api/admin/settings：message 标注「费率不在本表」',
    file: 'src/index.ts',
    start: L('    const settings = await DatabaseService.getSystemSettings();'),
    end: L('    sendSuccess(res, settings);'),
    replace: L(
      '    const settings = await DatabaseService.getSystemSettings();',
      '    // §1 #32 / §4.1 #35：响应必须标注「费率不在本表」（真源 = commission_policy.fee_rate_bp）。',
      '    // 用 message 承载（**不改 data 键集** —— §2 母约束 F1 优先）。',
      "    sendSuccess(res, settings, 'OK（费率不在 app_config；真源 = commission_policy.fee_rate_bp）');",
    ),
  },
  {
    name: 'IX5 POST /api/admin/settings：ops: 键 + 禁费率键 + updated_by',
    file: 'src/index.ts',
    start: L("app.post('/api/admin/settings', async (req, res) => {"),
    end: L(
      "    sendError(res, 400, error instanceof Error ? error.message : 'Failed to save system settings');",
      '  }',
      '});',
    ),
    replace: L(
      "app.post('/api/admin/settings', async (req, res) => {",
      "  const actor = await requireAdmin(req, res, 'manage_settings');",
      '  if (!actor) return;',
      '',
      '  // DL36 / §11.2:581：`ops:<admin_uid>:setting:<key>`；无键 ⇒ 400 LEDGER_IDEMPOTENCY_KEY_REQUIRED',
      "  const opsKey = resolveAdminOpsKey(req, actor.session.uID, 'setting', 'system_settings');",
      '  if (!opsKey.ok) {',
      '    return sendVerbError(res, opsKey.error);',
      '  }',
      '',
      '  try {',
      '    const body = (req.body || {}) as Record<string, unknown>;',
      '    // §1 #33 / §4.1 #36：**禁写费率键**（费率真源 = commission_policy.fee_rate_bp，CR23/CR25）',
      '    const feeKey = findFeeRateKey(body);',
      '    if (feeKey) {',
      "      return sendVerbError(res, adminVerbError(400, 'LEDGER_AMOUNT_INVALID', {",
      '        field: feeKey,',
      "        reason: 'FEE_RATE_KEY_NOT_IN_APP_CONFIG',",
      "        authoritative_table: 'commission_policy',",
      "        authoritative_column: 'fee_rate_bp',",
      "      }, 'Fee-rate keys are not writable via /api/admin/settings'));",
      '    }',
      '    const settings = await DatabaseService.saveSystemSettings(body, actor.session.uID);',
      "    sendSuccess(res, settings, 'System settings saved');",
      '  } catch (error) {',
      "    console.error('Error saving system settings:', error);",
      "    sendError(res, 400, error instanceof Error ? error.message : 'Failed to save system settings');",
      '  }',
      '});',
    ),
  },
  {
    name: 'IX6 POST /api/admin/settings/reset → 410（C3 ②）',
    file: 'src/index.ts',
    start: L("app.post('/api/admin/settings/reset', async (req, res) => {"),
    end: L("    sendError(res, 500, 'Failed to reset system settings');", '  }', '});'),
    replace: L(
      '// P4-B2c（§1 #34 + §5.1「一键重置设置」+ C3 ②「确认删除」）：无审计的批量破坏写 ⇒ 一律 410 + R107 形状。',
      '// 撤 requireAdmin 前置（同 B2a/B2b 先例：弃用面不得把「已下线」伪装成「未授权」）。',
      "const ADMIN_SETTINGS_RESET_SUNSET = '批 4 删路径（未决 §7-1：过期日待 Kevin 定）';",
      '',
      "app.post('/api/admin/settings/reset', async (_req, res) => {",
      "  return sendGone(res, '/api/admin/settings/reset', ADMIN_SETTINGS_RESET_SUNSET);",
      '});',
    ),
  },
  {
    name: 'IX7 GET /api/admin/permissions：撤销 deprecated（§5.1/§5.3）',
    file: 'src/index.ts',
    start: L("    sendSuccess(res, { groups, users }, 'OK', 200, { deprecated: true });"),
    end: L("    sendSuccess(res, { groups, users }, 'OK', 200, { deprecated: true });"),
    replace: L(
      '    // P4-B2c（§5.1「权限面板弃用标」/§5.3）：批 2 换数据源到 admin_role* 后即正式口 ⇒ **撤销 deprecated**。',
      "    sendSuccess(res, { groups, users });",
    ),
  },
  {
    name: 'IX8 POST /api/admin/permissions/save → verb（ops: 键 + 自锁守卫）',
    file: 'src/index.ts',
    start: L("app.post('/api/admin/permissions/save', async (req, res) => {"),
    end: L(
      "    sendError(res, 400, error instanceof Error ? error.message : 'Failed to save permission group');",
      '  }',
      '});',
    ),
    replace: L(
      "app.post('/api/admin/permissions/save', async (req, res) => {",
      "  const actor = await requireAdmin(req, res, 'manage_permissions');",
      '  if (!actor) return;',
      '',
      '  // DL36 / §11.2:582：`ops:<admin_uid>:permission_save:<role_key>`',
      "  const opsKey = resolveAdminOpsKey(req, actor.session.uID, 'permission_save', String(req.body?.id ?? 'new'));",
      '  if (!opsKey.ok) {',
      '    return sendVerbError(res, opsKey.error);',
      '  }',
      '',
      '  try {',
      '    const result = await adminPermissionSaveVerb({',
      '      actorUid: actor.session.uID,',
      '      actorIsAdmin: actor.adminAccess.is_admin,',
      '      id: req.body?.id,',
      '      name: req.body?.name,',
      '      description: req.body?.description,',
      '      permissions: req.body?.permissions,',
      '      user_ids: req.body?.user_ids,',
      '    });',
      '    if (!result.ok) {',
      '      return sendVerbError(res, result);',
      '    }',
      "    sendSuccess(res, result.view, 'Permission group saved');",
      '  } catch (error) {',
      "    console.error('Error saving permission group:', error);",
      "    sendError(res, 400, error instanceof Error ? error.message : 'Failed to save permission group');",
      '  }',
      '});',
    ),
  },
  {
    name: 'IX9 POST /api/admin/permissions/delete → verb（ops: 键 + 无在用用户才可删）',
    file: 'src/index.ts',
    start: L("app.post('/api/admin/permissions/delete', async (req, res) => {"),
    end: L(
      "    sendError(res, 400, error instanceof Error ? error.message : 'Failed to delete permission group');",
      '  }',
      '});',
    ),
    replace: L(
      "app.post('/api/admin/permissions/delete', async (req, res) => {",
      "  const actor = await requireAdmin(req, res, 'manage_permissions');",
      '  if (!actor) return;',
      '',
      '  // DL36 / §11.2:583：`ops:<admin_uid>:permission_delete:<role_key>`',
      "  const opsKey = resolveAdminOpsKey(req, actor.session.uID, 'permission_delete', String(req.body?.id ?? ''));",
      '  if (!opsKey.ok) {',
      '    return sendVerbError(res, opsKey.error);',
      '  }',
      '',
      '  try {',
      '    const result = await adminPermissionDeleteVerb({ id: req.body?.id });',
      '    if (!result.ok) {',
      '      return sendVerbError(res, result);',
      '    }',
      '    sendSuccess(res, result.view, \'Permission group deleted\');',
      '  } catch (error) {',
      "    console.error('Error deleting permission group:', error);",
      "    sendError(res, 400, error instanceof Error ? error.message : 'Failed to delete permission group');",
      '  }',
      '});',
    ),
  },
  {
    name: 'IX10 POST /api/admin/user/update → verb（DL104 白名单 + ops: 键）',
    file: 'src/index.ts',
    start: L("app.post('/api/admin/user/update', async (req, res) => {"),
    end: L(
      "    sendError(res, 400, error instanceof Error ? error.message : 'Failed to update user');",
      '  }',
      '});',
    ),
    replace: L(
      "app.post('/api/admin/user/update', async (req, res) => {",
      "  const actor = await requireAdmin(req, res, 'manage_users');",
      '  if (!actor) return;',
      '',
      '  // DL36 / §11.2:584：`ops:<admin_uid>:user_update:<target_uid>`',
      "  const opsKey = resolveAdminOpsKey(req, actor.session.uID, 'user_update', String(req.body?.target_uid ?? req.body?.uID ?? ''));",
      '  if (!opsKey.ok) {',
      '    return sendVerbError(res, opsKey.error);',
      '  }',
      '',
      '  try {',
      '    const result = await adminUserUpdateVerb({ body: req.body });',
      '    if (!result.ok) {',
      '      return sendVerbError(res, result);',
      '    }',
      "    sendSuccess(res, result.view, 'User updated');",
      '  } catch (error) {',
      "    console.error('Error updating user:', error);",
      "    sendError(res, 400, error instanceof Error ? error.message : 'Failed to update user');",
      '  }',
      '});',
    ),
  },
  {
    name: 'IX11 GET /api/user/stats：message 标注「账本派生」',
    file: 'src/index.ts',
    start: L('    const stats = await DatabaseService.getUserStats();'),
    end: L('    sendSuccess(res, stats);'),
    replace: L(
      '    const stats = await DatabaseService.getUserStats();',
      '    // §1 #46 / §4.1 #49 / DL1 / DL24：统计口径必须标注「账本派生」（余额真源 = account）。',
      "    sendSuccess(res, stats, 'OK（统计口径 = 账本派生：余额取自 account，DL1/DL24）');",
    ),
  },
  {
    name: 'IX12 GET /api/user/all：只读运维视图注记（分页 + 非敏感列 + 禁 token）',
    file: 'src/index.ts',
    start: L("app.get('/api/user/all', async (req, res) => {"),
    end: L('  const actor = await requireAdmin(req, res);', '  if (!actor) return;'),
    replace: L(
      "app.get('/api/user/all', async (req, res) => {",
      '  // P4-B2c（§1 #45 / §4.1 #48）：只读运维视图 —— 分页（getPagination）+ **只出非敏感列**',
      '  //（UserRecord 6 键：uID/EVM/bio/is_admin/time_reg/time_login_last）+ **禁 token**（mapper 无任何 token 列）。',
      '  const actor = await requireAdmin(req, res);',
      '  if (!actor) return;',
    ),
  },
];

// ---------------------------------------------------------------------------------------------
function loadOriginal(file: string): string {
  return fs.readFileSync(path.join(ROOT, file), 'utf8');
}

function applySpans(file: string, edits: Span[]): { before: string; after: string; hits: unknown[] } {
  let text = loadOriginal(file);
  const hits: unknown[] = [];
  for (const edit of edits) {
    const startIdx = text.indexOf(edit.start);
    if (startIdx < 0) {
      throw new Error(`[${edit.name}] start marker NOT FOUND in ${file}`);
    }
    if (text.indexOf(edit.start, startIdx + 1) >= 0) {
      throw new Error(`[${edit.name}] start marker NOT UNIQUE in ${file}`);
    }
    const endIdx = text.indexOf(edit.end, startIdx);
    if (endIdx < 0) {
      throw new Error(`[${edit.name}] end marker NOT FOUND after start in ${file}`);
    }
    const span = text.slice(startIdx, endIdx + edit.end.length);
    text = text.slice(0, startIdx) + edit.replace + text.slice(endIdx + edit.end.length);
    hits.push({ name: edit.name, removed_chars: span.length, added_chars: edit.replace.length });
  }
  return { before: loadOriginal(file), after: text, hits };
}

const report: Record<string, unknown> = { run: RUN, at: new Date().toISOString(), files: {} };
const files = ['src/database.ts', 'src/index.ts'];

for (const file of files) {
  const edits = file === 'src/database.ts' ? DB_EDITS : IDX_EDITS;
  const { before, after, hits } = applySpans(file, edits);

  // 备份改动前原文（不覆盖既有备份）
  const backup = path.join(ART, 'orig', `${file.replace(/\//g, '_')}.orig`);
  if (!fs.existsSync(backup)) {
    fs.writeFileSync(backup, before);
  }

  fs.writeFileSync(path.join(ROOT, file), after);

  const routes = (after.match(/^app\.(get|post|put|delete|patch)\(/gm) || []).length;
  const jwtLike = (after.match(/eyJ/g) || []).length;
  report.files = {
    ...(report.files as Record<string, unknown>),
    [file]: { edits: hits.length, hits, bytes_before: before.length, bytes_after: after.length, routes, jwt_like_tokens: jwtLike },
  };

  if (file === 'src/index.ts' && routes !== 51) {
    throw new Error(`route count changed: expected 51, got ${routes}`);
  }
}

// 独立复核：注册点 51 + 旧表 permission_group 的**代码面零引用**（DL38）
const idxText = fs.readFileSync(path.join(ROOT, 'src/index.ts'), 'utf8');
const dbText = fs.readFileSync(path.join(ROOT, 'src/database.ts'), 'utf8');
(report as Record<string, unknown>).assertions = {
  route_count_index: (idxText.match(/^app\.(get|post|put|delete|patch)\(/gm) || []).length,
  permission_group_refs_in_src: ((idxText + dbText).match(/permission_group/g) || []).length,
  jwt_like_tokens_in_src: ((idxText + dbText).match(/eyJ/g) || []).length,
  deprecated_true_calls: (idxText.match(/deprecated: true/g) || []).length,
  app_config_public: (dbText.match(/public\.app_config/g) || []).length,
  admin_role_public_refs: (dbText.match(/public\.admin_role/g) || []).length,
};

fs.writeFileSync(path.join(ART, 'patch-log.json'), JSON.stringify(report, null, 2));
console.log(JSON.stringify(report, null, 2));
