/**
 * p7b-06 · AC-11 / HTTP E2E 夹具建立（R-C：自建夹具 uid ≥ 900000）
 * ---------------------------------------------------------------------------
 * 用法：cd backend-ts && P7B_RUN=<run> npx ts-node --transpile-only scripts/p7b-06-fixture-setup.ts
 * 读数：.p7b-artifacts/p7b-06-fixture-setup-<RUN>.json（含 fixture id 与**残留清单**）
 *
 * 纪律：
 *   · 夹具 uid 全部 ≥ 900000（显式 INSERT；users.uid 为 GENERATED BY DEFAULT ⇒ 允许显式）。
 *   · 供资**走账本 transfer**（净额守恒、不 mint、Σ(cid=1) 零位移）。
 *   · 建立后**提交**（并发用例需跨会话可见）⇒ 残留逐项登记（见输出 residue_manifest）。
 */
import * as fs from 'fs';
import * as path from 'path';
import { mkPool, raw, raw1, save, pgErr, RUN, OUT_DIR, sha256 } from './p7b-lib';

const U = {
  S1: 900001, // 卖方（F1）
  B1: 900002, // 买方（F1/F2/F4）
  S2: 900003, // 卖方（F2）
  A_BUYER: 900004, // 管理员兼买方（F3 的买方）
  A_ADMIN: 900005, // 管理员（非当事人；E2E ④）
  A_NOPTS: 900006, // admin 面但**缺 manage_points**（E2E ⑥）
  P: 900007, // 普通第三方（E2E ②）
  S3: 900008, // 卖方（F4 · AC-11 并发）
};

const ROLE_ADMIN = 'p7b_fixture_admin';
const ROLE_NOPTS = 'p7b_fixture_nopts';

const evmOf = (uid: number) => `0x${sha256(`p7b:fixture:uid:${uid}`).slice(0, 40)}`;

(async () => {
  const p = mkPool(3);
  const out: Record<string, unknown> = { script: 'scripts/p7b-06-fixture-setup.ts', run: RUN };
  const q = async (sql: string, params: unknown[] = []) => raw(p, sql, params);
  try {
    // ---------------------------------------------------------------- 1 用户
    for (const uid of Object.values(U)) {
      await q(`INSERT INTO public."users" (uid, evm, bio) VALUES ($1, $2, $3) ON CONFLICT (uid) DO NOTHING`,
        [uid, evmOf(uid), `p7b fixture uid=${uid}`]);
    }
    out.users = await q(`SELECT uid::text AS uid, evm, is_admin FROM public."users" WHERE uid >= 900000 ORDER BY uid`);
    out.users_created = (out.users as unknown[]).length;

    // ---------------------------------------------------------------- 2 角色 / 权限
    await q(`INSERT INTO public.admin_role (role_key, name) VALUES ($1, $2) ON CONFLICT (role_key) DO NOTHING`,
      [ROLE_ADMIN, 'P7B fixture admin (manage_points)']);
    await q(`INSERT INTO public.admin_role (role_key, name) VALUES ($1, $2) ON CONFLICT (role_key) DO NOTHING`,
      [ROLE_NOPTS, 'P7B fixture admin without manage_points']);
    await q(`INSERT INTO public.admin_role_permission (role_key, permission_key) VALUES ($1,'manage_points') ON CONFLICT DO NOTHING`, [ROLE_ADMIN]);
    await q(`INSERT INTO public.admin_role_permission (role_key, permission_key) VALUES ($1,'read_users') ON CONFLICT DO NOTHING`, [ROLE_NOPTS]);
    for (const [uid, rk] of [[U.A_ADMIN, ROLE_ADMIN], [U.A_BUYER, ROLE_ADMIN], [U.A_NOPTS, ROLE_NOPTS]] as const) {
      await q(`INSERT INTO public.admin_user_role (uid, role_key) VALUES ($1,$2) ON CONFLICT DO NOTHING`, [uid, rk]);
    }
    out.role_assignments = await q(`SELECT uid::text AS uid, role_key FROM public.admin_user_role WHERE uid >= 900000 ORDER BY uid`);

    // ---------------------------------------------------------------- 3 listing（自建）
    const existingListing = await raw1<{ listing_id: string }>(p,
      `SELECT listing_id::text AS listing_id FROM public.listing WHERE create_key = 'cli:p7b-fixture-listing-01'`);
    let listingId: string;
    if (existingListing) {
      listingId = existingListing.listing_id;
    } else {
      const r = await raw1<{ listing_id: string }>(p,
        `INSERT INTO public.listing (seller_uid, cid, price, stock, title, create_key, status)
         VALUES ($1, 1, 1, 100, 'p7b fixture listing', 'cli:p7b-fixture-listing-01', 'listed')
         RETURNING listing_id::text AS listing_id`, [U.S1]);
      listingId = r!.listing_id;
    }
    out.listing_id = listingId;

    // ---------------------------------------------------------------- 4 供资（账本 transfer；净额守恒）
    const donor = await raw1<{ uid: string; balance: string }>(p,
      `SELECT uid::text AS uid, balance::text AS balance FROM public.account
        WHERE cid=1 AND balance > 100 AND uid > 0 AND uid NOT IN (900001,900002,900003,900004,900005,900006,900007,900008)
        ORDER BY balance DESC LIMIT 1`);
    const funding: unknown[] = [];
    for (const uid of [U.S1, U.S2, U.S3]) {
      const got = await raw1<{ balance: string }>(p,
        `SELECT COALESCE(balance,0)::text AS balance FROM public.account WHERE uid=$1 AND cid=1`, [uid]);
      if (Number(got?.balance ?? '0') >= 5) { funding.push({ uid, skipped: true, balance: got?.balance }); continue; }
      const r = await raw1<{ r: Record<string, unknown> }>(p,
        `SELECT public.ledger_post_event($1::jsonb) AS r`, [JSON.stringify({
          op: 'transfer', idempotency_key: `ops:p7b:fund:${RUN}:${uid}`,
          from_uid: donor!.uid, to_uid: String(uid), cid: '1', amount: '10',
        })]);
      funding.push({ uid, from: donor!.uid, amount: '10', txid: r?.r?.txid, replay: r?.r?.idempotent_replay });
    }
    out.funding = funding;

    // ---------------------------------------------------------------- 5 订单（paid）
    const payTxid = (await raw1<{ txid: string }>(p, `SELECT max(txid)::text AS txid FROM public.ledger_entry`))!.txid;
    const mkOrder = async (key: string, seller: number, buyer: number, price = 1, qty = 1) => {
      const ex = await raw1<{ order_id: string }>(p, `SELECT order_id::text AS order_id FROM public.listing_order WHERE create_key=$1`, [key]);
      if (ex) return ex.order_id;
      const r = await raw1<{ order_id: string }>(p,
        `INSERT INTO public.listing_order (listing_id, buyer_uid, seller_uid, cid, price, quantity, status, create_key, pay_txid)
         VALUES ($1,$2,$3,1,$4,$5,'paid',$6,$7) RETURNING order_id::text AS order_id`,
        [listingId, buyer, seller, price, qty, key, payTxid]);
      return r!.order_id;
    };
    const orders = {
      f1: await mkOrder('cli:p7b-fixture-order-f1', U.S1, U.B1),
      f2: await mkOrder('cli:p7b-fixture-order-f2', U.S2, U.B1),
      f3: await mkOrder('cli:p7b-fixture-order-f3', U.S1, U.A_BUYER),
      f4: await mkOrder('cli:p7b-fixture-order-f4', U.S3, U.B1),
      // 收口轮追加：R-A 删除不可达分支后**在新代码上**重跑 HTTP E2E 用的两笔（③④⑦ 用）
      f5: await mkOrder('cli:p7b-fixture-order-f5', U.S1, U.B1),
      f6: await mkOrder('cli:p7b-fixture-order-f6', U.S2, U.B1),
    };
    out.orders = orders;
    out.order_rows = await q(`SELECT order_id::text AS order_id, seller_uid::text, buyer_uid::text, price::text, quantity, status
      FROM public.listing_order WHERE create_key LIKE 'cli:p7b-fixture-order-%' ORDER BY order_id`);

    // ---------------------------------------------------------------- 6 残留清单
    out.residue_manifest = {
      users: Object.values(U),
      roles: [ROLE_ADMIN, ROLE_NOPTS],
      role_assignments: [[U.A_ADMIN, ROLE_ADMIN], [U.A_BUYER, ROLE_ADMIN], [U.A_NOPTS, ROLE_NOPTS]],
      listing_id: listingId,
      orders,
      funding_transfers: funding,
    };
  } finally {
    await p.end().catch(() => undefined);
  }
  const f = save('p7b-06-fixture-setup', out);
  console.log(JSON.stringify({ saved: f, ok: true, orders: out.orders, users_created: out.users_created, listing_id: out.listing_id }, null, 1));
})().catch((e) => {
  console.error('FATAL', pgErr(e));
  process.exit(2);
});
