-- ============================================================================
-- 0001_ledger_core.sql · 海鲜市场 P0 账本内核
-- 权威口径：docs/ledger.spec.md
--   §2.1  三张核心表 DDL（逐字落地，不增删字段）
--   §9.2  append-only 与 account 守卫触发器
--   §12.1 11 个必建索引
--   §13.2 保留 uid 区间（0 / -1 / -2 / -3）与平台账户种子（R99）
--   §2    R21：新增 ledger_owner 辅助表（Zang 裁定「采纳」）
-- 只创建新对象，不改动任何既有对象；破坏性 DDL 一律禁止（R77）
-- ============================================================================

-- ---------------------------------------------------------------- §2.1 currency
CREATE TABLE currency (
  cid            bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol         text        NOT NULL,
  name           text        NOT NULL,
  icon_url       text        NOT NULL DEFAULT '',
  owner_uid      bigint      NOT NULL DEFAULT 0,
  decimals       smallint    NOT NULL DEFAULT 0,
  total_supply   bigint      NOT NULL DEFAULT 0,
  supply_cap     bigint,
  status         text        NOT NULL DEFAULT 'draft',
  deposit_amount bigint      NOT NULL DEFAULT 0,
  deposit_cid    bigint      NOT NULL DEFAULT 1,
  listed_at      timestamptz,
  time_created   timestamptz NOT NULL DEFAULT now(),
  time_updated   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT currency_symbol_uniq   UNIQUE (symbol),
  CONSTRAINT currency_symbol_fmt    CHECK (symbol ~ '^[^[:space:]]{1,16}$'),
  CONSTRAINT currency_decimals_rng  CHECK (decimals BETWEEN 0 AND 18),
  CONSTRAINT currency_supply_guard  CHECK (
      total_supply >= 0
      AND (supply_cap IS NULL OR (supply_cap >= 0 AND total_supply <= supply_cap))
  ),
  CONSTRAINT currency_status_enum   CHECK (status IN ('draft','listed','frozen','delisted')),
  CONSTRAINT currency_deposit_guard CHECK (deposit_amount >= 0),
  CONSTRAINT currency_listed_at     CHECK (status = 'draft' OR listed_at IS NOT NULL)
);

-- ---------------------------------------------------------------- §2.1 account
CREATE TABLE account (
  uid          bigint      NOT NULL,
  cid          bigint      NOT NULL REFERENCES currency(cid),
  balance      bigint      NOT NULL DEFAULT 0,
  frozen       bigint      NOT NULL DEFAULT 0,
  version      bigint      NOT NULL DEFAULT 0,
  time_created timestamptz NOT NULL DEFAULT now(),
  time_updated timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT account_pk        PRIMARY KEY (uid, cid),
  CONSTRAINT account_bal_guard CHECK (balance >= 0),
  CONSTRAINT account_frz_guard CHECK (frozen  >= 0)
);

-- ------------------------------------------------------------ §2.1 ledger_entry
CREATE TABLE ledger_entry (
  txid                bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  uid                 bigint      NOT NULL,
  cid                 bigint      NOT NULL REFERENCES currency(cid),
  delta               bigint      NOT NULL DEFAULT 0,
  frozen_delta        bigint      NOT NULL DEFAULT 0,
  balance_after       bigint      NOT NULL,
  frozen_after        bigint      NOT NULL,
  kind                text        NOT NULL,
  ref_type            text,
  ref_id              bigint,
  idempotency_key     text        NOT NULL,
  request_fingerprint text,
  reversal_of_txid    bigint      REFERENCES ledger_entry(txid),
  memo                text        NOT NULL DEFAULT '',
  time_created        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ledger_move_guard    CHECK (delta <> 0 OR frozen_delta <> 0),
  CONSTRAINT ledger_after_guard   CHECK (balance_after >= 0 AND frozen_after >= 0),
  CONSTRAINT ledger_ref_pair      CHECK ((ref_type IS NULL) = (ref_id IS NULL)),
  CONSTRAINT ledger_idem_uniq     UNIQUE (idempotency_key),
  CONSTRAINT ledger_reversal_guard CHECK ((kind = 'reversal') = (reversal_of_txid IS NOT NULL)),
  CONSTRAINT ledger_kind_enum     CHECK (kind IN (
      'mint','burn','transfer','hold','hold_release','hold_forfeit',
      'job_escrow','job_escrow_refund','job_payout','job_fee','commission',
      'purchase','sale','purchase_refund',
      'trade','trade_fee',
      'listing_fee','listing_deposit','listing_deposit_refund','listing_deposit_forfeit',
      'currency_create_fee','reversal'
  )),
  CONSTRAINT ledger_ref_type_enum CHECK (ref_type IS NULL OR ref_type IN (
      'job','listing','listing_order','market_order','market_trade','currency','commission_payout','system'
  ))
);

CREATE UNIQUE INDEX ledger_reversal_of_uniq
  ON ledger_entry (reversal_of_txid) WHERE reversal_of_txid IS NOT NULL;

-- ------------------------------------------- §2.2 R21 采纳：ledger_owner 辅助表
-- 用途：承载 uid → 主体类型（真实用户 / 平台）的登记，是平台保留 uid 的 FK 目标。
-- 注：本版**未**对 account.uid / ledger_entry.uid 施加 FK（保持 §2.1 的 DDL 原样），
--     是否加 FK 属 P1/P2 身份 spec 的裁定项，已登记进交付报告的「已知未处理项」。
CREATE TABLE ledger_owner (
  uid          bigint      PRIMARY KEY,
  owner_type   text        NOT NULL,
  name         text        NOT NULL DEFAULT '',
  time_created timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ledger_owner_type_enum CHECK (owner_type IN ('user','platform')),
  CONSTRAINT ledger_owner_uid_rule  CHECK (
      (owner_type = 'user'     AND uid > 0)
   OR (owner_type = 'platform' AND uid = 0)
   OR (owner_type = 'platform' AND uid BETWEEN -99 AND -1)
  )
);

-- ------------------------------------------------------------- §12.1 索引清单
CREATE INDEX idx_account_cid_balance ON account (cid, balance DESC);
CREATE INDEX idx_account_frozen      ON account (cid, uid) WHERE frozen > 0;
CREATE INDEX idx_currency_owner      ON currency (owner_uid);
CREATE INDEX idx_currency_status     ON currency (status) WHERE status <> 'delisted';
CREATE INDEX idx_ledger_uid_cid_txid ON ledger_entry (uid, cid, txid DESC);
CREATE INDEX idx_ledger_ref          ON ledger_entry (ref_type, ref_id);
CREATE INDEX idx_ledger_kind_time    ON ledger_entry (kind, time_created DESC);

-- --------------------------------------------------------------- §9.2 触发器
CREATE OR REPLACE FUNCTION ledger_entry_append_only() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'ledger_entry is append-only: % forbidden (txid=%)',
        TG_OP, COALESCE(OLD.txid, 0);
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_ledger_entry_append_only
BEFORE UPDATE OR DELETE ON ledger_entry
FOR EACH ROW EXECUTE FUNCTION ledger_entry_append_only();

CREATE OR REPLACE FUNCTION account_guard() RETURNS trigger AS $$
DECLARE last_bal bigint; last_frz bigint;
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'account rows are not deletable (uid=%, cid=%)', OLD.uid, OLD.cid;
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF NEW.balance <> 0 OR NEW.frozen <> 0 THEN
      RAISE EXCEPTION 'new account must start at 0/0 (uid=%, cid=%)', NEW.uid, NEW.cid;
    END IF;
    RETURN NEW;
  END IF;

  SELECT balance_after, frozen_after INTO last_bal, last_frz
    FROM ledger_entry
   WHERE uid = NEW.uid AND cid = NEW.cid
   ORDER BY txid DESC LIMIT 1;

  IF last_bal IS NULL THEN
    RAISE EXCEPTION 'account update without any ledger_entry (uid=%, cid=%)', NEW.uid, NEW.cid;
  END IF;

  IF NEW.balance <> last_bal OR NEW.frozen <> last_frz THEN
    RAISE EXCEPTION
      'account(%/%) != latest ledger snapshot(%/%) for uid=% cid=%',
      NEW.balance, NEW.frozen, last_bal, last_frz, NEW.uid, NEW.cid;
  END IF;

  RETURN NEW;
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_account_guard
BEFORE INSERT OR UPDATE OR DELETE ON account
FOR EACH ROW EXECUTE FUNCTION account_guard();

-- --------------------------------------------------- §13 种子：$ 与平台保留账户
-- R2/R6：$ 显式插入 cid = 1；R26：status 恒为 listed（listed_at 必须非空）
INSERT INTO currency (cid, symbol, name, icon_url, owner_uid, decimals, total_supply,
                      supply_cap, status, deposit_amount, deposit_cid, listed_at)
VALUES (1, '$', '平台积分', '', 0, 0, 0, NULL, 'listed', 0, 1, now());

-- 让 IDENTITY 序列从 2 继续（$ 之后创建的自建单位不会撞 cid）
SELECT setval(pg_get_serial_sequence('currency', 'cid'), 1, true);

-- §13.2 保留 uid 登记
INSERT INTO ledger_owner (uid, owner_type, name) VALUES
  (  0, 'platform', '平台主体'),
  ( -1, 'platform', '手续费归集账户'),
  ( -2, 'platform', '佣金池'),
  ( -3, 'platform', '罚没账户');

-- R99：平台账户的 account 行由 migration 种子创建（开户必须 0/0，满足 R75）
INSERT INTO account (uid, cid, balance, frozen)
SELECT o.uid, 1, 0, 0 FROM ledger_owner o WHERE o.uid <= 0;
