-- ============================================================================
-- 0002_user_identity.sql · 账号身份表（登录必需）
-- 口径：
--   R22（Zang 裁定「采纳」）：新表统一 snake_case 无引号列名
--   spec §16 #5 / Zang §5.1：legacy `"user"."uID"` 为 text 列，本轮在**新库**上收敛为 bigint
--   R98：真实用户 uid 恒为正整数（> 0），平台保留 uid 走 ledger_owner
-- 字段集 = 现有代码实际查询的列（uID / EVM / time_reg / time_login_last / is_admin / bio）
-- 注：表名 `user` 是 SQL 保留字，必须双引号；列名一律 snake_case 不加引号。
-- ============================================================================

CREATE TABLE "user" (
  uid             bigint      GENERATED BY DEFAULT AS IDENTITY,
  evm             text        NOT NULL,
  bio             text        NOT NULL DEFAULT '',
  is_admin        boolean     NOT NULL DEFAULT false,
  time_reg        timestamptz NOT NULL DEFAULT now(),
  time_login_last timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_pk           PRIMARY KEY (uid),
  CONSTRAINT user_uid_positive CHECK (uid > 0),                -- R98
  CONSTRAINT user_evm_uniq     UNIQUE (evm),                    -- 一个钱包地址 = 一个账号
  CONSTRAINT user_evm_fmt      CHECK (evm ~ '^0x[0-9a-f]{40}$') -- 落库前统一小写（现有代码已 lower()）
);

-- 登录查找路径（getUserByEvm）恒为小写等值比较，上面 UNIQUE(evm) 已可支撑；
-- 额外补一个 lower() 表达式索引，兼容「库里存在历史大写地址」的过渡期查询。
CREATE INDEX idx_user_evm_lower ON "user" (LOWER(evm));
