-- ============================================================================
-- 0007_referral_and_commission_policy.sql · P2「十级返佣」数据契约
-- ============================================================================
-- 权威口径：docs/commission.spec.md **v0.2**（§2 DDL / §3 防环 / §6.5 CR80 / §9 白名单 /
--           §12 升级 / §13 借码）＋ docs/seafood.master-plan.md §5.19 / §5.20 / §5.21。
--   ⚠️ 本文件**只落** spec 已裁定的口径，不自行推导；一切「待拍板」项一律未落。
--
-- 本迁移做什么
--   ① `referral`：邀请图（child_uid PK / parent_uid / depth / bound_at；两列 FK 到 users(uid)；
--      自指禁令 CHECK；INSERT-only 不可变触发器）
--   ② `commission_policy`：版本化佣金政策（fee_rate_bp 100–500 / levels 1–10 / weights_bp /
--      effective_from UNIQUE / created_by **允许平台 id 0/-1/-2/-3 且无 FK**；INSERT-only）
--   ③ 政策写入守卫（CR83）：`Σweights_bp ∈ (0, 10000]` **且** `weights_bp[1] > 0` **且** 无负权重
--      **且** `len(weights_bp) == levels` ⇒ 失败一律 `23514` ⇒ 既有分类器归 `input` ⇒ **400**
--      （借 `LEDGER_AMOUNT_INVALID` + 前缀化 `reason`；**不新增错误码**）
--   ④ 默认政策种子行（裁定 #9 · 口径 A）⇒「无政策行」不可达
--   ⑤ 防环机制（裁定 #1）：**`depth` 不是防环机制**（只作遍历上界 / 审计）。
--      三件齐备 = ① 自指禁令（CHECK + 触发器）② 祖先检查 ③ 绑定串行化 ⇒ 见 §C
--      **2-环反例（先 A→B 再 B→A ⇒ 第二条必须被拒）**由 p2b-02 判负用例取证。
--   ⑥ 「Σ佣金 == 手续费」DB 侧后置断言（裁定 #14 / CR80）：**只读** `CONSTRAINT TRIGGER`
--      on `ledger_entry`（AFTER INSERT · DEFERRABLE INITIALLY DEFERRED）⇒ 失败抛**既有对账码**
--      `LEDGER_RECONCILE_MISMATCH`（关闭集第 33 码），**禁裸抛 23514、禁新增码**。
--   ⑦ 迁移自检（CR55）：把 P2 的准入前提（`-2` 白名单 + kind 关闭集）钉在 0007 里。
--
-- 本迁移**不**做什么（硬边界）
--   · **不改 `0001`–`0006` 的任何字节**（checksum 纪律：改一字节 ⇒ migrate.ts 整链 ABORT/exit 3）
--   · **不改 `ledger_post_event` 函数体**（裁定 #14 明令禁止）⇒ 只**新增** `ledger_entry` 上的
--     只读后置断言触发器（新增触发器**不属**表结构改动，见 spec §12.2）
--   · 不建 `commission_payout` 表（裁定 #4）；不新增错误码 / 不新增 kind（CR5 / CR75）
--   · 不改 `ledger_entry` 表结构、不写任何业务表（断言触发器**只读**）
--   · ⚠️ `-1` 白名单接纳 `job_fee` **不在本文件**（属既有对象行为改变）⇒ 落在 `0008`
--
-- 幂等：每条 DDL 自带存在性守卫（`IF NOT EXISTS` / `to_regclass` / `DROP TRIGGER IF EXISTS`
--      + `CREATE OR REPLACE`），种子行走 `WHERE NOT EXISTS`；`migrate.ts` 侧另有 checksum 去重。
--
-- 诚实边界（承 spec §2.2，不得夸大）
--   · 「不可变」是**防应用层事故的护栏**：`TRUNCATE` 不触发行触发器；管理员
--     `ALTER TABLE ... DISABLE TRIGGER USER` 可旁路（仓库内 purge-test-data.ts 即此法）。
--     **不得**表述为「绝对不可变」。
--   · 防环的结论只到「**按本文件的三件守卫写入的前提下**不成环」，不是「任何写入都不可能成环」。
--   · 断言触发器在**事务提交点**执行 ⇒ 它拦得住「提交」，拦不住「管理员关掉它再提交」。
-- ============================================================================

-- ============================================================================
-- §A 邀请图 `referral`（终身绑定 · 不可变 · INSERT-only）
-- ============================================================================

CREATE TABLE IF NOT EXISTS referral (
  child_uid  bigint      NOT NULL,
  parent_uid bigint      NOT NULL,
  depth      smallint    NOT NULL,
  bound_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT referral_pk         PRIMARY KEY (child_uid),
  -- 裁定 #6：业务表 FK 到 users(uid) 合法（R21 只约束账本表）
  CONSTRAINT referral_child_fk   FOREIGN KEY (child_uid)  REFERENCES users(uid),
  CONSTRAINT referral_parent_fk  FOREIGN KEY (parent_uid) REFERENCES users(uid),
  -- 防环第 ① 件（结构性）：自指禁令
  CONSTRAINT referral_no_self    CHECK (child_uid <> parent_uid),
  -- 裁定 #7：depth 不设上限（只 >= 1）；封顶的是分配层数 levels <= 10
  CONSTRAINT referral_depth_rng  CHECK (depth >= 1)
);

-- CR11：查「我邀请了谁」（读多写极少）
CREATE INDEX IF NOT EXISTS idx_referral_parent ON referral (parent_uid);

-- 不可变（CR8 / CR15）：与 ledger_entry 同法（触发器为主）
CREATE OR REPLACE FUNCTION referral_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'referral is append-only: % forbidden (child_uid=%)',
        TG_OP, COALESCE(OLD.child_uid, 0);
END $$;

DROP TRIGGER IF EXISTS trg_referral_append_only ON referral;
CREATE TRIGGER trg_referral_append_only
BEFORE UPDATE OR DELETE ON referral
FOR EACH ROW EXECUTE FUNCTION referral_append_only();


-- ============================================================================
-- §B 版本化佣金政策 `commission_policy`（INSERT-only · 版本化 · 不追溯）
-- ============================================================================

CREATE TABLE IF NOT EXISTS commission_policy (
  policy_id      bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fee_rate_bp    integer     NOT NULL,
  levels         smallint    NOT NULL,
  weights_bp     smallint[]  NOT NULL,
  effective_from timestamptz NOT NULL,
  created_by     bigint      NOT NULL,
  time_created   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT commission_policy_fee_rate_rng   CHECK (fee_rate_bp BETWEEN 100 AND 500),
  CONSTRAINT commission_policy_levels_rng     CHECK (levels BETWEEN 1 AND 10),
  CONSTRAINT commission_policy_weights_len    CHECK (array_length(weights_bp, 1) = levels),
  CONSTRAINT commission_policy_weights_nonneg CHECK (0 <= ALL (weights_bp)),
  -- 版本选择：无并列 + btree 可反向扫描 ⇒ 不另建 (effective_from DESC) 索引
  CONSTRAINT commission_policy_effective_uniq UNIQUE (effective_from),
  -- 裁定 #9：**去掉**指向 users 的 FK —— 种子行的作者是平台 id（P2 时点 users 可能 0 行）
  CONSTRAINT commission_policy_created_by_rng CHECK (created_by >= 0 OR created_by IN (-1, -2, -3))
);

CREATE OR REPLACE FUNCTION commission_policy_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'commission_policy is append-only: % forbidden (policy_id=%)',
        TG_OP, COALESCE(OLD.policy_id, 0);
END $$;

DROP TRIGGER IF EXISTS trg_commission_policy_append_only ON commission_policy;
CREATE TRIGGER trg_commission_policy_append_only
BEFORE UPDATE OR DELETE ON commission_policy
FOR EACH ROW EXECUTE FUNCTION commission_policy_append_only();

-- ---------------------------------------------------------------------------
-- §B.2 政策写入守卫（CR83）—— `Σ` 与「前缀全零」**无法用 CHECK 表达**（PG 的 CHECK 禁子查询 /
--      集合函数）⇒ 唯一落点 = BEFORE INSERT OR UPDATE 触发器。失败一律 `23514` ⇒ 既有分类器
--      （0005 `ledger_error_for_sqlstate`）对「其余 23514」归 `input` ⇒ `400`
--      `LEDGER_AMOUNT_INVALID`（+ 前缀化 reason）。**不得**改 0005 的分桶、**不得**新增错误码。
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION commission_policy_weights_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE v_sum integer;
BEGIN
  IF array_length(NEW.weights_bp, 1) IS DISTINCT FROM NEW.levels THEN
    RAISE EXCEPTION 'commission_policy_weights_guard: weights_bp length (%) <> levels (%)',
          array_length(NEW.weights_bp, 1), NEW.levels
      USING ERRCODE = '23514';
  END IF;
  v_sum := COALESCE((SELECT sum(w) FROM unnest(NEW.weights_bp) AS w), 0);
  IF (SELECT count(*) FROM unnest(NEW.weights_bp) AS w WHERE w IS NULL OR w < 0) > 0 THEN
    RAISE EXCEPTION 'commission_policy_weights_guard: negative/null weight in %', NEW.weights_bp
      USING ERRCODE = '23514';
  END IF;
  IF v_sum > 10000 THEN
    RAISE EXCEPTION 'commission_policy_weights_guard: sum(weights_bp) = % > 10000', v_sum
      USING ERRCODE = '23514';
  END IF;
  -- 裁定 #16：退化分母 W = 0 在**政策写入时**就拒（运行时因此不可达）
  IF v_sum = 0 THEN
    RAISE EXCEPTION 'commission_policy_weights_guard: sum(weights_bp) = 0 (degenerate denominator W = 0)'
      USING ERRCODE = '23514';
  END IF;
  -- 裁定 #16 / master-plan §5.21 #2：可静态判定式 = `weights_bp[1] > 0`（M = min(levels, 链深) ∈ [1,levels]）
  IF NEW.weights_bp[1] IS NULL OR NEW.weights_bp[1] = 0 THEN
    RAISE EXCEPTION 'commission_policy_weights_guard: weights_bp[1] = % (prefix-all-zero => W = 0 when M = 1)',
          NEW.weights_bp[1]
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_commission_policy_weights_guard ON commission_policy;
CREATE TRIGGER trg_commission_policy_weights_guard
BEFORE INSERT OR UPDATE ON commission_policy
FOR EACH ROW EXECUTE FUNCTION commission_policy_weights_guard();

-- ---------------------------------------------------------------------------
-- §B.3 默认政策种子（裁定 #9 · 口径 A）—— `policy(T)` 恒有返回值 ⇒「无政策行」不可达。
--      weights_bp = spec §4.4 的默认矩阵（Σ = 10000）；created_by = 0（平台 id）。
-- ---------------------------------------------------------------------------
INSERT INTO commission_policy (fee_rate_bp, levels, weights_bp, effective_from, created_by)
SELECT 100,
       10,
       ARRAY[3000, 2000, 1500, 1000, 800, 600, 500, 300, 200, 100]::smallint[],
       '1970-01-01T00:00:00Z'::timestamptz,
       0
 WHERE NOT EXISTS (
   SELECT 1 FROM commission_policy WHERE effective_from = '1970-01-01T00:00:00Z'::timestamptz);


-- ============================================================================
-- §C 防环机制（裁定 #1 · CR78）—— 自指禁令 + 祖先检查 + 绑定串行化
-- ============================================================================
-- ⛔ **`depth` 不是防环机制**（v0.2 裁定 #1）：`depth = 父.depth + 1` **只校验新插入的那条边**，
--    既有边会被后来的插入**追溯破坏**：先插 `A→B`（A.depth=1）再插 `B→A`（B.depth=2）⇒
--    两次插入的等式**都成立**、**2-环照样形成**（spec §3.2 反例表已逐行验算）。
--    ⇒ 任何「只验 depth 等式」的实现都必然漏。
--
-- 实现选择（**为什么选触发器而不是只在应用层 / 只在函数里检查**）：
--   ① 触发器是**任何 INSERT 路径都绕不过**的闸 —— 应用层守卫（或只提供一个 `referral_bind()`
--      函数）在「有人直接写 SQL / 有别的写路径」时就失效；`0007` 的职责是让**库自己**拒绝成环。
--   ② **串行化点必须与祖先检查在同一事务、且在检查之前**（spec §3.3 ②）⇒ 放进同一个
--      BEFORE INSERT 触发器（`users` 两行 `FOR UPDATE`、**按 uid 升序**，对齐 R79/R93 精神），
--      这样「锁 → 查 → 插」的顺序对**所有**写入路径都是同一个，不存在「某个入口忘加锁」。
--   ③ 另**附**一个可复用写入函数 `referral_bind(child, parent)`（幂等语义，CR19），供应用层
--      作为唯一入口使用；它只是**便利层**，真正的闸仍是触发器 + CHECK。
--   ④ `depth` 在同一个触发器里由 DB 侧算（CR16：**不得**作为 API 入参暴露给调用方）。
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION referral_cycle_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_hit boolean;
BEGIN
  -- ① 自指禁令（结构性闸是 `referral_no_self`；此处再挡一次以给出机读 reason）
  IF NEW.child_uid = NEW.parent_uid THEN
    PERFORM ledger_raise('LEDGER_AMOUNT_INVALID', jsonb_build_object(
      'reason', 'REFERRAL_SELF_BIND',
      'child_uid', NEW.child_uid::text, 'parent_uid', NEW.parent_uid::text));
  END IF;

  -- ② 绑定串行化点：同一事务内**先**锁 users 的两行（uid 升序）。
  --    目的：`A→B` 与 `B→A` 并发时两边争抢同一对 users 行 ⇒ 后者等前者提交后再跑 ③，
  --    此时新边已可见 ⇒ ③ 能拒绝（spec §3.3 ② 的设计意图）。
  PERFORM u.uid FROM users u WHERE u.uid IN (NEW.child_uid, NEW.parent_uid)
   ORDER BY u.uid FOR UPDATE;

  -- ③ 祖先检查：断言**新父 P 不是 child C 的后代**（等价式 C ∉ ancestors(P)）：
  --    从 P 沿 parent_uid 上行，遇 C 即拒。步行上界 1000 只为防「库里已有环」时无限递归
  --    （不是防环机制本身；防环 = 本检查 + 串行化）。
  WITH RECURSIVE up AS (
    SELECT r.parent_uid AS cur, 1 AS d
      FROM referral r WHERE r.child_uid = NEW.parent_uid
    UNION ALL
    SELECT r.parent_uid, up.d + 1
      FROM referral r JOIN up ON r.child_uid = up.cur
     WHERE up.d < 1000
  )
  SELECT EXISTS (SELECT 1 FROM up WHERE cur = NEW.child_uid) INTO v_hit;

  IF v_hit THEN
    PERFORM ledger_raise('LEDGER_AMOUNT_INVALID', jsonb_build_object(
      'reason', 'REFERRAL_CYCLE_REJECTED',
      'child_uid', NEW.child_uid::text, 'parent_uid', NEW.parent_uid::text));
  END IF;

  -- ④ depth 由 DB 侧算（父无行 ⇒ 1）—— 只作层级标签 / 遍历上界 / 审计，不承担防环
  NEW.depth := 1 + COALESCE((SELECT r.depth FROM referral r WHERE r.child_uid = NEW.parent_uid), 0);
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_referral_cycle_guard ON referral;
CREATE TRIGGER trg_referral_cycle_guard
BEFORE INSERT ON referral
FOR EACH ROW EXECUTE FUNCTION referral_cycle_guard();

COMMENT ON FUNCTION referral_cycle_guard() IS
  'P2 裁定 #1：防环 = 自指禁令 + 祖先检查（新父 P 不是 child C 的后代）+ 绑定串行化（users 两行 FOR UPDATE）。depth 只是层级标签，不是防环机制。';

-- 便利层：应用层的**唯一**绑定入口（幂等语义 CR19）。真正的闸仍在上面的触发器。
CREATE OR REPLACE FUNCTION referral_bind(p_child_uid bigint, p_parent_uid bigint)
RETURNS jsonb
LANGUAGE plpgsql AS $$
DECLARE
  v_existing referral%ROWTYPE;
  v_new      referral%ROWTYPE;
BEGIN
  IF p_child_uid = p_parent_uid THEN
    PERFORM ledger_raise('LEDGER_AMOUNT_INVALID', jsonb_build_object(
      'reason', 'REFERRAL_SELF_BIND',
      'child_uid', p_child_uid::text, 'parent_uid', p_parent_uid::text));
  END IF;

  -- 串行化点（与触发器同序 ⇒ 不会自相死锁）
  PERFORM u.uid FROM users u WHERE u.uid IN (p_child_uid, p_parent_uid)
   ORDER BY u.uid FOR UPDATE;

  SELECT * INTO v_existing FROM referral r WHERE r.child_uid = p_child_uid;
  IF FOUND THEN
    IF v_existing.parent_uid = p_parent_uid THEN
      RETURN jsonb_build_object(
        'ok', true, 'idempotent_replay', true,
        'child_uid', v_existing.child_uid::text, 'parent_uid', v_existing.parent_uid::text,
        'depth', v_existing.depth::text, 'bound_at', to_jsonb(v_existing.bound_at));
    END IF;
    -- CR19②：同一 child 已有行但 parent 不同 ⇒ 409（借码，不新增码）
    PERFORM ledger_raise('LEDGER_IDEMPOTENCY_CONFLICT', jsonb_build_object(
      'reason', 'REFERRAL_ALREADY_BOUND',
      'child_uid', p_child_uid::text,
      'bound_parent_uid', v_existing.parent_uid::text,
      'requested_parent_uid', p_parent_uid::text));
  END IF;

  -- depth 占位 0：由 trg_referral_cycle_guard 覆写；若守卫被摘掉 ⇒ CHECK(depth>=1) 立刻炸（响亮的失败）
  INSERT INTO referral (child_uid, parent_uid, depth) VALUES (p_child_uid, p_parent_uid, 0)
  RETURNING * INTO v_new;

  RETURN jsonb_build_object(
    'ok', true, 'idempotent_replay', false,
    'child_uid', v_new.child_uid::text, 'parent_uid', v_new.parent_uid::text,
    'depth', v_new.depth::text, 'bound_at', to_jsonb(v_new.bound_at));
END $$;

COMMENT ON FUNCTION referral_bind(bigint, bigint) IS
  'P2 应用层唯一绑定入口（幂等：同 (C,P) 读回 replay；C 已绑他人 ⇒ 409 REFERRAL_ALREADY_BOUND）。防环由 trg_referral_cycle_guard 强制。';


-- ============================================================================
-- §D DB 侧「Σ佣金 == 手续费」后置断言（裁定 #14 · CR80）
-- ============================================================================
-- 允许：在 `ledger_entry` 上**新增只读后置断言触发器**（不属「改表结构」、不属「改函数体」）。
-- 禁止（逐条照做）：① 改 `ledger_post_event` 函数体；② 改 `0001`–`0006`；③ 改 `ledger_entry`
--   表结构；④ 触发器**写任何表**；⑤ 用 `FOR EACH STATEMENT`（函数内每条 INSERT 是独立语句 ⇒
--   会在事件中途误报）；⑥ **裸抛 `23514`**（既有分类器把「其余 23514」归 `input` ⇒ 400，
--   而断言失败是**内部不变式违反** ⇒ 必须 `defect` / 500）。
--
-- 失败落点（master-plan §5.21 #3 裁定）：抛**既有的对账不符码** `LEDGER_RECONCILE_MISMATCH`
--   （关闭集第 33 码；SQLSTATE 投影 = `LD032`，见 0004 `ledger_sqlstate_of`）。
--   真库探针读数（p2b-03）：`ledger_error_for_sqlstate('LD032')` ⇒ `bucket = defect` ⇒ **500 类**；
--   且 TS 侧 `LEDGER_SQLSTATE_TO_CODE['LD032'] = 'LEDGER_RECONCILE_MISMATCH'`。
--   ⚠️ 诚实登记：该码在 TS 错误表里 `status = null`（§14 #33「对账脚本退出码语义，不映射 HTTP」），
--      既有逃逸扫描显式豁免它（`code !== 'LEDGER_RECONCILE_MISMATCH'`）⇒ 断言失败**不落 400**。
--
-- 断言范围（CR80 原文 = 对「佣金分录」做断言；**并经相容性对拍**，见 master-plan §5.21 #4）：
--   触发器对**相关行**触发，相关 = `kind='commission' AND uid=-2`（出池方）
--                                 或 `kind='job_fee' AND uid=-2 AND delta>0`（入池方）；
--   然后在**提交点**对整个 `event_root_key` 断言 `Σ出池 == Σ入池`。
--   · 四种 P2 形状全部满足：正常 / 短链（Σ出池 == 入池）✓；无邀请人（fee 入 `-1`，`-2` 不参与）✓；
--     零额（既无 `job_fee` 也无 `commission` ⇒ 不触发）✓。
--   · **相容性对拍读数（p2b-00，真库全表 240 行）**：全库 `kind='job_fee'` 行 **0 条**、
--     `kind='commission'` 行 **0 条** ⇒ 不存在「有 `job_fee` 入 `-2` 而无 `commission`」的历史 / 回归行
--     ⇒ **无需收窄到「含 commission 行的事件」**；本实现仍以「相关行」为触发条件（= 收窄），
--       因为它同时满足 CR80 原文与「不让历史形状被判死」两条。
--   · 已知边界（诚实）：**只**断言 `-2` 池的进出守恒；**不**断言「受益人分对了人」（归属由 M4/M5 覆盖）。
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION ledger_assert_commission_conservation() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_key      text;
  v_pool_in  bigint;
  v_paid_out bigint;
  v_comm_rows integer;
  v_fee_rows  integer;
BEGIN
  -- 只读断言：不写任何表。仅对「相关行」触发（见文件头 §D 的范围说明）。
  IF NOT (NEW.kind = 'commission' AND NEW.uid = -2)
     AND NOT (NEW.kind = 'job_fee' AND NEW.uid = -2 AND NEW.delta > 0) THEN
    RETURN NULL;
  END IF;

  v_key := COALESCE(NEW.event_root_key, split_part(NEW.idempotency_key, '#', 1));

  SELECT COALESCE(sum(CASE WHEN e.uid = -2 AND e.kind = 'job_fee'    THEN e.delta  ELSE 0 END), 0),
         COALESCE(sum(CASE WHEN e.uid = -2 AND e.kind = 'commission' THEN -e.delta ELSE 0 END), 0),
         count(*) FILTER (WHERE e.uid = -2 AND e.kind = 'commission'),
         count(*) FILTER (WHERE e.uid = -2 AND e.kind = 'job_fee')
    INTO v_pool_in, v_paid_out, v_comm_rows, v_fee_rows
    FROM ledger_entry e
   WHERE COALESCE(e.event_root_key, split_part(e.idempotency_key, '#', 1)) = v_key;

  IF v_pool_in <> v_paid_out THEN
    PERFORM ledger_raise('LEDGER_RECONCILE_MISMATCH', jsonb_build_object(
      'reason', 'COMMISSION_SPLIT_SUM_MISMATCH',
      'idempotency_key', v_key,
      'pool_in', v_pool_in::text, 'commission_out', v_paid_out::text,
      'commission_rows', v_comm_rows::text, 'job_fee_rows', v_fee_rows::text));
  END IF;

  RETURN NULL;
END $$;

COMMENT ON FUNCTION ledger_assert_commission_conservation() IS
  'P2 CR80：同一 event_root_key 的 Σcommission(出 -2) == Σjob_fee(入 -2)。只读断言，失败抛 LEDGER_RECONCILE_MISMATCH(defect/500)。';

DROP TRIGGER IF EXISTS trg_ledger_entry_commission_conservation ON ledger_entry;
CREATE CONSTRAINT TRIGGER trg_ledger_entry_commission_conservation
AFTER INSERT ON ledger_entry
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION ledger_assert_commission_conservation();


-- ============================================================================
-- §E 迁移自检（CR55）—— 把 P2 的**准入前提**钉住；失败即中止迁移（不得静默跳过）
-- ============================================================================
-- 依据 spec §9.3：`commission` 出账（`-2` 的 debit）是 P2 的前提，但它落在 `0001`–`0006` 里；
-- 若日后被「清理」收紧 ⇒ P2 会在生产结算那一刻才以 LD021 硬失败。⇒「不安检不许起飞」。
DO $$
BEGIN
  -- ① 行为探针：`-2` 的 `commission` 减方必须放行（不放行 ⇒ ledger_raise 直接中止本迁移）
  PERFORM ledger_assert_platform_mutation(-2::bigint, 'commission', 'debit');
  -- ② 行为探针：`-2` 的 `job_fee` 增方必须放行（池子的入项）
  PERFORM ledger_assert_platform_mutation(-2::bigint, 'job_fee', 'credit');
  -- ③ kind 关闭集仍含本事件只用到的三个 kind
  IF NOT (ledger_kind_ok('job_payout') AND ledger_kind_ok('job_fee') AND ledger_kind_ok('commission')) THEN
    RAISE EXCEPTION '0007 self-check FAILED: kind close set no longer contains job_payout/job_fee/commission';
  END IF;
  -- ④ 结构性自检：两张表 + 断言触发器 + 种子行都在
  IF to_regclass('public.referral') IS NULL OR to_regclass('public.commission_policy') IS NULL THEN
    RAISE EXCEPTION '0007 self-check FAILED: referral / commission_policy missing';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger
                  WHERE tgrelid = 'public.ledger_entry'::regclass
                    AND tgname = 'trg_ledger_entry_commission_conservation'
                    AND NOT tgisinternal) THEN
    RAISE EXCEPTION '0007 self-check FAILED: commission conservation trigger missing';
  END IF;
  IF (SELECT count(*) FROM commission_policy) < 1 THEN
    RAISE EXCEPTION '0007 self-check FAILED: default commission_policy seed missing';
  END IF;
END $$;
