-- ============================================================================
-- 0013_job_core.sql · P3 第一柱（招工）· `job` 表 + 状态机守卫 + 业务编排函数
-- ============================================================================
-- 权威口径：docs/data-layer.spec.md **v0.3**（220752 B / md5 0a8e228dcbc1dcb517a378ca46dee79c）
--   §6.1  `0013` = `job` / `job_application` / `job_submission` + 状态机守卫 + 编排函数
--   §6.2  `job` 逐列契约（DL50）· 状态机（DL51）· 三条守卫（DL52）· 三个索引（DL53）
--   §6.7  通用规约：三件套（DL75）· 可变表用状态机守卫（DL76）· uid 列 FK users（DL78）·
--         禁 DELETE（DL79）· snake_case（DL80）· 索引预算（DL74）
--   §7.1  业务动作 → kind 映射（发布/取消/结算）· DL84 事件级 kind 白名单 · DL86 `-2`/`-1` 分支
--   §8    幂等键四类前缀（DL93）· 创建类 `cli:`（DL94）· 键只由不可变业务标识派生（DL95）·
--         路由层强制指纹（DL96）· 重放语义（DL98）· 无分录的写不造占位（DL99，本文件不涉及）
--   DL20  ✅ 采纳提案 A：业务编排函数（业务行锁 → 派生分录 → 调既有 ledger_post_event → 回写）
--   DL141 加锁全序 = 业务行（主键升序）→ currency（cid 升序）→ account（uid 升序）
--   DL142 编排函数只由迁移创建、**函数体内禁任何 DDL**
--   DL143 每次调用必带幂等键（键由本函数按 §8 确定性派生）+ `ref_id` 落账本引用列
--   DL144 重放语义逐字对齐 R51/R52：同键同指纹 ⇒ 200 重放且**不重写业务行**、**不追加
--         `ledger_event_keys` 项**；同键异指纹 ⇒ 409
--   DL149 C8 判负用例（「同键重放不追加 ledger_event_keys 项」）—— 由 scripts/p3j-03 取证
--   DL151 新数据层所有 SQL 显式限定 `public.`（`neon_auth.account` 同名陷阱）
--   §11.2 状态类错误借码（C5 已裁）：`LEDGER_CURRENCY_INVALID_TRANSITION`（409, integrity）
--         + `details.field='job.status'` + `reason='JOB_STATE_INVALID'`（**唯一可执行口径 = 大写**）
--   已知债 DL148：码名语义窄化（借币种状态机码），将来启用专用码必须「正向+反向+bucket」一次到位
--
-- 本迁移做什么
--   ① `public.job`：逐列照 §6.2 的 DL50（**不增删列、不自创列名**）+ 状态 CHECK + FK users/currency
--   ② `public.job_status_transition_ok(from,to)`：状态机白名单的**唯一真源**（DL51 写死）
--   ③ 三条 BEFORE UPDATE 守卫（DL52：规则独立可测）+ time_updated 自动刷新（DL75③）+ 禁 DELETE（DL79）
--   ④ 三个必建索引（DL53）
--   ⑤ `public.job_settle_plan(...)`：结算分录派生（commission.spec §5.3 顺序铁律 + §6.2 最大余数法）
--   ⑥ `public.job_post_event(payload jsonb)`：编排函数（op = publish | refund | settle）
--
-- 本迁移**不**做什么（硬边界）
--   · **不改 `0001`–`0012` 的任何字节**（checksum 冻结；`migrate.ts` 会整链 ABORT/exit 3）
--   · **不改 `ledger_post_event` 的函数体**（CR81 只禁「改函数体」；本文件只**新增**新函数）
--   · 不建 `job_application` / `job_submission`（属本柱后续单，一迁一主题 DL46）
--   · 不动 `currency` / `account` / `ledger_*` 的**数据**、不动既有 8 张基表结构
--   · 不新增 `kind`（DL81：0 个扩展）、不新增错误码（DL119：一律映射既有 33 码）
--   · 不接路由（`src/` 本单不改；招工写路由留下一单）
--
-- 幂等（DL48）：`CREATE TABLE IF NOT EXISTS` / `CREATE INDEX IF NOT EXISTS` /
--   `CREATE OR REPLACE FUNCTION` / `DROP TRIGGER IF EXISTS` + `CREATE TRIGGER`；
--   末尾 apply-time `DO` 自检（结构 + 纯函数断言 + 结算派生守恒）；任一失败 ⇒ 整迁移回滚、不写版本行。
--
-- 诚实边界（不得夸大）
--   · 「不可变/一次写定」是**防应用层事故的护栏**：`TRUNCATE` 不触发行触发器，超管
--     `ALTER TABLE ... DISABLE TRIGGER USER` 可旁路 ⇒ 不得表述为「绝对不可变」。
--   · 本函数的幂等重放探测是**只读**的「键是否已落账」查询（与 `0012` 的重放前置闸同法）：
--     它只决定「是否还走业务状态机校验」，**不**取代账本的权威幂等探针（R51 的首条分录
--     `ON CONFLICT` + 唯一约束 `ledger_idem_uniq` 仍是落账决策的唯一权威）。
--   · 状态机违反的 SQLSTATE **不是** `23514`（DL52① 的旧写法），而是借码 `LD011`
--     （正向 `ledger_sqlstate_of` → `LEDGER_CURRENCY_INVALID_TRANSITION`，bucket=integrity ⇒ 409）。
--     理由：C5/§11.2 要求调用方按 `code` 分支拿到 **409 + JOB_STATE_INVALID**；裸 `23514` 会
--     经 `0009` 反向映射落到 `input`（400）桶，与 C5 直接冲突。本处口径张力已登记台账。
-- ============================================================================


-- ============================================================================
-- §A 状态机白名单（DL51）—— 唯一真源，供触发器与编排函数共用
-- ============================================================================
CREATE OR REPLACE FUNCTION public.job_status_transition_ok(p_from text, p_to text)
RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE p_from
    WHEN 'open'      THEN p_to IN ('accepted', 'cancelled')
    WHEN 'accepted'  THEN p_to IN ('submitted', 'rejected')
    WHEN 'submitted' THEN p_to IN ('settled', 'rejected', 'disputed')
    WHEN 'disputed'  THEN p_to IN ('settled', 'cancelled')
    ELSE false            -- settled / rejected / cancelled = 无出边（终态；rejected 在白名单里无后继）
  END
$$;

COMMENT ON FUNCTION public.job_status_transition_ok(text, text) IS
  'DL51 状态机白名单唯一真源：open→{accepted,cancelled}；accepted→{submitted,rejected}；submitted→{settled,rejected,disputed}；disputed→{settled,cancelled}；settled/cancelled/rejected 无出边。';


-- ============================================================================
-- §B `public.job` 表（逐列照 §6.2 / DL50）
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.job (
  job_id             bigint      GENERATED BY DEFAULT AS IDENTITY,
  employer_uid       bigint      NOT NULL,
  worker_uid         bigint,
  cid                bigint      NOT NULL,
  reward             bigint      NOT NULL,
  title              text        NOT NULL DEFAULT '',
  description        text        NOT NULL DEFAULT '',
  status             text        NOT NULL DEFAULT 'open',
  create_key         text        NOT NULL,
  escrow_txid        bigint,
  settle_txid        bigint,
  ledger_event_keys  text[]      NOT NULL DEFAULT '{}',
  time_created       timestamptz NOT NULL DEFAULT now(),
  time_updated       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT job_pk              PRIMARY KEY (job_id),
  -- 三件套 ①（DL75 / DL50）：创建幂等键，指纹口径与 R51/R52 一致
  CONSTRAINT job_create_key_uniq UNIQUE (create_key),
  -- DL50：`reward` 是业务约定额（不是余额，DL3）
  CONSTRAINT job_reward_positive CHECK (reward > 0),
  -- DL51 状态白名单（§6.2 的 7 态；`disputed` 属 P6 仲裁路径，列先进关闭集）
  CONSTRAINT job_status_enum     CHECK (status IN ('open','accepted','submitted','settled','disputed','rejected','cancelled')),
  CONSTRAINT job_employer_fk     FOREIGN KEY (employer_uid) REFERENCES public.users(uid),
  CONSTRAINT job_worker_fk       FOREIGN KEY (worker_uid)   REFERENCES public.users(uid),
  CONSTRAINT job_cid_fk          FOREIGN KEY (cid)          REFERENCES public.currency(cid)
);

COMMENT ON TABLE public.job IS
  'P3 招工第一柱主表（data-layer.spec v0.3 §6.2 / DL50）。账本引用列 escrow_txid/settle_txid 不建 FK（R21 方向：反向引用用 bigint + 对账）。';

-- DL53：三个必建索引（`create_key` 的唯一约束自带索引，不另建）
CREATE INDEX IF NOT EXISTS idx_job_status_time ON public.job (status, time_created DESC);
CREATE INDEX IF NOT EXISTS idx_job_employer    ON public.job (employer_uid, time_created DESC);
CREATE INDEX IF NOT EXISTS idx_job_worker      ON public.job (worker_uid, time_created DESC) WHERE worker_uid IS NOT NULL;


-- ============================================================================
-- §C 守卫触发器（DL52 三条 + DL75③ 时间戳 + DL79 禁 DELETE）
-- ============================================================================

-- C1 状态转移白名单（DL51 / DL52①）
CREATE OR REPLACE FUNCTION public.job_status_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF NOT public.job_status_transition_ok(OLD.status, NEW.status) THEN
      PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
        jsonb_build_object('field', 'job.status', 'reason', 'JOB_STATE_INVALID',
                           'from', OLD.status, 'to', NEW.status, 'job_id', OLD.job_id::text));
    END IF;
  END IF;
  RETURN NEW;
END $$;

COMMENT ON FUNCTION public.job_status_guard() IS
  'DL52① / DL51：状态转移白名单（唯一真源 = public.job_status_transition_ok）。违反 ⇒ 借码 LD011 LEDGER_CURRENCY_INVALID_TRANSITION（integrity ⇒ 409）+ reason=JOB_STATE_INVALID（大写为唯一口径）。';

-- C2 账本引用列一次写定（DL52②；`OLD IS NULL` 时允许写入，之后禁改、禁清空）
CREATE OR REPLACE FUNCTION public.job_ledger_ref_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.escrow_txid IS NOT NULL AND NEW.escrow_txid IS DISTINCT FROM OLD.escrow_txid THEN
    PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
      jsonb_build_object('field', 'job.escrow_txid', 'reason', 'job_ledger_ref_immutable',
                         'old', OLD.escrow_txid::text,
                         'new', CASE WHEN NEW.escrow_txid IS NULL THEN NULL ELSE NEW.escrow_txid::text END,
                         'job_id', OLD.job_id::text));
  END IF;
  IF OLD.settle_txid IS NOT NULL AND NEW.settle_txid IS DISTINCT FROM OLD.settle_txid THEN
    PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
      jsonb_build_object('field', 'job.settle_txid', 'reason', 'job_ledger_ref_immutable',
                         'old', OLD.settle_txid::text,
                         'new', CASE WHEN NEW.settle_txid IS NULL THEN NULL ELSE NEW.settle_txid::text END,
                         'job_id', OLD.job_id::text));
  END IF;
  RETURN NEW;
END $$;

COMMENT ON FUNCTION public.job_ledger_ref_guard() IS
  'DL52②：escrow_txid / settle_txid 一次写定（OLD 非 NULL 后禁改、禁清空）。护栏强度=行触发器；不拦 TRUNCATE / DISABLE TRIGGER USER。';

-- C3 核心业务字段冻结（DL52③）+ worker/create_key 一次写定（防「托管后改价」）
CREATE OR REPLACE FUNCTION public.job_core_immutable_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.status <> 'open'
     AND (NEW.employer_uid IS DISTINCT FROM OLD.employer_uid
          OR NEW.cid       IS DISTINCT FROM OLD.cid
          OR NEW.reward    IS DISTINCT FROM OLD.reward) THEN
    PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
      jsonb_build_object('field', 'job.core_fields', 'reason', 'job_core_fields_immutable',
                         'status', OLD.status, 'job_id', OLD.job_id::text));
  END IF;
  IF OLD.worker_uid IS NOT NULL AND NEW.worker_uid IS DISTINCT FROM OLD.worker_uid THEN
    PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
      jsonb_build_object('field', 'job.worker_uid', 'reason', 'job_worker_immutable',
                         'old', OLD.worker_uid::text,
                         'new', CASE WHEN NEW.worker_uid IS NULL THEN NULL ELSE NEW.worker_uid::text END,
                         'job_id', OLD.job_id::text));
  END IF;
  IF NEW.create_key IS DISTINCT FROM OLD.create_key THEN
    PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
      jsonb_build_object('field', 'job.create_key', 'reason', 'job_create_key_immutable',
                         'job_id', OLD.job_id::text));
  END IF;
  RETURN NEW;
END $$;

COMMENT ON FUNCTION public.job_core_immutable_guard() IS
  'DL52③：employer_uid / cid / reward 在 status <> ''open'' 后不可变（防托管后改价）；worker_uid 选定后一次写定；create_key 永不可改。';

-- C4 时间戳统一刷新（DL75③：不接受客户端传时间，R5）
CREATE OR REPLACE FUNCTION public.job_touch_time_updated() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.time_updated := now();
  RETURN NEW;
END $$;

COMMENT ON FUNCTION public.job_touch_time_updated() IS
  'DL75③ / R5：time_updated 由 BEFORE UPDATE 触发器统一刷新，不接受客户端传时间。';

-- C5 禁 DELETE（DL79：业务行的终结 = 状态位）
CREATE OR REPLACE FUNCTION public.job_no_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
    jsonb_build_object('field', 'job', 'reason', 'job_delete_forbidden', 'job_id', OLD.job_id::text));
END $$;

COMMENT ON FUNCTION public.job_no_delete() IS
  'DL79：业务表禁物理删除（终结 = status 位）。触发器执行序按名字母序：core_immutable → ledger_ref → status → touch。';

DROP TRIGGER IF EXISTS trg_job_core_immutable_guard ON public.job;
CREATE TRIGGER trg_job_core_immutable_guard
  BEFORE UPDATE ON public.job
  FOR EACH ROW EXECUTE FUNCTION public.job_core_immutable_guard();

DROP TRIGGER IF EXISTS trg_job_ledger_ref_guard ON public.job;
CREATE TRIGGER trg_job_ledger_ref_guard
  BEFORE UPDATE ON public.job
  FOR EACH ROW EXECUTE FUNCTION public.job_ledger_ref_guard();

DROP TRIGGER IF EXISTS trg_job_status_guard ON public.job;
CREATE TRIGGER trg_job_status_guard
  BEFORE UPDATE ON public.job
  FOR EACH ROW EXECUTE FUNCTION public.job_status_guard();

DROP TRIGGER IF EXISTS trg_job_touch_time_updated ON public.job;
CREATE TRIGGER trg_job_touch_time_updated
  BEFORE UPDATE ON public.job
  FOR EACH ROW EXECUTE FUNCTION public.job_touch_time_updated();

DROP TRIGGER IF EXISTS trg_job_no_delete ON public.job;
CREATE TRIGGER trg_job_no_delete
  BEFORE DELETE ON public.job
  FOR EACH ROW EXECUTE FUNCTION public.job_no_delete();


-- ============================================================================
-- §D 结算分录派生（commission.spec §5.3 顺序铁律 + §6.2 最大余数法；DL86 分支）
-- ============================================================================
-- 纯派生函数（STABLE，只读 commission_policy / referral）：
--   fee = (gross × fee_rate_bp + 5000) / 10000      -- CR38：全项目唯一取整点（半进位）
--   net = gross − fee                               -- CR39 / D14：减法求净额，net+fee == gross 恒等
--   M   = min(policy.levels, chain_depth)           -- CR46
--   W   = Σ_{L<=M} w_L                              -- CR47：重归一化的唯一分母（不是 10000）
--   q_L = (P × w_L) / W ; r_L = (P × w_L) mod W ; D = P − Σq
--   order = (r_L DESC, L DESC) 全序 ⇒ 前 D 名 +1 ⇒ Σx_L == P 逐分不差
--   x_L = 0 的层不建分录（CR48）；fee = 0 ⇒ 只有 job_payout 两条（CR51）；
--   无邀请人（M=0）⇒ fee 增方 = uid −1（平台收入，DL86），不得写 −2。
CREATE OR REPLACE FUNCTION public.job_settle_plan(
  p_job_id bigint, p_employer bigint, p_worker bigint, p_cid bigint, p_gross bigint
) RETURNS jsonb
LANGUAGE plpgsql STABLE AS $$
DECLARE
  v_bp      integer;
  v_levels  smallint;
  v_weights smallint[];
  v_cur     bigint;
  v_anc     bigint;
  v_chain   bigint[] := '{}';
  v_fee     bigint;
  v_net     bigint;
  v_pool    bigint;
  v_credit  bigint;
  v_M       integer;
  v_w       bigint[] := '{}';
  v_wsum       bigint := 0;
  v_q       bigint[] := '{}';
  v_r       bigint[] := '{}';
  v_x       bigint[] := '{}';
  v_order   integer[];
  v_sumq    bigint := 0;
  v_sumx    bigint := 0;
  v_D       bigint;
  v_layers  jsonb := '[]'::jsonb;
  v_entries jsonb := '[]'::jsonb;
  v_memo    text;
  v_N       integer := 0;
  i         integer;
BEGIN
  IF p_gross IS NULL OR p_gross <= 0 THEN
    PERFORM public.ledger_raise('LEDGER_AMOUNT_NOT_POSITIVE',
      jsonb_build_object('field', 'reward', 'value', COALESCE(p_gross::text, 'null')));
  END IF;
  IF p_worker IS NULL THEN
    -- 未选定打工人 = 无结算对象（§11.2「无权/状态类」借码；reason 小写下划线形态）
    PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
      jsonb_build_object('field', 'job.worker_uid', 'reason', 'not_job_worker', 'job_id', p_job_id::text));
  END IF;

  -- 政策取「now() 生效的最新一版」（CR23：policy(now())；commission_policy 是 INSERT-only）
  SELECT cp.fee_rate_bp, cp.levels, cp.weights_bp
    INTO v_bp, v_levels, v_weights
    FROM public.commission_policy cp
   WHERE cp.effective_from <= now()
   ORDER BY cp.effective_from DESC
   LIMIT 1;
  IF NOT FOUND THEN
    PERFORM public.ledger_raise('LEDGER_FEE_RATE_INVALID',
      jsonb_build_object('reason', 'policy_weights_all_zero', 'job_id', p_job_id::text,
                         'note', 'no commission_policy row effective at now()'));
  END IF;

  v_fee  := (p_gross * v_bp + 5000) / 10000;   -- CR38
  v_net  := p_gross - v_fee;                    -- CR39
  v_pool := v_fee;

  -- 链：从 worker 向上遍历 ≤ levels 层（DL51 归属：上级受益人 = 直接邀请人起逐层上溯）
  v_cur := p_worker;
  FOR i IN 1..LEAST(v_levels::integer, 10) LOOP
    SELECT r.parent_uid INTO v_anc FROM public.referral r WHERE r.child_uid = v_cur;
    EXIT WHEN NOT FOUND;
    v_chain := v_chain || v_anc;
    v_cur := v_anc;
  END LOOP;
  v_M := COALESCE(array_length(v_chain, 1), 0);

  IF v_M = 0 THEN
    v_credit := -1;                              -- DL86：无可付祖先 ⇒ 平台收入
  ELSE
    v_credit := -2;                              -- DL86：有可付祖先 ⇒ 佣金池
  END IF;

  -- 最大余数法（仅 fee > 0 且 M > 0 时需要分配）
  IF v_fee > 0 AND v_M > 0 THEN
    FOR i IN 1..v_M LOOP
      v_w := v_w || v_weights[i]::bigint;
      v_wsum := v_wsum + v_weights[i]::bigint;
    END LOOP;
    IF v_wsum <= 0 THEN
      -- §7.3：W = 0 在政策写入时已被 0007 守卫拒（裁定 #16）⇒ 运行时不可达；兜底按 defect 类
      PERFORM public.ledger_raise('LEDGER_FEE_RATE_INVALID',
        jsonb_build_object('reason', 'policy_weights_all_zero', 'levels', v_M, 'job_id', p_job_id::text,
                           'note', 'runtime W=0 branch unreachable under 0007 write-time guard'));
    END IF;
    FOR i IN 1..v_M LOOP
      v_q := v_q || ((v_pool * v_w[i]) / v_wsum);
      v_r := v_r || ((v_pool * v_w[i]) % v_wsum);
      v_sumq := v_sumq + ((v_pool * v_w[i]) / v_wsum);
    END LOOP;
    v_D := v_pool - v_sumq;
    IF v_D < 0 OR v_D > v_M THEN
      PERFORM public.ledger_raise('LEDGER_ACCOUNT_GUARD_VIOLATION',
        jsonb_build_object('reason', 'COMMISSION_SPLIT_SUM_MISMATCH', 'D', v_D::text, 'M', v_M::text));
    END IF;
    v_x := v_q;
    v_order := ARRAY(
      SELECT g.ord FROM generate_series(1, v_M) AS g(ord)
       ORDER BY v_r[g.ord] DESC, g.ord DESC);    -- CR42：余数相同 ⇒ 更深层优先
    FOR i IN 1..v_D::integer LOOP
      v_x[v_order[i]] := v_x[v_order[i]] + 1;
    END LOOP;
    FOR i IN 1..v_M LOOP
      v_sumx := v_sumx + v_x[i];
    END LOOP;
    IF v_sumx <> v_pool THEN
      PERFORM public.ledger_raise('LEDGER_ACCOUNT_GUARD_VIOLATION',
        jsonb_build_object('reason', 'COMMISSION_SPLIT_SUM_MISMATCH',
                           'pool', v_pool::text, 'sum_x', v_sumx::text, 'M', v_M::text));
    END IF;
  END IF;

  -- ---------------------------------------------------------------- 分录（§5.3 顺序铁律）
  v_memo := '招工验收结算 job=' || p_job_id::text;
  v_entries := jsonb_build_array(
    jsonb_build_object('uid', p_employer::text, 'cid', p_cid::text, 'delta', '0',
                       'frozen_delta', (-v_net)::text, 'kind', 'job_payout',
                       'memo', v_memo || '（雇主托管出账）'),
    jsonb_build_object('uid', p_worker::text, 'cid', p_cid::text, 'delta', v_net::text,
                       'frozen_delta', '0', 'kind', 'job_payout',
                       'memo', v_memo || '（打工人到手）'));

  IF v_fee > 0 THEN
    v_entries := v_entries || jsonb_build_array(
      jsonb_build_object('uid', p_employer::text, 'cid', p_cid::text, 'delta', '0',
                         'frozen_delta', (-v_fee)::text, 'kind', 'job_fee',
                         'memo', v_memo || '（手续费）'),
      jsonb_build_object('uid', v_credit::text, 'cid', p_cid::text, 'delta', v_fee::text,
                         'frozen_delta', '0', 'kind', 'job_fee',
                         'memo', v_memo || '（手续费入账）'));
    IF v_M > 0 THEN
      FOR i IN 1..v_M LOOP
        IF v_x[i] > 0 THEN
          v_N := v_N + 1;
          v_layers := v_layers || jsonb_build_array(jsonb_build_object(
            'level', i, 'beneficiary_uid', v_chain[i]::text, 'weight_bp', v_w[i]::text,
            'q', v_q[i]::text, 'r', v_r[i]::text, 'x', v_x[i]::text));
          v_entries := v_entries || jsonb_build_array(
            jsonb_build_object('uid', '-2', 'cid', p_cid::text, 'delta', (-v_x[i])::text,
                               'frozen_delta', '0', 'kind', 'commission',
                               'memo', v_memo || '（佣金 L' || i || '）'),
            jsonb_build_object('uid', v_chain[i]::text, 'cid', p_cid::text, 'delta', v_x[i]::text,
                               'frozen_delta', '0', 'kind', 'commission',
                               'memo', v_memo || '（佣金 L' || i || '）'));
        END IF;
      END LOOP;
    END IF;
  END IF;

  RETURN jsonb_build_object(
    'job_id', p_job_id::text, 'employer_uid', p_employer::text, 'worker_uid', p_worker::text,
    'cid', p_cid::text, 'gross', p_gross::text, 'fee', v_fee::text, 'net', v_net::text,
    'pool', v_pool::text, 'fee_rate_bp', v_bp, 'levels', v_levels, 'M', v_M, 'N', v_N,
    'W', v_wsum::text, 'weights_bp', to_jsonb(v_w), 'fee_credit_uid', v_credit::text,
    'zero_amount', (v_fee = 0), 'no_referrer', (v_M = 0),
    'layers', v_layers, 'entries', v_entries);
END $$;

COMMENT ON FUNCTION public.job_settle_plan(bigint, bigint, bigint, bigint, bigint) IS
  '招工结算分录派生（commission.spec §5.3 顺序铁律 + §6.2 最大余数法；DL86 的 -2/-1 分支）。只读、不写库、不锁账户；金额一律十进制字符串（R70）。';


-- ============================================================================
-- §E 业务编排函数 `public.job_post_event(payload jsonb)`（DL20 提案 A / DL141–DL144）
-- ============================================================================
-- 入参契约（amounts 一律十进制字符串，R70）
--   { "op": "publish" | "refund" | "settle",
--     "request_fingerprint": "<hex>"|null,          -- 路由层强制传（DL96）；本函数透传
--     "memo": "…"?,                                 -- 可选
--     "create_key": "cli:<uuid-v4>",                -- op=publish 必填（创建类键，DL94）
--     "employer_uid": "900001", "cid": "1", "reward": "1000",
--     "title": "…"?, "description": "…"?,
--     "job_id": "123",                              -- op=refund|settle 必填
--     "to_status": "cancelled"|"rejected" }         -- op=refund 必填（cancel / reject）
-- 幂等键**由本函数确定性派生**（DL95：键只能由不可变业务标识派生；调用方不得自造）：
--   publish → `biz:job:escrow:<job_id>`（创建本身用 create_key = `cli:<uuid>`，DL58）
--   refund  → `biz:job:refund:<job_id>`
--   settle  → `biz:job:settle:<job_id>`（逐字对齐 CR57）
-- 出参：{ok, idempotent_replay, op, job_id, status, escrow_txid, settle_txid,
--        ledger_event_keys, txid, created, entries, accounts, extra}
CREATE OR REPLACE FUNCTION public.job_post_event(payload jsonb) RETURNS jsonb
LANGUAGE plpgsql AS $$
DECLARE
  v_op         text;
  v_fp         text;
  v_memo       text;
  v_create_key text;
  v_employer   bigint;
  v_cid        bigint;
  v_reward     bigint;
  v_title      text;
  v_desc       text;
  v_to         text;
  v_job_id     bigint;
  v_job        public.job;
  v_key        text;
  v_entries    jsonb;
  v_plan       jsonb;
  v_replay     boolean := false;
  v_created    boolean := false;
  v_ledger     jsonb;
  v_txid       text;
  v_seen       integer;
  v_bad        text;
  v_cur        record;
BEGIN
  -- ---------------------------------------------------------------- 信封校验
  IF payload IS NULL OR jsonb_typeof(payload) <> 'object' THEN
    PERFORM public.ledger_raise('LEDGER_AMOUNT_INVALID',
      jsonb_build_object('field', 'payload', 'reason', 'BAD_TYPE'));
  END IF;
  v_op := payload->>'op';
  IF v_op IS NULL OR v_op NOT IN ('publish', 'refund', 'settle') THEN
    PERFORM public.ledger_raise('LEDGER_AMOUNT_INVALID',
      jsonb_build_object('field', 'op', 'value', COALESCE(v_op, 'null'), 'reason', 'UNKNOWN_JOB_OP'));
  END IF;
  -- R53 / §19.6：指纹可为 NULL（未传 = 同键即重放）；只作用于事件第 1 条分录
  IF payload ? 'request_fingerprint' AND jsonb_typeof(payload->'request_fingerprint') = 'string' THEN
    v_fp := NULLIF(payload->>'request_fingerprint', '');
  ELSE
    v_fp := NULL;
  END IF;
  v_memo := COALESCE(NULLIF(payload->>'memo', ''), 'job ' || v_op);

  IF v_op = 'publish' THEN
    -- ============================================================ op = publish
    -- ① 创建幂等键闸（DL93 的字符集闸，逐项同序：TOO_LONG → PREFIX_REQUIRED →
    --    RESERVED_SEPARATOR → CONTROL_CHARACTER）
    v_create_key := btrim(COALESCE(payload->>'create_key', ''));
    IF v_create_key = '' OR jsonb_typeof(payload->'create_key') <> 'string' THEN
      PERFORM public.ledger_raise('LEDGER_IDEMPOTENCY_KEY_REQUIRED',
        jsonb_build_object('field', 'create_key'));
    END IF;
    IF length(v_create_key) > 256 THEN
      PERFORM public.ledger_raise('LEDGER_IDEMPOTENCY_KEY_INVALID',
        jsonb_build_object('reason', 'TOO_LONG', 'field', 'create_key'));
    END IF;
    IF v_create_key !~ '^(biz|cm|cli|ops):' THEN
      PERFORM public.ledger_raise('LEDGER_IDEMPOTENCY_KEY_INVALID',
        jsonb_build_object('reason', 'PREFIX_REQUIRED', 'provided', left(v_create_key, 8), 'field', 'create_key'));
    END IF;
    IF position('#' in v_create_key) > 0 THEN
      PERFORM public.ledger_raise('LEDGER_IDEMPOTENCY_KEY_INVALID',
        jsonb_build_object('reason', 'RESERVED_SEPARATOR', 'field', 'create_key'));
    END IF;
    IF v_create_key ~ '[[:cntrl:]]' THEN
      PERFORM public.ledger_raise('LEDGER_IDEMPOTENCY_KEY_INVALID',
        jsonb_build_object('reason', 'CONTROL_CHARACTER', 'field', 'create_key'));
    END IF;
    -- 入参解析（R100：body 侧 uid 必须 > 0；平台保留区间一律拒）
    v_employer := public.ledger_uid_arg(COALESCE(payload->>'employer_uid', ''), 'employer_uid');
    IF v_employer < 1 THEN
      PERFORM public.ledger_raise('LEDGER_RESERVED_UID',
        jsonb_build_object('uid', v_employer::text, 'field', 'employer_uid',
                           'reason', 'PLATFORM_EMPLOYER_FORBIDDEN'));
    END IF;
    v_cid    := public.ledger_cid_arg(COALESCE(payload->>'cid', ''));
    v_reward := public.ledger_int_amount(COALESCE(payload->>'reward', ''), 'reward');
    IF v_reward <= 0 THEN
      PERFORM public.ledger_raise('LEDGER_AMOUNT_NOT_POSITIVE',
        jsonb_build_object('field', 'reward', 'value', v_reward::text));
    END IF;
    IF v_reward > public.ledger_max_single_amount() THEN
      PERFORM public.ledger_raise('LEDGER_AMOUNT_INVALID',
        jsonb_build_object('field', 'reward', 'reason', 'OVER_MAX_SINGLE_AMOUNT', 'value', left(v_reward::text, 40)));
    END IF;
    v_title := COALESCE(payload->>'title', '');
    v_desc  := COALESCE(payload->>'description', '');
    IF length(v_title) > 200 THEN
      PERFORM public.ledger_raise('LEDGER_AMOUNT_INVALID',
        jsonb_build_object('field', 'title', 'reason', 'TOO_LONG', 'limit', 200));
    END IF;

    -- ② 业务行锁（DL141：业务行先于 currency/account）。create_key 是创建幂等的唯一权威
    SELECT * INTO v_job FROM public.job j WHERE j.create_key = v_create_key FOR UPDATE;
    IF FOUND THEN
      v_replay := true;
      -- 同键异业务内容 ⇒ 409（DL144② 的业务侧对应物；有指纹时账本侧另有一道闸）
      IF v_job.employer_uid <> v_employer OR v_job.cid <> v_cid OR v_job.reward <> v_reward THEN
        PERFORM public.ledger_raise('LEDGER_IDEMPOTENCY_CONFLICT',
          jsonb_build_object('reason', 'CREATE_KEY_REUSED_WITH_DIFFERENT_CONTENT',
                             'field', 'create_key', 'idempotency_key', v_create_key,
                             'job_id', v_job.job_id::text));
      END IF;
    ELSE
      INSERT INTO public.job (employer_uid, cid, reward, title, description, status, create_key)
      VALUES (v_employer, v_cid, v_reward, v_title, v_desc, 'open', v_create_key)
      ON CONFLICT (create_key) DO NOTHING
      RETURNING * INTO v_job;
      IF NOT FOUND THEN
        -- 并发同键：另一事务已建行 ⇒ 重读（持行锁），按重放返回，不重写业务行
        SELECT * INTO v_job FROM public.job j WHERE j.create_key = v_create_key FOR UPDATE;
        IF NOT FOUND THEN
          PERFORM public.ledger_raise('LEDGER_REF_NOT_FOUND',
            jsonb_build_object('field', 'create_key', 'reason', 'job_create_race_lost',
                               'idempotency_key', v_create_key));
        END IF;
        v_replay := true;
      ELSE
        v_created := true;
      END IF;
    END IF;

    v_job_id := v_job.job_id;
    v_key    := 'biz:job:escrow:' || v_job_id::text;

    -- R28：招工酬金计价仅 `listed`（只在**发布托管**路径上校验；退款/结算不受币种状态影响）
    SELECT c.cid, c.status INTO v_cur FROM public.currency c WHERE c.cid = v_job.cid;
    IF NOT FOUND THEN
      PERFORM public.ledger_raise('LEDGER_CURRENCY_NOT_FOUND', jsonb_build_object('cid', v_job.cid::text));
    END IF;
    IF v_cur.status <> 'listed' THEN
      PERFORM public.ledger_raise('LEDGER_CURRENCY_NOT_LISTED',
        jsonb_build_object('cid', v_job.cid::text, 'symbol', NULL, 'reason', 'job_reward_currency_not_listed', 'status', v_cur.status));
    END IF;

    -- ③ 派生分录（§7.1：`job_escrow` ×2，雇主 balance −n / 雇主 frozen +n；DL90 例外）
    v_entries := jsonb_build_array(
      jsonb_build_object('uid', v_job.employer_uid::text, 'cid', v_job.cid::text, 'delta', (-v_job.reward)::text,
                         'frozen_delta', '0', 'kind', 'job_escrow',
                         'memo', '招工发布托管 job=' || v_job_id::text || '（雇主余额出账）'),
      jsonb_build_object('uid', v_job.employer_uid::text, 'cid', v_job.cid::text, 'delta', '0',
                         'frozen_delta', v_job.reward::text, 'kind', 'job_escrow',
                         'memo', '招工发布托管 job=' || v_job_id::text || '（入冻结）'));

  ELSE
    -- ============================================================ op = refund | settle
    v_job_id := public.ledger_int_amount(COALESCE(payload->>'job_id', ''), 'job_id');
    IF v_job_id < 1 THEN
      PERFORM public.ledger_raise('LEDGER_REF_NOT_FOUND',
        jsonb_build_object('field', 'job_id', 'value', v_job_id::text, 'reason', 'job_not_found'));
    END IF;
    IF v_op = 'refund' THEN
      v_to := COALESCE(NULLIF(payload->>'to_status', ''), 'cancelled');
      IF v_to NOT IN ('cancelled', 'rejected') THEN
        PERFORM public.ledger_raise('LEDGER_AMOUNT_INVALID',
          jsonb_build_object('field', 'to_status', 'value', v_to, 'reason', 'not_a_refund_target'));
      END IF;
      v_key := 'biz:job:refund:' || v_job_id::text;
    ELSE
      v_to  := 'settled';
      v_key := 'biz:job:settle:' || v_job_id::text;
    END IF;

    -- ① 业务行锁（DL141 全序第 1 段；单行按主键）
    SELECT * INTO v_job FROM public.job j WHERE j.job_id = v_job_id FOR UPDATE;
    IF NOT FOUND THEN
      PERFORM public.ledger_raise('LEDGER_REF_NOT_FOUND',
        jsonb_build_object('field', 'job_id', 'value', v_job_id::text, 'reason', 'job_not_found'));
    END IF;

    -- ② 重放探测（**只读**，按事件根键走已有索引 idx_ledger_event_root_key）
    --    与 0012 的重放前置闸同法：它只决定「是否还走业务状态机校验」，不取代账本的权威幂等探针。
    SELECT 1 INTO v_seen FROM public.ledger_entry e WHERE e.event_root_key = v_key LIMIT 1;
    v_replay := FOUND;

    -- ③ 状态机闸（DL51/DL52；**仅非重放**：重放时业务行已在终态，不得第二次校验/重写）
    IF NOT v_replay THEN
      IF NOT public.job_status_transition_ok(v_job.status, v_to) THEN
        PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
          jsonb_build_object('field', 'job.status', 'reason', 'JOB_STATE_INVALID',
                             'from', v_job.status, 'to', v_to, 'job_id', v_job_id::text));
      END IF;
    END IF;

    -- ④ 派生分录
    IF v_op = 'refund' THEN
      IF v_job.escrow_txid IS NULL THEN
        -- 未托管 ⇒ 无可退（结构性判据；防「凭空退款」）
        PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
          jsonb_build_object('field', 'job.escrow_txid', 'reason', 'job_escrow_missing',
                             'job_id', v_job_id::text, 'status', v_job.status));
      END IF;
      v_entries := jsonb_build_array(
        jsonb_build_object('uid', v_job.employer_uid::text, 'cid', v_job.cid::text, 'delta', v_job.reward::text,
                           'frozen_delta', '0', 'kind', 'job_escrow_refund',
                           'memo', '招工托管退回 job=' || v_job_id::text || '（出冻结）'),
        jsonb_build_object('uid', v_job.employer_uid::text, 'cid', v_job.cid::text, 'delta', '0',
                           'frozen_delta', (-v_job.reward)::text, 'kind', 'job_escrow_refund',
                           'memo', '招工托管退回 job=' || v_job_id::text || '（回余额）'));
    ELSE
      v_plan    := public.job_settle_plan(v_job.job_id, v_job.employer_uid, v_job.worker_uid, v_job.cid, v_job.reward);
      v_entries := v_plan->'entries';
    END IF;
  END IF;

  -- ---------------------------------------------------------------- DL84 事件级 kind 白名单
  FOR v_cur IN SELECT t.e->>'kind' AS k FROM jsonb_array_elements(v_entries) AS t(e) LOOP
    IF (v_op = 'publish' AND v_cur.k <> 'job_escrow')
       OR (v_op = 'refund' AND v_cur.k <> 'job_escrow_refund')
       OR (v_op = 'settle' AND v_cur.k NOT IN ('job_payout', 'job_fee', 'commission')) THEN
      PERFORM public.ledger_raise('LEDGER_ACCOUNT_GUARD_VIOLATION',
        jsonb_build_object('reason', 'JOB_EVENT_KIND_OUT_OF_WHITELIST', 'op', v_op, 'kind', v_cur.k));
    END IF;
  END LOOP;

  -- ---------------------------------------------------------------- DL141/DL143：调既有账本函数
  -- 锁序：业务行（上方已 `FOR UPDATE`）→ currency（cid 升序）→ account（uid 升序）—— 由
  -- `ledger_post_event` 在其内部完成第二、三段；本函数**绝不**先锁 account（否则 AB-BA 死锁）。
  v_ledger := public.ledger_post_event(jsonb_build_object(
    'op',                  'entries',
    'idempotency_key',     v_key,
    'request_fingerprint', v_fp,
    'memo',                v_memo,
    'ref_type',            'job',
    'ref_id',              v_job_id::text,
    'entries',             v_entries));
  v_txid := v_ledger->>'txid';
  IF (v_ledger->>'idempotent_replay')::boolean THEN
    v_replay := true;
  END IF;

  -- ---------------------------------------------------------------- 回写业务行
  -- DL144①：重放 ⇒ **不重写业务行**、**不追加 `ledger_event_keys` 项**（DL149 判负用例钉住）；
  -- 判据是账本侧的 `idempotent_replay`（+ 只读根键探测），**不是** `UPDATE ... RETURNING` 的行数。
  IF NOT v_replay THEN
    IF v_op = 'publish' THEN
      UPDATE public.job j
         SET escrow_txid = v_txid::bigint,
             ledger_event_keys = j.ledger_event_keys || v_key
       WHERE j.job_id = v_job_id
      RETURNING * INTO v_job;
    ELSIF v_op = 'refund' THEN
      UPDATE public.job j
         SET status = v_to,
             ledger_event_keys = j.ledger_event_keys || v_key
       WHERE j.job_id = v_job_id
      RETURNING * INTO v_job;
    ELSE
      UPDATE public.job j
         SET status = 'settled',
             settle_txid = v_txid::bigint,
             ledger_event_keys = j.ledger_event_keys || v_key
       WHERE j.job_id = v_job_id
      RETURNING * INTO v_job;
    END IF;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'idempotent_replay', v_replay,
    'op', v_op,
    'job_id', v_job_id::text,
    'created', v_created,
    'status', v_job.status,
    'escrow_txid', CASE WHEN v_job.escrow_txid IS NULL THEN NULL ELSE v_job.escrow_txid::text END,
    'settle_txid', CASE WHEN v_job.settle_txid IS NULL THEN NULL ELSE v_job.settle_txid::text END,
    'ledger_event_keys', to_jsonb(v_job.ledger_event_keys),
    'txid', v_txid,
    'ledger_idempotency_key', v_key,
    'entries', v_ledger->'entries',
    'accounts', v_ledger->'accounts',
    'extra', jsonb_build_object('job_op', v_op, 'fee_credit_uid',
                                CASE WHEN v_plan IS NULL THEN NULL ELSE v_plan->>'fee_credit_uid' END));
END $$;

COMMENT ON FUNCTION public.job_post_event(jsonb) IS
  'P3 招工业务编排函数（DL20 提案 A；硬约束 DL141–DL144）。op=publish|refund|settle；幂等键由本函数按 §8 确定性派生（cli: 创建 / biz: 业务）；同一语句内完成「锁业务行 → 派生分录 → 调 ledger_post_event($1::jsonb) → 回写 ledger_event_keys/引用列」；函数体内无任何 DDL（DL142）；同键重放不重写业务行、不追加 ledger_event_keys 项（DL144①/DL149）。';


-- ============================================================================
-- §F apply-time 自检（DL48：不通过则整迁移回滚、不写版本行）
-- ============================================================================
DO $$
DECLARE
  v_missing text;
  v_cols    int;
  v_idx     int;
  v_plan    jsonb;
  v_bal     numeric;
  v_kinds   text;
  v_bad     int;
BEGIN
  -- ---------------------------------------------------------------- 结构断言
  IF to_regclass('public.job') IS NULL THEN
    RAISE EXCEPTION '0013 self-check FAILED: public.job missing';
  END IF;

  SELECT count(*) INTO v_cols
    FROM information_schema.columns c
   WHERE c.table_schema = 'public' AND c.table_name = 'job';
  IF v_cols <> 14 THEN
    RAISE EXCEPTION '0013 self-check FAILED: public.job has % columns, expected 14 (DL50)', v_cols;
  END IF;

  SELECT string_agg(x.n, ',' ORDER BY x.n) INTO v_missing
    FROM (VALUES ('job_id'),('employer_uid'),('worker_uid'),('cid'),('reward'),('title'),('description'),
                 ('status'),('create_key'),('escrow_txid'),('settle_txid'),('ledger_event_keys'),
                 ('time_created'),('time_updated')) AS x(n)
   WHERE NOT EXISTS (SELECT 1 FROM information_schema.columns c
                      WHERE c.table_schema='public' AND c.table_name='job' AND c.column_name = x.n);
  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION '0013 self-check FAILED: public.job missing columns: %', v_missing;
  END IF;

  SELECT count(*) INTO v_idx
    FROM pg_indexes i
   WHERE i.schemaname='public' AND i.tablename='job'
     AND i.indexname IN ('idx_job_status_time','idx_job_employer','idx_job_worker');
  IF v_idx <> 3 THEN
    RAISE EXCEPTION '0013 self-check FAILED: expected 3 job indexes (DL53), found %', v_idx;
  END IF;

  IF to_regprocedure('public.job_post_event(jsonb)') IS NULL
     OR to_regprocedure('public.job_settle_plan(bigint,bigint,bigint,bigint,bigint)') IS NULL
     OR to_regprocedure('public.job_status_transition_ok(text,text)') IS NULL THEN
    RAISE EXCEPTION '0013 self-check FAILED: orchestration/derivation functions missing';
  END IF;

  -- DL142：编排函数体内禁 DDL（实例级 + 类级双查；类级由 p3s1b-01 覆盖全树）
  --   注：匿名块的探测串必须用 chr(36) 拼出 —— 本块自身是 dollar-quoted body，
  --   体内出现字面量 dollar-quote 标记会**提前闭合**该 body（实测：42601 syntax error）。
  SELECT string_agg(t.p, ',') INTO v_missing FROM (
    VALUES ('create table'),('alter table'),('drop table'),('truncate'),('create index'),
           ('create function'),('rename to'),('do ' || chr(36) || chr(36))
  ) AS t(p)
   WHERE position(upper(t.p) in upper(pg_get_functiondef('public.job_post_event(jsonb)'::regprocedure))) > 0;
  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION '0013 self-check FAILED: DDL token(s) inside job_post_event body: %', v_missing;
  END IF;

  -- ---------------------------------------------------------------- 纯函数断言（状态机白名单）
  IF NOT public.job_status_transition_ok('open','accepted')
     OR NOT public.job_status_transition_ok('open','cancelled')
     OR NOT public.job_status_transition_ok('accepted','submitted')
     OR NOT public.job_status_transition_ok('accepted','rejected')
     OR NOT public.job_status_transition_ok('submitted','settled')
     OR NOT public.job_status_transition_ok('submitted','rejected')
     OR NOT public.job_status_transition_ok('submitted','disputed')
     OR NOT public.job_status_transition_ok('disputed','settled')
     OR NOT public.job_status_transition_ok('disputed','cancelled') THEN
    RAISE EXCEPTION '0013 self-check FAILED: whitelist missing an allowed transition (DL51)';
  END IF;
  IF public.job_status_transition_ok('open','settled')
     OR public.job_status_transition_ok('open','submitted')
     OR public.job_status_transition_ok('accepted','settled')
     OR public.job_status_transition_ok('settled','open')
     OR public.job_status_transition_ok('cancelled','open')
     OR public.job_status_transition_ok('rejected','submitted')
     OR public.job_status_transition_ok('settled','cancelled') THEN
    RAISE EXCEPTION '0013 self-check FAILED: whitelist admits a forbidden transition (DL51)';
  END IF;

  -- ---------------------------------------------------------------- 结算派生守恒（只读、无副作用的纯派生）
  v_plan := public.job_settle_plan(0::bigint, 900000::bigint, 900001::bigint, 1::bigint, 10000::bigint);
  v_bal := 0;
  SELECT COALESCE(sum((t.e->>'delta')::numeric + (t.e->>'frozen_delta')::numeric), 0) INTO v_bal
    FROM jsonb_array_elements(v_plan->'entries') AS t(e);
  IF v_bal <> 0 THEN
    RAISE EXCEPTION '0013 self-check FAILED: settle entries not balanced (sum=%)', v_bal;
  END IF;
  IF (v_plan->>'fee')::numeric + (v_plan->>'net')::numeric <> (v_plan->>'gross')::numeric THEN
    RAISE EXCEPTION '0013 self-check FAILED: net + fee <> gross (CR39)';
  END IF;
  SELECT string_agg(DISTINCT t.e->>'kind', ',' ORDER BY t.e->>'kind') INTO v_kinds
    FROM jsonb_array_elements(v_plan->'entries') AS t(e);
  SELECT count(*) INTO v_bad
    FROM jsonb_array_elements(v_plan->'entries') AS t(e)
   WHERE t.e->>'kind' NOT IN ('job_payout', 'job_fee', 'commission');
  IF COALESCE(v_bad, 0) <> 0 THEN
    RAISE EXCEPTION '0013 self-check FAILED: settle event kind whitelist violated: % (kinds=%)', v_bad, v_kinds;
  END IF;

  RAISE NOTICE '0013 self-check OK: job columns=%, indexes=%, settle fee=% net=% M=% fee_credit_uid=% kinds=%',
    v_cols, v_idx, v_plan->>'fee', v_plan->>'net', v_plan->>'M', v_plan->>'fee_credit_uid', v_kinds;
END $$;

