-- ============================================================================
-- 0014_job_flow.sql · P3 第一柱（招工）第二片 · `job_application` + `job_submission` + 守卫
-- ============================================================================
-- 权威口径：docs/data-layer.spec.md **v0.4**（现盘）
--   §6.1  `0014` = `job_application` / `job_submission` + 其守卫（DL54–DL56）
--   §6.2  job_application 列契约（DL54）· 其守卫 + 部分唯一索引（DL55）
--         job_submission 列契约与列级不可变守卫（DL56）
--   DL46  一迁一主题（本迁只做招工第二、三表 + 其守卫/索引）
--   DL47  编号顺序 = 应用顺序（`0013` 已应用 ⇒ 本迁 = `0014`；不得再动编号）
--   DL48  每迁移自带幂等 + apply-time 自检（不通过 ⇒ 整迁移回滚、不写版本行）
--   DL7   schema 只由迁移变更；`0001`–`0013` 不得改动（checksum 冻结）
--   DL75③ time_updated 由 BEFORE UPDATE 触发器统一刷新（仅 job_application；DL56 的
--         job_submission **无** time_updated 列，口径逐列照 spec）
--   DL76  可变表用「状态机守卫触发器」，**禁**全表 append-only 触发器
--         （job_application / job_submission 均为**可变**表）
--   DL78  新表 uid 列一律 FK public.users(uid)
--   DL79  DELETE 一律不出现在业务表（终结 = 状态位）
--   DL80  snake_case / 无引号 / 非保留字
--   DL99  **不得为「无分录的写」造账本事件占位** ⇒ `apply` / `accept` / `submit`
--         属无分录动作，两表**不建** `ledger_event_keys` 列、**不建**编排函数
--         （带分录的 publish/refund/settle 已在 `0013` 的 `public.job_post_event` 内）
--   DL151 新数据层所有 SQL 显式限定 `public.`（`neon_auth.account` 同名陷阱）
--   §11.2 状态类错误借码（C5 已裁）：`LEDGER_CURRENCY_INVALID_TRANSITION`（integrity ⇒ 409）
--   已知债 DL148：借币种状态机码（与 `0013` 同源张力，已登记台账）
--
-- 本迁移做什么
--   ① `public.job_application`：逐列照 DL54（**不增删列**）+ 状态 CHECK + FK
--      + `UNIQUE (job_id, worker_uid)`（DL54）+ 状态机守卫（DL55）
--   ② `public.job_application` 的**部分唯一索引** `UNIQUE (job_id) WHERE status='accepted'`
--      （DL55：同一 job 最多一条 accepted；结构性可判负）
--   ③ `public.job_submission`：逐列照 DL56（**不增删列**）+ review_status CHECK + FK
--      + 列级不可变守卫（deliverable/job_id/worker_uid/create_key 永不可改；review_* 一次写定）
--   ④ `public.job_application_status_transition_ok(from,to)`：应用状态白名单唯一真源（DL55）
--   ⑤ 两表各建索引（按读口清单，DL74 精神：受控、说明为何现有索引不覆盖）
--   ⑥ 触发器：状态机守卫 / time_updated 刷新 / 禁 DELETE（DL76/DL79/DL75③）
--
-- 本迁移**不**做什么（硬边界）
--   · **不改 `0001`–`0013` 的任何字节**（checksum 冻结；`migrate.ts` 会整链 ABORT/exit 3）
--   · **不建编排函数**（DL99：apply/accept/submit 无分录；带分录动作已在 `0013`）
--   · **不建** `ledger_event_keys` 列（DL99：无分录的写不得借账本幂等）
--   · 不动既有 9 张基表的**数据**或结构（本迁只**增**表/索引/触发器）
--   · 不新增 `kind`（DL81：0 个扩展）、不新增错误码（DL119：一律映射既有 33 码）
--   · 不接路由（`src/` 本单不改）
--
-- 幂等（DL48）：`CREATE TABLE IF NOT EXISTS` / `CREATE INDEX IF NOT EXISTS` /
--   `CREATE UNIQUE INDEX IF NOT EXISTS` / `CREATE OR REPLACE FUNCTION` /
--   `DROP TRIGGER IF EXISTS` + `CREATE TRIGGER`；末尾 apply-time `DO` 自检
--   （结构 + 纯函数白名单正/负全集 + 触发器启用态 + 函数体内无 DDL）；
--   任一失败 ⇒ 整迁移回滚、不写版本行。
--
-- 诚实边界（不得夸大）
--   · 「列级不可变 / 一次写定 / 最多一条 accepted」都是**防应用层事故的护栏**：
--     `TRUNCATE` 不触发行触发器，超管 `ALTER TABLE ... DISABLE TRIGGER USER` 可旁路
--     ⇒ 不得表述为「绝对不可变」。
--   · 部分唯一索引是**结构性**保证（并发 accept 由索引挡），但**不拦**「先 DROP INDEX
--     再写」的超级用户路径 —— 本片判负自证正是用这一条把尺子撞响（见 p3f-02）。
-- ============================================================================


-- ============================================================================
-- §A 应用状态白名单（DL55）—— 唯一真源，供触发器与自检共用
-- ============================================================================
CREATE OR REPLACE FUNCTION public.job_application_status_transition_ok(p_from text, p_to text)
RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE p_from
    WHEN 'applied' THEN p_to IN ('accepted', 'rejected', 'withdrawn')
    ELSE false            -- accepted / rejected / withdrawn = 无出边（终态）
  END
$$;

COMMENT ON FUNCTION public.job_application_status_transition_ok(text, text) IS
  'DL55 应用状态白名单唯一真源：applied→{accepted,rejected,withdrawn}；accepted/rejected/withdrawn 无出边（终态）。';


-- ============================================================================
-- §B `public.job_application` 表（逐列照 §6.2 / DL54）
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.job_application (
  application_id bigint      GENERATED BY DEFAULT AS IDENTITY,
  job_id         bigint      NOT NULL,
  worker_uid     bigint      NOT NULL,
  status         text        NOT NULL DEFAULT 'applied',
  create_key     text        NOT NULL,
  time_created   timestamptz NOT NULL DEFAULT now(),
  time_updated   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT job_application_pk              PRIMARY KEY (application_id),
  -- DL75① / DL54：创建幂等键
  CONSTRAINT job_application_create_key_uniq UNIQUE (create_key),
  -- DL54：一人一单只有一条申请
  CONSTRAINT job_application_job_worker_uniq UNIQUE (job_id, worker_uid),
  -- DL54 / DL55 状态白名单（applied / withdrawn / rejected / accepted）
  CONSTRAINT job_application_status_enum     CHECK (status IN ('applied','withdrawn','rejected','accepted')),
  CONSTRAINT job_application_job_fk          FOREIGN KEY (job_id)     REFERENCES public.job(job_id),
  CONSTRAINT job_application_worker_fk       FOREIGN KEY (worker_uid) REFERENCES public.users(uid)
);

COMMENT ON TABLE public.job_application IS
  'P3 招工第二表（data-layer.spec v0.4 §6.2 / DL54）：报名。无分录动作（DL99）⇒ 无 ledger_event_keys 列；幂等靠 create_key 与 UNIQUE(job_id,worker_uid)。';

-- DL55：同一 job 最多一条 accepted（部分唯一索引；结构性保证并发「同时被选定」不可发生）
CREATE UNIQUE INDEX IF NOT EXISTS uniq_job_application_accepted
  ON public.job_application (job_id)
  WHERE status = 'accepted';

-- 索引（DL74 受控）：`(job_id, worker_uid)` 唯一约束自带索引已覆盖 job_id 前缀读
-- ⇒ 不另建 `(job_id)`；只补「我的报名」读口（worker_uid 轴）。
CREATE INDEX IF NOT EXISTS idx_job_application_worker
  ON public.job_application (worker_uid, time_created DESC);


-- ============================================================================
-- §C `public.job_submission` 表（逐列照 §6.2 / DL56）
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.job_submission (
  submission_id bigint      GENERATED BY DEFAULT AS IDENTITY,
  job_id        bigint      NOT NULL,
  worker_uid    bigint      NOT NULL,
  deliverable   text        NOT NULL,
  review_status text        NOT NULL DEFAULT 'pending',
  reviewed_by   bigint,
  reviewed_at   timestamptz,
  review_memo   text        NOT NULL DEFAULT '',
  create_key    text        NOT NULL,
  time_created  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT job_submission_pk              PRIMARY KEY (submission_id),
  CONSTRAINT job_submission_create_key_uniq UNIQUE (create_key),
  -- DL56：审核结论白名单（pending / approved / rejected）
  CONSTRAINT job_submission_review_status_enum CHECK (review_status IN ('pending','approved','rejected')),
  CONSTRAINT job_submission_job_fk          FOREIGN KEY (job_id)      REFERENCES public.job(job_id),
  CONSTRAINT job_submission_worker_fk       FOREIGN KEY (worker_uid)  REFERENCES public.users(uid),
  CONSTRAINT job_submission_reviewed_by_fk  FOREIGN KEY (reviewed_by) REFERENCES public.users(uid)
);

COMMENT ON TABLE public.job_submission IS
  'P3 招工第三表（data-layer.spec v0.4 §6.2 / DL56）：提交/审核。无分录动作（DL99）⇒ 无 ledger_event_keys 列、无 time_updated 列（逐列照 DL56）；审核结论一次写定（列级不可变守卫）。';

-- 索引（DL74 受控）：job 读口 + worker 读口 + 待审核读口（§3.2 #51 雇主视角 review_status='pending'）
CREATE INDEX IF NOT EXISTS idx_job_submission_job
  ON public.job_submission (job_id, time_created DESC);
CREATE INDEX IF NOT EXISTS idx_job_submission_worker
  ON public.job_submission (worker_uid, time_created DESC);
CREATE INDEX IF NOT EXISTS idx_job_submission_review
  ON public.job_submission (review_status, time_created DESC);


-- ============================================================================
-- §D 守卫触发器（DL55 状态机 + DL76 可变表 + DL79 禁 DELETE + DL75③ 时间戳）
-- ============================================================================

-- D1 job_application 状态转移白名单（DL55）
CREATE OR REPLACE FUNCTION public.job_application_status_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF NOT public.job_application_status_transition_ok(OLD.status, NEW.status) THEN
      PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
        jsonb_build_object('field', 'job_application.status', 'reason', 'JOB_APPLICATION_STATE_INVALID',
                           'from', OLD.status, 'to', NEW.status,
                           'application_id', OLD.application_id::text));
    END IF;
  END IF;
  RETURN NEW;
END $$;

COMMENT ON FUNCTION public.job_application_status_guard() IS
  'DL55：应用状态白名单（唯一真源 = public.job_application_status_transition_ok）。违反 ⇒ 借码 LD011 LEDGER_CURRENCY_INVALID_TRANSITION（integrity ⇒ 409）+ reason=JOB_APPLICATION_STATE_INVALID。';

-- D2 job_application 创建键一次写定（DL75① 指纹一致 ⇒ 不可变）
CREATE OR REPLACE FUNCTION public.job_application_create_key_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.create_key IS DISTINCT FROM OLD.create_key THEN
    PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
      jsonb_build_object('field', 'job_application.create_key', 'reason', 'job_application_create_key_immutable',
                         'application_id', OLD.application_id::text));
  END IF;
  RETURN NEW;
END $$;

COMMENT ON FUNCTION public.job_application_create_key_guard() IS
  'DL75①：job_application.create_key 永不可改（幂等键指纹稳定）。';

-- D3 job_application time_updated 统一刷新（DL75③ / R5）
CREATE OR REPLACE FUNCTION public.job_application_touch_time_updated() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.time_updated := now();
  RETURN NEW;
END $$;

COMMENT ON FUNCTION public.job_application_touch_time_updated() IS
  'DL75③ / R5：job_application.time_updated 由 BEFORE UPDATE 触发器统一刷新，不接受客户端传时间。';

-- D4 job_application 禁 DELETE（DL79）
CREATE OR REPLACE FUNCTION public.job_application_no_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
    jsonb_build_object('field', 'job_application', 'reason', 'job_application_delete_forbidden',
                       'application_id', OLD.application_id::text));
END $$;

COMMENT ON FUNCTION public.job_application_no_delete() IS
  'DL79：业务表禁物理删除（终结 = status 位）。触发器执行序按名字母序：create_key → status → time_updated。';

-- D5 job_submission 列级不可变守卫（DL56）
--   ① deliverable / job_id / worker_uid / create_key 永不可改；
--   ② review_status 只允许 pending → {approved, rejected}；
--   ③ 结论落定（review_status <> 'pending'）后 review_* 四列冻结；
--   ④ reviewed_by / reviewed_at / review_memo 各自一次写定（已非空/非 NULL 后不可改）。
CREATE OR REPLACE FUNCTION public.job_submission_immutable_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.job_id      IS DISTINCT FROM OLD.job_id
     OR NEW.worker_uid IS DISTINCT FROM OLD.worker_uid
     OR NEW.deliverable IS DISTINCT FROM OLD.deliverable
     OR NEW.create_key  IS DISTINCT FROM OLD.create_key THEN
    PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
      jsonb_build_object('field', 'job_submission.immutable', 'reason', 'job_submission_core_immutable',
                         'submission_id', OLD.submission_id::text));
  END IF;

  IF NEW.review_status IS DISTINCT FROM OLD.review_status THEN
    IF NOT (OLD.review_status = 'pending' AND NEW.review_status IN ('approved', 'rejected')) THEN
      PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
        jsonb_build_object('field', 'job_submission.review_status', 'reason', 'job_review_status_invalid',
                           'from', OLD.review_status, 'to', NEW.review_status,
                           'submission_id', OLD.submission_id::text));
    END IF;
  END IF;

  -- ③ 结论落定后 review_* 冻结
  IF OLD.review_status <> 'pending'
     AND (NEW.review_status IS DISTINCT FROM OLD.review_status
          OR NEW.reviewed_by  IS DISTINCT FROM OLD.reviewed_by
          OR NEW.reviewed_at  IS DISTINCT FROM OLD.reviewed_at
          OR NEW.review_memo  IS DISTINCT FROM OLD.review_memo) THEN
    PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
      jsonb_build_object('field', 'job_submission.review', 'reason', 'job_review_immutable',
                         'review_status', OLD.review_status, 'submission_id', OLD.submission_id::text));
  END IF;

  -- ④ 三列各自一次写定
  IF (OLD.reviewed_by IS NOT NULL AND NEW.reviewed_by IS DISTINCT FROM OLD.reviewed_by)
     OR (OLD.reviewed_at IS NOT NULL AND NEW.reviewed_at IS DISTINCT FROM OLD.reviewed_at)
     OR (OLD.review_memo <> '' AND NEW.review_memo IS DISTINCT FROM OLD.review_memo) THEN
    PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
      jsonb_build_object('field', 'job_submission.review_cols', 'reason', 'job_review_col_once_only',
                         'submission_id', OLD.submission_id::text));
  END IF;
  RETURN NEW;
END $$;

COMMENT ON FUNCTION public.job_submission_immutable_guard() IS
  'DL56：列级不可变守卫（deliverable/job_id/worker_uid/create_key 永不可改；review_* 只允许从 NULL/pending 一次写定，之后冻结）。护栏强度=行触发器；不拦 TRUNCATE / DISABLE TRIGGER USER。';

-- D6 job_submission 禁 DELETE（DL79）
CREATE OR REPLACE FUNCTION public.job_submission_no_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  PERFORM public.ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION',
    jsonb_build_object('field', 'job_submission', 'reason', 'job_submission_delete_forbidden',
                       'submission_id', OLD.submission_id::text));
END $$;

COMMENT ON FUNCTION public.job_submission_no_delete() IS
  'DL79：业务表禁物理删除（终结 = review_status 位）。';

DROP TRIGGER IF EXISTS trg_job_application_create_key_guard ON public.job_application;
CREATE TRIGGER trg_job_application_create_key_guard
  BEFORE UPDATE ON public.job_application
  FOR EACH ROW EXECUTE FUNCTION public.job_application_create_key_guard();

DROP TRIGGER IF EXISTS trg_job_application_status_guard ON public.job_application;
CREATE TRIGGER trg_job_application_status_guard
  BEFORE UPDATE ON public.job_application
  FOR EACH ROW EXECUTE FUNCTION public.job_application_status_guard();

DROP TRIGGER IF EXISTS trg_job_application_touch_time_updated ON public.job_application;
CREATE TRIGGER trg_job_application_touch_time_updated
  BEFORE UPDATE ON public.job_application
  FOR EACH ROW EXECUTE FUNCTION public.job_application_touch_time_updated();

DROP TRIGGER IF EXISTS trg_job_application_no_delete ON public.job_application;
CREATE TRIGGER trg_job_application_no_delete
  BEFORE DELETE ON public.job_application
  FOR EACH ROW EXECUTE FUNCTION public.job_application_no_delete();

DROP TRIGGER IF EXISTS trg_job_submission_immutable_guard ON public.job_submission;
CREATE TRIGGER trg_job_submission_immutable_guard
  BEFORE UPDATE ON public.job_submission
  FOR EACH ROW EXECUTE FUNCTION public.job_submission_immutable_guard();

DROP TRIGGER IF EXISTS trg_job_submission_no_delete ON public.job_submission;
CREATE TRIGGER trg_job_submission_no_delete
  BEFORE DELETE ON public.job_submission
  FOR EACH ROW EXECUTE FUNCTION public.job_submission_no_delete();


-- ============================================================================
-- §E apply-time 自检（DL48：不通过则整迁移回滚、不写版本行）
-- ============================================================================
DO $$
DECLARE
  v_missing  text;
  v_cols     int;
  v_idx      int;
  v_trg      int;
  v_def      text;
BEGIN
  -- ---------------------------------------------------------------- 结构断言
  IF to_regclass('public.job_application') IS NULL OR to_regclass('public.job_submission') IS NULL THEN
    RAISE EXCEPTION '0014 self-check FAILED: job_application / job_submission missing';
  END IF;

  SELECT count(*) INTO v_cols
    FROM information_schema.columns c
   WHERE c.table_schema = 'public' AND c.table_name = 'job_application';
  IF v_cols <> 7 THEN
    RAISE EXCEPTION '0014 self-check FAILED: public.job_application has % columns, expected 7 (DL54)', v_cols;
  END IF;

  SELECT string_agg(x.n, ',' ORDER BY x.n) INTO v_missing
    FROM (VALUES ('application_id'),('job_id'),('worker_uid'),('status'),
                 ('create_key'),('time_created'),('time_updated')) AS x(n)
   WHERE NOT EXISTS (SELECT 1 FROM information_schema.columns c
                      WHERE c.table_schema='public' AND c.table_name='job_application' AND c.column_name = x.n);
  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION '0014 self-check FAILED: job_application missing columns: %', v_missing;
  END IF;

  SELECT count(*) INTO v_cols
    FROM information_schema.columns c
   WHERE c.table_schema = 'public' AND c.table_name = 'job_submission';
  IF v_cols <> 10 THEN
    RAISE EXCEPTION '0014 self-check FAILED: public.job_submission has % columns, expected 10 (DL56)', v_cols;
  END IF;

  SELECT string_agg(x.n, ',' ORDER BY x.n) INTO v_missing
    FROM (VALUES ('submission_id'),('job_id'),('worker_uid'),('deliverable'),('review_status'),
                 ('reviewed_by'),('reviewed_at'),('review_memo'),('create_key'),('time_created')) AS x(n)
   WHERE NOT EXISTS (SELECT 1 FROM information_schema.columns c
                      WHERE c.table_schema='public' AND c.table_name='job_submission' AND c.column_name = x.n);
  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION '0014 self-check FAILED: job_submission missing columns: %', v_missing;
  END IF;

  -- DL99：无分录动作表**不得**有 ledger_event_keys（证明「未借账本幂等」）
  SELECT string_agg(x.n, ',' ORDER BY x.n) INTO v_missing
    FROM (VALUES ('ledger_event_keys')) AS x(n)
   WHERE EXISTS (SELECT 1 FROM information_schema.columns c
                  WHERE c.table_schema='public' AND c.column_name = x.n
                    AND c.table_name IN ('job_application','job_submission'));
  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION '0014 self-check FAILED: DL99 violation, no-entry tables must not carry: %', v_missing;
  END IF;

  -- UNIQUE (job_id, worker_uid)（DL54）
  SELECT count(*) INTO v_idx
    FROM pg_constraint k
   WHERE k.conname = 'job_application_job_worker_uniq'
     AND k.contype = 'u'
     AND k.conrelid = 'public.job_application'::regclass;
  IF v_idx <> 1 THEN
    RAISE EXCEPTION '0014 self-check FAILED: UNIQUE(job_id,worker_uid) missing (DL54)';
  END IF;

  -- 部分唯一索引（DL55）：唯一 + `WHERE (status = 'accepted')`
  SELECT indexdef INTO v_def
    FROM pg_indexes i
   WHERE i.schemaname='public' AND i.tablename='job_application'
     AND i.indexname = 'uniq_job_application_accepted';
  IF v_def IS NULL THEN
    RAISE EXCEPTION '0014 self-check FAILED: partial unique index uniq_job_application_accepted missing (DL55)';
  END IF;
  IF position('CREATE UNIQUE INDEX' in upper(v_def)) = 0
     OR position('WHERE' in upper(v_def)) = 0
     OR position('accepted' in lower(v_def)) = 0 THEN
    RAISE EXCEPTION '0014 self-check FAILED: uniq_job_application_accepted is not a partial unique index: %', v_def;
  END IF;

  -- 触发器启用态（DL76/DL79/DL75③）：5 个 trg_（application 4 + submission 2 = 6，逐表断言）
  SELECT count(*) INTO v_trg
    FROM pg_trigger t
   WHERE NOT t.tgisinternal AND t.tgenabled = 'O'
     AND t.tgrelid = 'public.job_application'::regclass;
  IF v_trg <> 4 THEN
    RAISE EXCEPTION '0014 self-check FAILED: job_application enabled triggers = %, expected 4', v_trg;
  END IF;
  SELECT count(*) INTO v_trg
    FROM pg_trigger t
   WHERE NOT t.tgisinternal AND t.tgenabled = 'O'
     AND t.tgrelid = 'public.job_submission'::regclass;
  IF v_trg <> 2 THEN
    RAISE EXCEPTION '0014 self-check FAILED: job_submission enabled triggers = %, expected 2', v_trg;
  END IF;

  IF to_regprocedure('public.job_application_status_transition_ok(text,text)') IS NULL THEN
    RAISE EXCEPTION '0014 self-check FAILED: job_application_status_transition_ok(text,text) missing';
  END IF;

  -- 函数体内禁 DDL（DL142 同精神；本迁只有守卫函数）
  --   注：探测串用 chr(36) 拼 dollar-quote —— 本块自身是 dollar-quoted body，
  --   体内出现字面 dollar-quote 标记会提前闭合（同 0013 的实测）。
  SELECT string_agg(t.f || ':' || t.p, ',') INTO v_missing FROM (
    SELECT f.fn AS f, p.p AS p
      FROM (VALUES ('public.job_application_status_guard()'),
                   ('public.job_application_create_key_guard()'),
                   ('public.job_application_touch_time_updated()'),
                   ('public.job_application_no_delete()'),
                   ('public.job_submission_immutable_guard()'),
                   ('public.job_submission_no_delete()')) AS f(fn),
           (VALUES ('create table'),('alter table'),('drop table'),('truncate'),('create index'),
                   ('create function'),('rename to'),('do ' || chr(36) || chr(36))) AS p(p)
     WHERE position(upper(p.p) in upper(pg_get_functiondef(f.fn::regprocedure))) > 0
  ) AS t;
  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION '0014 self-check FAILED: DDL token(s) inside function bodies: %', v_missing;
  END IF;

  -- ---------------------------------------------------------------- 纯函数断言（应用状态白名单，正全集）
  IF NOT public.job_application_status_transition_ok('applied','accepted')
     OR NOT public.job_application_status_transition_ok('applied','rejected')
     OR NOT public.job_application_status_transition_ok('applied','withdrawn') THEN
    RAISE EXCEPTION '0014 self-check FAILED: application whitelist missing an allowed transition (DL55)';
  END IF;
  IF public.job_application_status_transition_ok('applied','applied')
     OR public.job_application_status_transition_ok('accepted','applied')
     OR public.job_application_status_transition_ok('accepted','rejected')
     OR public.job_application_status_transition_ok('rejected','accepted')
     OR public.job_application_status_transition_ok('withdrawn','accepted') THEN
    RAISE EXCEPTION '0014 self-check FAILED: application whitelist admits a forbidden transition (DL55)';
  END IF;

  RAISE NOTICE '0014 self-check OK: job_application cols=7 trg=4 / job_submission cols=10 trg=2 / partial-unique(accepted) ok';
END $$;
