-- 0023_admin_points_audit_daily_cap.sql
-- ============================================================================
-- P6-B6-AUDIT（Kong）· 管理面治理：A1 审计留痕 + 日累计闸
-- ============================================================================
-- 上游：`0022_admin_permission_seed.sql`。**不改 `0001`–`0022` 任何字节。**
--
-- 规格依据（逐字，不得改写）：
--   · `docs/route-layer.spec.md` §4.8 ⑨：「新增第 ② 类『**授权主体意图额**』（客户端可传，**但必须
--     权限校验 + 服务端上限校验（上限标 `TODO: Kevin 定值`）+ 审计留痕**）；逐事件表内 **A1 归入该类**」。
--   · §4.10 ③（A1 落定）：`POST /api/admin/points/adjust` = **有符号 `amount`**（`>0` ⇒ `op='mint'` +
--     `platform=true`；`<0` ⇒ `op='entries'` + **单腿 `kind='burn'`**）；**单次上限 ±100000**；
--     **`requireAdmin` 先于金额校验**；幂等键 = **`ops:` 系**；`uID<0`/库无此用户 ⇒
--     **400 `LEDGER_RESERVED_UID`**；**注册点不变**。
--   · **Zang 本批新定（进规格待 Jing 收口）**：**日累计上限 = 1,000,000 点/日**，**按操作人 + 自然日
--     （UTC）**，**超限 ⇒ 明确拒绝 + 机读 reason + 审计留痕**；阈值 = **服务端常量**，客户端永不参与。
--   · **★ Zang 2026-10-02 三条裁定（BE-AUDIT-FIX；本文件按裁定就地改，因 `0023` 尚未 apply）**：
--     ① **被拒的尝试必须留痕**（「零残留」的口径是**资金零残留**，**不是**「不得有表行」）——
--        被拒尝试恰恰是最该留痕的事件（有人在试着超额造币）；本仓**不落 access log** ⇒ 只写
--        服务端日志等于无痕迹。**实现约束：函数不得 `RAISE`**（异常会把同一函数内**已写的审计行**
--        一并回滚）⇒ 改为**函数返回拒绝回执**、**由路由层回 400 + 机读 reason**；审计行写
--        `result='rejected_daily_cap'`，**与「无资金分录」一起提交**。
--     ② **★ 拒绝行不得计入日累计**（否则反复发超限请求即可把当日额度刷爆、让管理员当天再也调不出
--        分 = 拒绝留痕带来的新攻击面）⇒ 日累计求和**只计成功行**（判据逐字：`result = 'applied'`）。
--     ③ **不新造错误码**（只用既有 `LD016` = `LEDGER_AMOUNT_INVALID` + 机读 `reason`）。
--   · **★ Zang 2026-10-02 裁定四（BE-AUDIT-FIX2；本文件**就地改**，因 `0023` **仍未 apply**）**：
--     幂等键的语义应约束「**效果**」、不应被「**尝试**」消费（同键重试同一意图必须能成功）。
--     `UNIQUE (idempotency_key)` ⇒ **`UNIQUE (idempotency_key, result)`**（一个索引同时把三向都修对）：
--       ① 同键被拒两次 ⇒ 冲突 ⇒ `DO NOTHING`（**拒绝行不放大**）；
--       ② 同键先拒后成 ⇒ `result` 不同 ⇒ **允许成功**（且既有拒绝行保留）；
--       ③ 同键成功两次 ⇒ 冲突 ⇒ **拦住**（真幂等保护不弱化）。
--     详见 §A 约束旁注释 + §D 自检（新增「复合唯一索引在场」判据）；三向实测见
--     `scripts/p4z-b6audit-02-idemkey.ts`（含「改回旧写法 ⇒ 第②向必败 23505」自证）。
--
-- 设计取向（Zang 硬要求）：
--   ① **审计行与资金事件压成「一次 DB 调用」**——与 `job_post_event` 同构（精神 = 「**结论位与资金
--      同语句**」）。**不得**写成「先调资金、再插入审计行」。本文件用**一个新的 DB 编排函数**
--      （`public.admin_points_adjust_post_event(jsonb)`）把三段压进**同一函数体、同一条语句**：
--        函数入口（`pg_advisory_xact_lock`）→ 存在性闸 → **日累计闸（同函数内读当日成功行求和）**
--        → `ledger_post_event`（资金）→ `INSERT admin_ops_audit_log`（审计）→ 回执。
--      任一失败 ⇒ **整条语句回滚** ⇒ 不存在「资金动了而审计没落」或反之。
--   ② **日累计闸放同一函数内读取**（对当日成功行求和）——目的：**防并发两笔同时卡在阈值下**。
--      同一语句内再取 `pg_advisory_xact_lock`（按操作人）⇒ 两笔串行：恰一笔过、另一笔被日累计拒。
--   ③ **阈值 = 服务端常量**，客户端永不参与；常量旁带 `TODO: Kevin 定值`。
--
-- 硬约束（沿用既有纪律）：
--   · 不改 `ledger_post_event` 函数体（裁定 #14 / CR81）；本文件只**新增**新函数。
--   · 不新增/不改任何账本错误码（§14.1 关闭集 33 不动）；超限拒绝**复用既有码** `LEDGER_AMOUNT_INVALID`
--     的通道（机读 `reason = OVER_MAX_DAILY_AMOUNT`，与既有 `OVER_MAX_SINGLE_AMOUNT` 同族）。
--   · 函数体内**无任何 DDL**（DL142）；审计表为 **append-only**（手法同 `0017` 的
--     `currency_status_log_append_only`）。
--   · 审计表**只增不删**（append-only 触发器覆盖 UPDATE OR DELETE；具名约束、索引齐）。
-- ============================================================================


-- ============================================================================
-- §A `public.admin_ops_audit_log`（管理面越权/资金动作审计；逐列标依据见交付报告 §1）
-- ============================================================================
-- 命名/列风格参照 `0017` 的 `public.currency_status_log`（7 列 + 身份证 PK + 具名约束 + append-only）。
-- 列清单（谁 / 何时 / 对谁 / 动作 / 值前值 / 请求指纹 / 幂等键 / 结果）：
--   who   = actor_uid                     ；when = time_created   ；whom = target_uid
--   act   = action / op / cid             ；value = amount + balance_before / balance_after
--   proof = request_fingerprint（DL96）+ idempotency_key（DL146② / DL36 `ops:` 系）
--   result= result（'applied' | 'rejected_daily_cap'）+ txid（账本回执）
CREATE TABLE IF NOT EXISTS public.admin_ops_audit_log (
  log_id              bigint      GENERATED BY DEFAULT AS IDENTITY,          -- 依据 0017:140 先例（身份证 PK）
  actor_uid           bigint      NOT NULL,                                   -- 依据 §4.10③ requireAdmin ⇒ 操作人；
                                                                              --   日累计口径「按操作人」（Zang 新定）
  action              text        NOT NULL,                                   -- 依据 §4.8⑨② 「授权主体意图额」逐动作留痕；
                                                                              --   本仓 A1 = 'points_adjust'
  target_uid          bigint      NOT NULL,                                   -- 依据 §4.10③ `uID` ⇒「对谁」
  cid                 bigint      NOT NULL,                                   -- 依据现盘 A1 恒 `cid=1`（database.ts:1066 ref_id '1'）
  op                  text        NOT NULL,                                   -- 依据 §4.10③ 符号派生 ⇒ 'mint' | 'burn'
  amount              bigint      NOT NULL,                                   -- 依据 §4.10③ **有符号** amount（值）
  balance_before      numeric,                                                -- 依据「值前值」要求；= 事后余额 − amount（账本回执推导）
  balance_after       numeric,                                                -- 依据「值前值」要求；= 账本回执 accounts[].balance
  request_fingerprint text        NOT NULL,                                   -- 依据 DL96（index.ts:1268 现盘）
  idempotency_key     text        NOT NULL,                                   -- 依据 DL146② / §4.8（`ops:` 系；index.ts:1264 现盘）
  result              text        NOT NULL,                                   -- 依据「结果」列要求 + Zang 裁定①（拒绝亦须留痕）
  txid                bigint,                                                 -- 依据账本回执 `txid`（成功时；拒绝行 = NULL）
  memo                text,                                                   -- 依据 0017:145 `currency_status_log.memo` 先例（= reason）
  time_created        timestamptz NOT NULL DEFAULT now(),                     -- 依据 0017:146 先例；日累计「自然日（UTC）」判据列
  CONSTRAINT admin_ops_audit_log_pk         PRIMARY KEY (log_id),
  CONSTRAINT admin_ops_audit_log_actor_fk   FOREIGN KEY (actor_uid)  REFERENCES public.users(uid),
  CONSTRAINT admin_ops_audit_log_target_fk  FOREIGN KEY (target_uid) REFERENCES public.users(uid),
  CONSTRAINT admin_ops_audit_log_cid_fk     FOREIGN KEY (cid)        REFERENCES public.currency(cid),
  CONSTRAINT admin_ops_audit_log_action_ck CHECK (action = 'points_adjust'),
  CONSTRAINT admin_ops_audit_log_op_ck     CHECK (op IN ('mint', 'burn')),
  CONSTRAINT admin_ops_audit_log_amount_ck CHECK (amount <> 0),
  CONSTRAINT admin_ops_audit_log_result_ck CHECK (result IN ('applied', 'rejected_daily_cap')),
  -- ★ Zang 裁定四（BE-AUDIT-FIX2）：幂等键的语义约束「**效果**」、不约束「**尝试**」。
  -- 旧写法 `UNIQUE (idempotency_key)` 对成功行与拒绝行**一视同仁** ⇒ **被拒的键即被消费**：
  --   额度释放后客户端拿**同一个键**重投 ⇒ 末尾 `'applied'` 插入撞上既有拒绝行 ⇒ `23505` ⇒
  --   **整条语句回滚**（客户端拿到莫名的约束错误）。
  -- 改法 `UNIQUE (idempotency_key, result)` —— 一个索引同时把三向都修对：
  --   ① 同键被拒两次 ⇒ `(key,'rejected_daily_cap')` 冲突 ⇒ `DO NOTHING`（**拒绝行不放大**）；
  --   ② 同键先拒后成 ⇒ `result` 不同 ⇒ **允许成功**（且既有拒绝行保留）；
  --   ③ 同键成功两次 ⇒ `(key,'applied')` 冲突 ⇒ **拦住**（真幂等保护不弱化）。
  -- 结论位对「同键 + 同结果」唯一：同键**不得**产生第二行**同结果**审计（DL146② 兜底不弱化）。
  CONSTRAINT admin_ops_audit_log_idem_uniq UNIQUE (idempotency_key, result)
);

COMMENT ON TABLE public.admin_ops_audit_log IS
  'P6-B6-AUDIT（Kong；依据 route-layer.spec §4.8⑨② + §4.10③，Zang 2026-10-02 新定 + 三条裁定）：管理面「授权主体意图额」类动作（本仓 A1 = 后台调分）的**审计留痕**。列风格参照 0017.currency_status_log（身份证 PK + 具名约束 + append-only）。**只增不删**：BEFORE UPDATE OR DELETE 无条件 RAISE。actor_uid/target_uid FK users(uid)、cid FK currency(cid)。**成功行与拒绝行同表**（`result` 区分）。诚实边界：append-only 触发器不拦 TRUNCATE / DISABLE TRIGGER USER（与 0017 同边界）。';

COMMENT ON COLUMN public.admin_ops_audit_log.balance_before IS
  '值前值（余额）。账本回执只给事后余额 ⇒ 本列 = balance_after − amount（同一函数内推导，非外部传入）。**拒绝行 = NULL**（无资金事件）。';
COMMENT ON COLUMN public.admin_ops_audit_log.result IS
  '结论位。''applied'' = 资金事件已落且本审计行与它同语句（**计入**当日累计）；''rejected_daily_cap'' = 日累计闸拒绝的**留痕**行（Zang 裁定①：被拒尝试必须留痕）——**零资金分录**、balance_before/balance_after/txid 皆 NULL、memo=OVER_MAX_DAILY_AMOUNT，且**不计入**日累计求和（裁定②：只对 result=''applied'' 求和，防「反复发超限请求把当日额度刷爆」）。';


-- ============================================================================
-- §B append-only 守卫（手法同 0017:192-200 `currency_status_log_append_only`）
-- ============================================================================
CREATE OR REPLACE FUNCTION public.admin_ops_audit_log_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'admin_ops_audit_log is append-only: % forbidden (log_id=%)',
        TG_OP, COALESCE(OLD.log_id, 0);
END $$;

COMMENT ON FUNCTION public.admin_ops_audit_log_append_only() IS
  'P6-B6-AUDIT：审计表 append-only（BEFORE UPDATE OR DELETE 无条件 RAISE，原生 P0001，不借账本错误码 ⇒ 不建账本类对象）。只由迁移创建；体内无 DDL。诚实边界：不拦 TRUNCATE / DISABLE TRIGGER USER。';

DROP TRIGGER IF EXISTS trg_admin_ops_audit_log_append_only ON public.admin_ops_audit_log;
CREATE TRIGGER trg_admin_ops_audit_log_append_only
  BEFORE UPDATE OR DELETE ON public.admin_ops_audit_log
  FOR EACH ROW EXECUTE FUNCTION public.admin_ops_audit_log_append_only();

-- 索引齐：
--   · `admin_ops_audit_log_actor_day_idx` —— **日累计闸**的求和路径（按操作人 + 自然日 UTC；本单核心读）;
--   · `admin_ops_audit_log_target_idx`     —— 「对谁」的审计检索路径（谁被调过分）。
-- （PK 索引与 `admin_ops_audit_log_idem_uniq` 唯一索引由约束自带 ⇒ 计 4 个索引。）
CREATE INDEX IF NOT EXISTS admin_ops_audit_log_actor_day_idx
  ON public.admin_ops_audit_log (actor_uid, time_created);
CREATE INDEX IF NOT EXISTS admin_ops_audit_log_target_idx
  ON public.admin_ops_audit_log (target_uid, time_created);


-- ============================================================================
-- §C 唯一资金写路径编排函数（DL20 提案 A；硬约束 DL141–DL144）
-- ============================================================================
-- 与 `public.job_post_event(jsonb)` **同构**：调用方一条语句 `SELECT public.admin_points_adjust_post_event($1::jsonb)`
-- ⇒ 函数内「并发闸 → 存在性闸 → 日累计闸 → 派生分录 → 调 ledger_post_event → 写审计行 → 回执」
--    **同函数、同语句**（= 一个隐式事务）。
-- 回执形状（全部为 jsonb 标量，路由层用 `->>` 取值 ⇒ 不依赖 TS 侧 JSON 解析）：
--   { ok, user_found, reason, op, amount, idempotent_replay, txid, new_balance, audit_logged,
--     daily_cap, daily_used, entries, accounts }
--   · 拒绝回执（Zang 裁定①，**函数正常返回、不 RAISE**）：
--     { ok:false, user_found:1, reason:'OVER_MAX_DAILY_AMOUNT', op, requested, daily_cap, daily_used }
-- 契约：
--   · `user_found = 0` ⇒ 库内无该目标用户 ⇒ **零写**（不调账本、不写审计），由路由映射既有码 LD021。
--   · `ok = false` + `reason = 'OVER_MAX_DAILY_AMOUNT'` ⇒ 日累计闸拒 ⇒ **零资金分录、留一行审计**
--     （`result='rejected_daily_cap'`，与「无资金分录」一起提交）。**函数不得 `RAISE`**：异常会把同一
--     函数内**已写的拒绝审计行**一并回滚（被拒尝试恰恰最该留痕）；故本分支**正常返回拒绝回执**，
--     由路由层据此回 `400` + 既有码 LD016（`LEDGER_AMOUNT_INVALID`）+ 机读 `reason`（裁定③：零新码）。
--   · 成功 ⇒ 资金事件与审计行**同生**；同键同指纹重放 ⇒ `idempotent_replay=true` 且**不写第二行审计**。
CREATE OR REPLACE FUNCTION public.admin_points_adjust_post_event(payload jsonb) RETURNS jsonb
LANGUAGE plpgsql AS $$
DECLARE
  -- ★★ 服务端常量（**客户端永不参与**）：日累计上限 = 1,000,000 点/日，按操作人 + 自然日（UTC）。
  -- TODO: Kevin 定值
  v_daily_cap   CONSTANT bigint := 1000000;

  v_actor       bigint := (payload->>'actor_uid')::bigint;
  v_target      bigint := (payload->>'target_uid')::bigint;
  v_cid         bigint := COALESCE((payload->>'cid')::bigint, 1);
  v_amount      bigint := (payload->>'amount')::bigint;
  v_reason      text   := COALESCE(payload->>'reason', '');
  v_key         text   := payload->>'idempotency_key';
  v_fp          text   := payload->>'request_fingerprint';

  v_day_start   timestamptz := date_trunc('day', now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC';
  v_used        bigint;
  v_op          text;
  v_envelope    jsonb;
  v_ledger      jsonb;
  v_txid        text;
  v_replay      boolean := false;
  v_new_balance numeric;
  v_bal_before  numeric;
  v_audited     boolean := false;
BEGIN
  -- ---------------------------------------------------------------- ① 并发闸（同一语句内）
  -- 按操作人取事务级 advisory lock ⇒ 同一操作人的并发两笔**串行**：后到者读到前者的已提交审计行
  -- ⇒ 「两笔同时卡在阈值下」的竞态被消除（恰一笔过、另一笔被日累计拒）。
  PERFORM pg_advisory_xact_lock(hashtextextended('admin_points_adjust:' || v_actor::text, 0));

  -- ---------------------------------------------------------------- ② 目标存在性闸（零写）
  IF NOT EXISTS (SELECT 1 FROM public."users" AS u WHERE u.uid = v_target) THEN
    RETURN jsonb_build_object('ok', false, 'user_found', 0, 'reason', NULL,
                              'daily_cap', v_daily_cap, 'daily_used', NULL);
  END IF;

  -- ---------------------------------------------------------------- ③ 符号 ⇒ op（提前派生）
  -- 拒绝行也须携带**合法 op**（CHECK `op IN ('mint','burn')` 对两类结果行一视同仁）⇒ 在日累计闸
  -- **之前**派生，使「被拒尝试」的审计行与成功行同形（只差 `result` / `txid` / 余额两列）。
  IF v_amount > 0 THEN v_op := 'mint'; ELSE v_op := 'burn'; END IF;

  -- ---------------------------------------------------------------- ③' 日累计闸（同函数内读当日审计行求和）
  -- ★ 求和口径（逐字，Zang 裁定②）：`actor_uid = v_actor` 且 **`result = 'applied'`（只计成功行）**
  --   且 `time_created >= 当日 00:00 UTC` 的 `abs(amount)` 之和。
  -- ★ 为何必须排除拒绝行：被拒行同样携带 `amount`（= 请求值，非零）；若把它计入求和，则**反复发
  --   超限请求即可把当日额度刷爆**（每笔被拒都在「已用」上再加一笔）⇒ 管理员当天再也调不出分
  --   = 拒绝留痕引入的新攻击面。故**只计成功行**（`result = 'applied'`）。
  -- `idempotency_key <> v_key`：把**本次键的既有行**排除 ⇒ 同键重放不会被自己顶穿（否则 900k 的重放
  --   会因 900k+900k > cap 被误拒）；对**新键**而言该排除项不命中 ⇒ 判定不变。
  SELECT COALESCE(sum(abs(a.amount)), 0)::bigint INTO v_used
    FROM public.admin_ops_audit_log AS a
   WHERE a.actor_uid  = v_actor
     AND a.result     = 'applied'
     AND a.time_created >= v_day_start
     AND a.idempotency_key <> v_key;

  IF v_used + abs(v_amount) > v_daily_cap THEN
    -- 拒绝留痕（Zang 裁定①）：写审计行 `result='rejected_daily_cap'`，**与「零资金分录」一起提交**。
    -- **不得以异常中止**：异常会把同一函数内**已写的这一行**一并回滚（被拒尝试恰恰最该留痕）；
    -- 且本仓不落 access log ⇒ 只写服务端日志等于无痕迹。故此处**正常返回拒绝回执**。
    -- 同键重投 ⇒ `ON CONFLICT DO NOTHING` ⇒ **不重复写审计行**（与「幂等」口径一致）。
    INSERT INTO public.admin_ops_audit_log
      (actor_uid, action, target_uid, cid, op, amount, balance_before, balance_after,
       request_fingerprint, idempotency_key, result, txid, memo)
    VALUES
      (v_actor, 'points_adjust', v_target, v_cid, v_op, v_amount, NULL, NULL,
       v_fp, v_key, 'rejected_daily_cap', NULL, 'OVER_MAX_DAILY_AMOUNT')
    ON CONFLICT (idempotency_key, result) DO NOTHING;
    RETURN jsonb_build_object('ok', false, 'user_found', 1, 'reason', 'OVER_MAX_DAILY_AMOUNT',
                              'op', v_op, 'requested', v_amount::text,
                              'daily_cap', v_daily_cap, 'daily_used', v_used);
  END IF;

  -- ---------------------------------------------------------------- ④ 派生分录（§4.10③ 逐字；op 已在 ③ 派生）
  IF v_op = 'mint' THEN
    v_envelope := jsonb_build_object(
      'op', 'mint', 'idempotency_key', v_key, 'request_fingerprint', v_fp, 'memo', v_reason,
      'ref_type', 'currency', 'ref_id', v_cid::text,
      'uid', v_target::text, 'cid', v_cid::text, 'amount_units', v_amount::text, 'platform', true);
  ELSE
    v_envelope := jsonb_build_object(
      'op', 'entries', 'idempotency_key', v_key, 'request_fingerprint', v_fp, 'memo', v_reason,
      'ref_type', 'currency', 'ref_id', v_cid::text,
      'entries', jsonb_build_array(jsonb_build_object(
        'uid', v_target::text, 'cid', v_cid::text, 'delta', v_amount::text, 'kind', 'burn')));
  END IF;

  -- ---------------------------------------------------------------- ⑤ 资金事件（既有账本函数；同一语句内）
  -- 锁序：advisory（本函数）→ currency（cid 升序）→ account（uid 升序）—— 后两段由 ledger_post_event
  -- 内部完成；本函数**绝不**先锁 account（否则 AB-BA 死锁）。
  v_ledger := public.ledger_post_event(v_envelope);
  v_txid   := v_ledger->>'txid';
  v_replay := COALESCE((v_ledger->>'idempotent_replay')::boolean, false);

  SELECT (e->>'balance')::numeric INTO v_new_balance
    FROM jsonb_array_elements(v_ledger->'accounts') AS t(e)
   WHERE (e->>'uid')::bigint = v_target AND (e->>'cid')::bigint = v_cid;

  -- ---------------------------------------------------------------- ⑥ 审计行（与资金同函数、同语句）
  -- DL144① 同精神：**重放 ⇒ 不写第二行审计**（同时被 `admin_ops_audit_log_idem_uniq` 兜住）。
  IF NOT v_replay THEN
    v_bal_before := v_new_balance - v_amount;     -- 账本只给事后余额 ⇒ 前值 = 事后 − amount
    INSERT INTO public.admin_ops_audit_log
      (actor_uid, action, target_uid, cid, op, amount, balance_before, balance_after,
       request_fingerprint, idempotency_key, result, txid, memo)
    VALUES
      (v_actor, 'points_adjust', v_target, v_cid, v_op, v_amount, v_bal_before, v_new_balance,
       v_fp, v_key, 'applied', v_txid::bigint, v_reason);
    v_audited := true;
  END IF;

  RETURN jsonb_build_object(
    'ok', true, 'user_found', 1, 'reason', NULL, 'op', v_op, 'amount', v_amount::text,
    'idempotent_replay', v_replay, 'txid', v_txid,
    'new_balance', CASE WHEN v_new_balance IS NULL THEN NULL ELSE v_new_balance::text END,
    'audit_logged', v_audited, 'daily_cap', v_daily_cap, 'daily_used', v_used,
    'entries', v_ledger->'entries', 'accounts', v_ledger->'accounts');
END $$;

COMMENT ON FUNCTION public.admin_points_adjust_post_event(jsonb) IS
  'P6-B6-AUDIT（DL20 提案 A；硬约束 DL141–DL144；Zang 2026-10-02 三条裁定）：A1 后台调分的**唯一资金写路径**。同一函数/同一语句内完成「pg_advisory_xact_lock（按操作人）→ 目标存在性闸 → 符号⇒op → 日累计闸（读 admin_ops_audit_log 当日 **result=''applied''** 行求和；阈值 1000000 点/日，服务端常量）→ 派生分录 → 调 ledger_post_event → INSERT admin_ops_audit_log → 回执」⇒ **审计行与资金事件同生同灭**。有符号 amount：>0 ⇒ mint（platform=true）；<0 ⇒ entries 单腿 kind=burn（§4.10③）。超限 ⇒ **正常返回** {ok:false, reason:''OVER_MAX_DAILY_AMOUNT'', op, requested, daily_cap, daily_used}，**同时写一行 result=''rejected_daily_cap'' 审计行**（**零资金分录**、余额列与 txid 皆 NULL），由路由映射既有码 LD016；本函数**不含任何 RAISE**（异常会回滚同函数内已写的拒绝审计行）。同键重放：成功 ⇒ idempotent_replay=true 不写第二行；被拒 ⇒ ON CONFLICT DO NOTHING 不重复写。函数体内无任何 DDL。';


-- ============================================================================
-- §D apply-time 自检（DL48：不通过则整迁移回滚、**不写版本行**）
-- ============================================================================
DO $$
DECLARE
  v_names text;
  v_n     int;
  v_trg   int;
  v_covers int;
  v_def   text;
BEGIN
  -- ---------------------------------------------------------------- 结构：审计表在场
  IF to_regclass('public.admin_ops_audit_log') IS NULL THEN
    RAISE EXCEPTION '0023 self-check FAILED: public.admin_ops_audit_log missing';
  END IF;

  -- 15 列，逐名（只增不删：名字齐全即通过；多列不判负以留后续扩展）
  SELECT string_agg(column_name, ',' ORDER BY ordinal_position) INTO v_names
    FROM information_schema.columns
   WHERE table_schema = 'public' AND table_name = 'admin_ops_audit_log';
  IF v_names <> 'log_id,actor_uid,action,target_uid,cid,op,amount,balance_before,balance_after,request_fingerprint,idempotency_key,result,txid,memo,time_created' THEN
    RAISE EXCEPTION '0023 self-check FAILED: admin_ops_audit_log columns = %', v_names;
  END IF;

  -- 具名约束齐：PK×1 / FK×3 / CHECK×4 / UNIQUE×1
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.admin_ops_audit_log'::regclass AND contype = 'p';
  IF v_n <> 1 THEN RAISE EXCEPTION '0023 self-check FAILED: audit PK count = %', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.admin_ops_audit_log'::regclass AND contype = 'f';
  IF v_n <> 3 THEN RAISE EXCEPTION '0023 self-check FAILED: audit FK count = % (expect 3: actor/target/cid)', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.admin_ops_audit_log'::regclass AND contype = 'c' AND conname LIKE 'admin_ops_audit_log_%_ck';
  IF v_n <> 4 THEN RAISE EXCEPTION '0023 self-check FAILED: audit CHECK count = % (expect 4)', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.admin_ops_audit_log'::regclass AND contype = 'u' AND conname = 'admin_ops_audit_log_idem_uniq';
  IF v_n <> 1 THEN RAISE EXCEPTION '0023 self-check FAILED: audit idempotency UNIQUE missing'; END IF;
  -- ★ Zang 裁定四（BE-AUDIT-FIX2）：唯一键必须是**复合** `(idempotency_key, result)`（恰两列、非部分索引）。
  --   旧单列写法会把「被拒的尝试」当成已消费 ⇒ 同键先拒后成时 `23505` ⇒ 整条语句回滚（客户端莫名报错）。
  --   结构存在性走 `pg_constraint`(DDL) + `pg_index`/`indnkeyatts`/`indpred`(索引目录) 取证，非源码推断。
  IF (SELECT pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid='public.admin_ops_audit_log'::regclass AND conname='admin_ops_audit_log_idem_uniq')
     <> 'UNIQUE (idempotency_key, result)' THEN
    RAISE EXCEPTION '0023 self-check FAILED: audit idem UNIQUE 非复合 (idempotency_key, result)，实际=%',
      (SELECT COALESCE(pg_get_constraintdef(oid), '<none>') FROM pg_constraint
        WHERE conrelid='public.admin_ops_audit_log'::regclass AND conname='admin_ops_audit_log_idem_uniq');
  END IF;
  SELECT count(*) INTO v_n
    FROM pg_index i JOIN pg_class ic ON ic.oid = i.indexrelid
   WHERE i.indrelid = 'public.admin_ops_audit_log'::regclass
     AND i.indisunique AND NOT i.indisprimary
     AND ic.relname = 'admin_ops_audit_log_idem_uniq'
     AND i.indnkeyatts = 2 AND i.indpred IS NULL
     AND pg_get_indexdef(i.indexrelid) LIKE '%(idempotency_key, result)%';
  IF v_n <> 1 THEN RAISE EXCEPTION '0023 self-check FAILED: 复合唯一索引 (idempotency_key, result) 不在场 (count=%)', v_n; END IF;

  -- 索引齐：PK + 日累计索引 + (PK 之外的具名索引 ≥ 2)
  SELECT count(*) INTO v_n FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'admin_ops_audit_log';
  IF v_n < 4 THEN RAISE EXCEPTION '0023 self-check FAILED: audit index count = % (expect >= 4)', v_n; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='admin_ops_audit_log'
                   AND indexname='admin_ops_audit_log_actor_day_idx') THEN
    RAISE EXCEPTION '0023 self-check FAILED: admin_ops_audit_log_actor_day_idx missing';
  END IF;

  -- append-only：恰好 1 个启用触发器，且覆盖 UPDATE OR DELETE
  SELECT count(*) INTO v_trg FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relname = 'admin_ops_audit_log' AND NOT t.tgisinternal AND t.tgenabled = 'O';
  IF v_trg <> 1 THEN RAISE EXCEPTION '0023 self-check FAILED: audit enabled triggers = %, expect 1', v_trg; END IF;
  SELECT count(*) INTO v_covers FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relname = 'admin_ops_audit_log' AND NOT t.tgisinternal
     AND (t.tgtype & 2) <> 0 AND (t.tgtype & 8) <> 0 AND (t.tgtype & 16) <> 0;
  IF v_covers <> 1 THEN RAISE EXCEPTION '0023 self-check FAILED: append-only trigger must cover UPDATE OR DELETE'; END IF;

  -- 编排函数在场 + 返回类型 + 关键机体（并发闸 / 日累计常量 / 审计插入）
  IF to_regprocedure('public.admin_points_adjust_post_event(jsonb)') IS NULL THEN
    RAISE EXCEPTION '0023 self-check FAILED: admin_points_adjust_post_event(jsonb) missing';
  END IF;
  SELECT pg_get_functiondef(p.oid) INTO v_def FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE n.nspname = 'public' AND p.proname = 'admin_points_adjust_post_event';
  IF v_def IS NULL THEN RAISE EXCEPTION '0023 self-check FAILED: admin_points_adjust_post_event not found in public'; END IF;
  IF position('pg_advisory_xact_lock' IN v_def) = 0 THEN
    RAISE EXCEPTION '0023 self-check FAILED: 并发闸 pg_advisory_xact_lock 不在函数体内';
  END IF;
  IF position('1000000' IN v_def) = 0 THEN
    RAISE EXCEPTION '0023 self-check FAILED: 日累计常量 1000000 不在函数体内';
  END IF;
  -- ★ Zang 裁定①：函数体内**不得出现 RAISE**（异常会回滚同函数内已写的拒绝留痕行）
  IF position('RAISE' IN v_def) <> 0 THEN
    RAISE EXCEPTION '0023 self-check FAILED: 日累计函数体内出现 RAISE（异常会回滚已写的拒绝留痕行）';
  END IF;
  -- ★ Zang 裁定①：拒绝留痕分支在场（结果位 'rejected_daily_cap'）
  IF position('rejected_daily_cap' IN v_def) = 0 THEN
    RAISE EXCEPTION '0023 self-check FAILED: 拒绝留痕分支（result=rejected_daily_cap）缺失';
  END IF;
  -- ★ Zang 裁定②：日累计求和**只计成功行**（判据 result = 'applied'）
  IF position('result = ''applied''' IN v_def) = 0 THEN
    RAISE EXCEPTION '0023 self-check FAILED: 日累计求和判据 result=''applied'' 缺失';
  END IF;
  IF position('admin_ops_audit_log' IN v_def) = 0 OR position('ledger_post_event' IN v_def) = 0 THEN
    RAISE EXCEPTION '0023 self-check FAILED: 审计行与资金事件未压进同一函数体';
  END IF;
  IF to_regprocedure('public.admin_ops_audit_log_append_only()') IS NULL THEN
    RAISE EXCEPTION '0023 self-check FAILED: admin_ops_audit_log_append_only() missing';
  END IF;

  -- 指纹守卫：`ledger_post_event` 签名/返回类型未变（不改函数体，只新增调用方）
  SELECT count(*) INTO v_n FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE n.nspname = 'public' AND p.proname = 'ledger_post_event'
     AND pg_get_function_identity_arguments(p.oid) = 'payload jsonb' AND pg_get_function_result(p.oid) = 'jsonb';
  IF v_n <> 1 THEN RAISE EXCEPTION '0023 self-check FAILED: ledger_post_event fingerprint changed (DL142)'; END IF;

  RAISE NOTICE '0023 self-check OK: admin_ops_audit_log 15 cols / PK×1 FK×3 CHECK×4 UNIQUE×1 / idx×4 / trg×1(O,UPDATE|DELETE) / admin_points_adjust_post_event(jsonb) 在场（advisory lock + cap 1000000 + ledger_post_event + 成功审计 insert + 拒绝留痕 insert、无 RAISE）/ ledger_post_event 指纹不变';
END $$;
