-- 0024_admin_refund_audit.sql
-- ============================================================================
-- P7-B · §7-32「管理员退款发起」（Kong）· 审计留痕 + 唯一资金编排
-- ============================================================================
-- 上游：`0023_admin_points_audit_daily_cap.sql`。**不改 `0001`–`0023` 任何字节。**
--
-- 规格依据（逐字，不得改写）：`docs/route-layer.spec.md` **v1.8**：
--   · §12.11.1 **Z2 = 变体 B**：新建审计表 `public.admin_refund_audit_log`
--     （四条依据 = ① `0023:86` `CHECK (action='points_adjust')` 是**单值**约束；
--      ② 🔴 `0023:207-212` 的日累计求和**无 `action` 过滤** ⇒ 任何落入 `admin_ops_audit_log`
--         的 `result='applied'` 行（含将来的退款行）都会被计入 A1 的 `1,000,000 点/日`额度
--         = **跨特性静默污染**；③ 复用须 `CREATE OR REPLACE` 改**已 apply** 的函数体
--         ⇒ 作废 `0023` 质检的字节级锚；④ 该表列语义是**调分中心**的（`op IN ('mint','burn')`
--         + 单一 `target_uid`）⇒ 退款（seller + buyer + `order_id`）塞进去必被**信息压缩**）。
--   · §12.11.1 **Z3 = 留痕**：`result` 闭集 = `{'applied','rejected_state'}`；**函数不得 `RAISE`**
--     （异常会把同函数内**已写的审计行**一并回滚）⇒ 返回拒绝回执、由路由映射 `409`；
--     同键重投 `ON CONFLICT (idempotency_key, result) DO NOTHING`。
--   · §12.11.1 **Z4 = 新编排函数 `public.listing_refund_post_event(jsonb)`**；
--     **★ 硬约束（防双真源）**：必须**复用既有资金路径**（同一语句内调既有
--     `public.listing_post_event(payload)`（`op='refund'`）；`purchase_refund` ×2 / 金额服务端取数
--     （`0015:711`）/ 不回滚库存（`0015:775-781`）**全在 `0015` 里**）⇒ **严禁复制退款资金腿**；
--     审计行 `INSERT` 必须与该资金调用**同函数、同一次 DB 调用**。
--   · §12.11.1 **Z4b = 不取 `pg_advisory_xact_lock`**（本批无日累计闸 ⇒ 无跨行读-改-写聚合；
--     同订单串行性由 `0015:670` 的 `SELECT … FOR UPDATE` 行锁承担）。
--   · §12.12.2 **T-2 = 变体①**：`BEGIN … EXCEPTION WHEN SQLSTATE 'LD011' THEN … END` 捕获
--     （先例 `0008:87/98/103`）；**白名单 = `SQLSTATE='LD011'` ∧ `reason ∈
--     {order_not_refundable, order_pay_missing}`**（`reason` 载体 = `ledger_raise` 的 `DETAIL`，
--     读取照抄 `0004:1094` 的 `GET STACKED DIAGNOSTICS … PG_EXCEPTION_DETAIL`）。
--   · §12.12.3 **① 白名单式捕获、严禁 `WHEN OTHERS`**（否则基础设施错误 `53300`/`XX000`
--     会被吞成「被拒」= D-04 那类真缺陷）；**② 拒收回执与审计行一起提交（零资金残留）**；
--     **③ 子事务回滚不得波及其他已写对象**（审计行 `INSERT` 落在 `EXCEPTION` 处理器内）。
--   · §12.11.2-E / §12.12.7 **I-16**：`0024` 自带 **apply-time 自检**（列集 / 约束 / 触发器
--     启用态 / 键集 / **反断言**：函数体内不得出现 `purchase_refund`、不得有 `WHEN OTHERS`、
--     不得有 `RAISE`）；失败整体回滚（`DL48`）。
--
-- 设计取向（照抄 `0023` 的 `admin_ops_audit_log` / `admin_points_adjust_post_event` 手法）：
--   · 审计表 = **13 列**（12 语义列 + `log_id` 结构列，T-1 变体①）；列类型 / 约束命名风格 /
--     append-only 手法 / 索引形态 / 自检结构**全部照抄 `0023`**，**未另创风格**。
--   · **只增不删**：`BEFORE UPDATE OR DELETE` 无条件 `RAISE`（原生 `P0001`，不借账本错误码）。
--   · **无 `op` 列**（退款既非 mint 亦非 burn ⇒ 不引入 `op`；这正是变体 B 免于信息压缩的点）。
--   · **纪律**：任何求和 / 额度判据只计 `result='applied'`（即便本批无闸）。
-- ============================================================================


-- ============================================================================
-- §A `public.admin_refund_audit_log`（逐列照抄 `0023:64-99` 风格；列集 = 退款语义、不压缩）
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.admin_refund_audit_log (
  log_id              bigint      GENERATED BY DEFAULT AS IDENTITY,          -- 照抄 0023:65（身份证 PK；T-1 变体①）
  actor_uid           bigint      NOT NULL,                                   -- 照抄 0023:66（发起人 uid；token 侧；不得由客户端声明）
  order_id            bigint      NOT NULL,                                   -- 退款目标订单（listing_order.order_id；无业务表 FK，照抄 0023「无业务表 FK」先例）
  seller_uid          bigint      NOT NULL,                                   -- 照抄 0023:70 手法（被扣款方，−amount）
  buyer_uid           bigint      NOT NULL,                                   -- 照抄 0023:70 手法（收款方，+amount）
  cid                 bigint      NOT NULL,                                   -- 照抄 0023:71
  amount              bigint      NOT NULL,                                   -- 照抄 0023:73（= price × quantity，服务端取数）
  result              text        NOT NULL,                                   -- 照抄 0023:78（闭集换值 = Z3：{'applied','rejected_state'}）
  txid                bigint,                                                 -- 照抄 0023:79（账本回执 txid；拒绝行 = NULL）
  idempotency_key     text        NOT NULL,                                   -- 照抄 0023:77（= biz:listing:refund:<order_id>，逐字同资金事件根键）
  request_fingerprint text        NOT NULL,                                   -- 照抄 0023:76（= sha256('listing.refund'|<order_id>)，服务端派生）
  memo                text,                                                   -- 照抄 0023:80（拒绝 = reason）
  time_created        timestamptz NOT NULL DEFAULT now(),                     -- 照抄 0023:81（DB 生成，不得客户端传）
  CONSTRAINT admin_refund_audit_log_pk        PRIMARY KEY (log_id),
  CONSTRAINT admin_refund_audit_log_actor_fk  FOREIGN KEY (actor_uid)  REFERENCES public.users(uid),
  CONSTRAINT admin_refund_audit_log_seller_fk FOREIGN KEY (seller_uid) REFERENCES public.users(uid),
  CONSTRAINT admin_refund_audit_log_buyer_fk  FOREIGN KEY (buyer_uid)  REFERENCES public.users(uid),
  CONSTRAINT admin_refund_audit_log_cid_fk    FOREIGN KEY (cid)        REFERENCES public.currency(cid),
  CONSTRAINT admin_refund_audit_log_amount_ck CHECK (amount <> 0),
  CONSTRAINT admin_refund_audit_log_result_ck CHECK (result IN ('applied', 'rejected_state')),
  -- ★ 沿用 `0023` 裁定四（「幂等键的语义约束**效果**、不约束**尝试**」）：
  --   同键被拒两次 ⇒ `(key,'rejected_state')` 冲突 ⇒ DO NOTHING（拒绝行不放大）；
  --   同键先拒后成 ⇒ `result` 不同 ⇒ 允许成功；同键成功两次 ⇒ `(key,'applied')` 冲突 ⇒ 拦住。
  CONSTRAINT admin_refund_audit_log_idem_uniq UNIQUE (idempotency_key, result)
);

COMMENT ON TABLE public.admin_refund_audit_log IS
  'P7-B（Kong；依据 route-layer.spec §12.11.1 Z2 = 变体 B / §12.11.2）：§7-32「管理员退款发起」的**审计留痕**（actor_uid = 发起人；order_id/seller_uid/buyer_uid 逐列表达两方，**不压缩**）。列风格 / 约束命名 / 索引形态照抄 0023 的 admin_ops_audit_log。**只增不删**：BEFORE UPDATE OR DELETE 无条件 RAISE。**成功行与拒绝行同表**（`result` 闭集 = {applied, rejected_state}）。**与 A1 的 admin_ops_audit_log 零耦合**（后者日累计求和无 action 过滤 ⇒ 退款行若落入会静默污染 1,000,000 点/日额度）。纪律：任何求和 / 额度判据只计 result=''applied''。诚实边界：append-only 触发器不拦 TRUNCATE / DISABLE TRIGGER USER（同 DL65 / 0023:103）。';

COMMENT ON COLUMN public.admin_refund_audit_log.result IS
  '结论位。''applied'' = 资金事件已落且本审计行与它同函数同语句；''rejected_state'' = 已进入资金编排、被状态机拒绝（409 LD011）的**留痕**行（Z3）——**零资金分录**、txid=NULL、memo=reason。**闸前拒绝（401/403）与 404/400 一律不写本表**（Z5 / T-3）。';
COMMENT ON COLUMN public.admin_refund_audit_log.idempotency_key IS
  '资金事件根键**逐字**（= biz:listing:refund:<order_id>；成功行由资金回执 ledger_idempotency_key 回填）。';
COMMENT ON COLUMN public.admin_refund_audit_log.order_id IS
  '业务表无 FK（照抄 0023「无业务表 FK」先例）：存在性由编排函数内的资金腿（0015:670/672-673）保证。';


-- ============================================================================
-- §B append-only 守卫（手法逐字同 0023:114-127 / 0007:67-71 / 0016:313）
-- ============================================================================
CREATE OR REPLACE FUNCTION public.admin_refund_audit_log_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'admin_refund_audit_log is append-only: % forbidden (log_id=%)',
        TG_OP, COALESCE(OLD.log_id, 0);
END $$;

COMMENT ON FUNCTION public.admin_refund_audit_log_append_only() IS
  'P7-B：审计表 append-only（BEFORE UPDATE OR DELETE 无条件 RAISE，原生 P0001，不借账本错误码 ⇒ 不建账本类对象）。只由迁移创建；体内无 DDL。诚实边界：不拦 TRUNCATE / DISABLE TRIGGER USER（同 DL65）。';

DROP TRIGGER IF EXISTS trg_admin_refund_audit_log_append_only ON public.admin_refund_audit_log;
CREATE TRIGGER trg_admin_refund_audit_log_append_only
  BEFORE UPDATE OR DELETE ON public.admin_refund_audit_log
  FOR EACH ROW EXECUTE FUNCTION public.admin_refund_audit_log_append_only();

-- 索引齐（= 0023 的 idx×4 同款：PK 索引 + idem 唯一索引由约束自带）：
--   · `admin_refund_audit_log_actor_day_idx` —— 按发起人 + 时间检索（将来额度判据路径）；
--   · `admin_refund_audit_log_order_idx`     —— 按订单轴检索（谁退过这单）。
CREATE INDEX IF NOT EXISTS admin_refund_audit_log_actor_day_idx
  ON public.admin_refund_audit_log (actor_uid, time_created);
CREATE INDEX IF NOT EXISTS admin_refund_audit_log_order_idx
  ON public.admin_refund_audit_log (order_id);


-- ============================================================================
-- §C 唯一资金写路径编排函数（Z4；同构 `admin_points_adjust_post_event`）
-- ============================================================================
-- 调用方**一条语句**：`SELECT public.listing_refund_post_event($1::jsonb)`
--   （经 `DatabaseService.listingRefundPostEvent`）。
-- 函数内三段（同一函数、同一条语句 = 一个隐式事务）：
--   ① （无 advisory lock · Z4b）
--   ② 调**既有** `public.listing_post_event(payload)`（`op='refund'`；**函数体一字不改**）
--   ③ 写审计行 `INSERT INTO public.admin_refund_audit_log …`
-- ⇒ **审计行与资金事件同生同灭**（不存在「资金动了而审计没落」或反之）。
--
-- ★ 拒绝面（Z3 / T-2 / §12.12.3）：状态机拒绝（`0015:682-690` 的
--   `ledger_raise('LEDGER_CURRENCY_INVALID_TRANSITION', …)` = SQLSTATE `LD011`）由**子事务**捕获；
--   白名单 = `reason ∈ {order_not_refundable, order_pay_missing}` ⇒ 写 `result='rejected_state'`
--   审计行（**落在 EXCEPTION 处理器内** ⇒ 子事务回滚**不波及**它）+ 返回拒收回执。
--   **只捕 `LD011` 一类**（严禁 `WHEN OTHERS`）⇒ 其他 SQLSTATE（含 `53300`/`XX000` 基础设施错、
--   `LD022` 404）**保持既有传播**、由既有 §14 分类器映射。
-- ★ 本函数体内**无任何** `RAISE`（异常会回滚同函数内已写的拒绝留痕行）。
-- ★ 本函数体内**不得出现** `purchase_refund` 字面量（AC-12：防双真源）。
CREATE OR REPLACE FUNCTION public.listing_refund_post_event(payload jsonb) RETURNS jsonb
LANGUAGE plpgsql AS $$
DECLARE
  v_actor     bigint := (payload->>'actor_uid')::bigint;
  v_fp        text   := payload->>'request_fingerprint';
  v_memo      text   := COALESCE(NULLIF(payload->>'memo', ''), 'listing refund');
  v_order_id  bigint := public.ledger_int_amount(COALESCE(payload->>'order_id', ''), 'order_id');
  v_key       text   := 'biz:listing:refund:' || v_order_id::text;
  v_envelope  jsonb;
  v_ledger    jsonb;
  v_txid      text;
  v_replay    boolean := false;
  v_seller    bigint;
  v_buyer     bigint;
  v_cid       bigint;
  v_amount    bigint;
  v_audited   boolean := false;
  v_detail    text;
  v_reason    text;
BEGIN
  -- ---------------------------------------------------------------- ② 资金事件（既有账本函数；同一语句内）
  -- **信封逐字同改接前的服务层 payload**（`op` / `order_id` / `request_fingerprint` / `memo`）；
  -- 金额 / 对手方 / 幂等键 / 状态机一律由 `listing_post_event`（`0015`）服务端取数 ⇒ 本函数
  -- **不派生任何分录、不构造任何资金腿**。
  v_envelope := jsonb_build_object(
    'op',                  'refund',
    'order_id',            v_order_id::text,
    'request_fingerprint', v_fp,
    'memo',                v_memo);

  BEGIN
    v_ledger := public.listing_post_event(v_envelope);
  EXCEPTION WHEN SQLSTATE 'LD011' THEN
    -- ★ 白名单式捕获（严禁兜底类子句）：只认「状态机拒绝」那两种 reason。
    --   `reason` 的载体 = `ledger_raise` 的 `DETAIL`（`0004:148`）；读取手法照抄 `0004:1094`。
    --   用正则取值（**不用** JSON 解析 ⇒ 无需任何兜底类子句）。
    GET STACKED DIAGNOSTICS v_detail = PG_EXCEPTION_DETAIL;
    v_reason := substring(v_detail from '"reason"[[:space:]]*:[[:space:]]*"([^"]*)"');

    IF v_reason IN ('order_not_refundable', 'order_pay_missing') THEN
      -- 审计行取值 = **订单行服务端取数**（§12.11.3；拒绝行无资金回执）。
      -- 资金腿已随子事务回滚 ⇒ **零资金残留**；本插入在处理器内 ⇒ **不受该回滚波及**。
      SELECT o.seller_uid, o.buyer_uid, o.cid, (o.price * o.quantity)::bigint
        INTO v_seller, v_buyer, v_cid, v_amount
        FROM public.listing_order AS o
       WHERE o.order_id = v_order_id;

      IF FOUND THEN
        INSERT INTO public.admin_refund_audit_log
          (actor_uid, order_id, seller_uid, buyer_uid, cid, amount,
           result, txid, idempotency_key, request_fingerprint, memo)
        VALUES
          (v_actor, v_order_id, v_seller, v_buyer, v_cid, v_amount,
           'rejected_state', NULL, v_key, v_fp, v_reason)
        ON CONFLICT (idempotency_key, result) DO NOTHING;

        RETURN jsonb_build_object(
          'ok', false, 'order_id', v_order_id::text, 'reason', v_reason,
          'status_field', 'listing_order.status',
          'txid', NULL, 'idempotent_replay', false,
          'audit_logged', true, 'result', 'rejected_state');
      END IF;
    END IF;

    -- 非白名单 `LD011`（例如币种状态位拒绝 `{cid,from,to}`）/ 订单行缺失：
    -- **不写审计行**（Z3 射程 = 白名单状态位拒绝），只回**未被拒收回执** ⇒ 由路由映射既有 `409`。
    RETURN jsonb_build_object(
      'ok', false, 'order_id', v_order_id::text, 'reason', v_reason,
      'status_field', 'listing_order.status',
      'txid', NULL, 'idempotent_replay', false,
      'audit_logged', false, 'result', NULL);
  END;

  v_txid   := v_ledger->>'txid';
  v_replay := COALESCE((v_ledger->>'idempotent_replay')::boolean, false);

  -- ---------------------------------------------------------------- ③ 审计行（与资金同函数、同语句）
  -- DL144① 同精神：**重放 ⇒ 不写第二行审计**（同时被 `admin_refund_audit_log_idem_uniq` 兜住）。
  IF NOT v_replay THEN
    -- 取值 = **资金回执**（服务端取数；不重复读订单行 ⇒ 审计与资金**同源**）：
    --   卖方腿 = 负 delta 那条；买方腿 = 正 delta 那条；金额 = |delta|。
    SELECT (e->>'uid')::bigint, (e->>'cid')::bigint, (-((e->>'delta')::bigint))
      INTO v_seller, v_cid, v_amount
      FROM jsonb_array_elements(v_ledger->'entries') AS t(e)
     WHERE (e->>'delta')::bigint < 0
     LIMIT 1;
    SELECT (e->>'uid')::bigint
      INTO v_buyer
      FROM jsonb_array_elements(v_ledger->'entries') AS t(e)
     WHERE (e->>'delta')::bigint > 0
     LIMIT 1;

    -- `idempotency_key` = 资金事件根键**逐字**（直接取回执字段，不自行拼接）。
    v_key := COALESCE(v_ledger->>'ledger_idempotency_key', v_key);

    INSERT INTO public.admin_refund_audit_log
      (actor_uid, order_id, seller_uid, buyer_uid, cid, amount,
       result, txid, idempotency_key, request_fingerprint, memo)
    VALUES
      (v_actor, v_order_id, v_seller, v_buyer, v_cid, v_amount,
       'applied', v_txid::bigint, v_key, v_fp, v_memo);
    v_audited := true;
  END IF;

  RETURN jsonb_build_object(
    'ok', true, 'order_id', v_order_id::text,
    'txid', v_txid, 'idempotent_replay', v_replay,
    'audit_logged', v_audited, 'result', 'applied',
    'refund_receipt', v_ledger);
END $$;

COMMENT ON FUNCTION public.listing_refund_post_event(jsonb) IS
  'P7-B（Z4 / Z4b / T-2；硬约束 = 防双真源）：§7-32「管理员退款发起」的**唯一资金写路径**。同一函数 / 同一语句内完成「调**既有** public.listing_post_event(op=''refund'')（**复用资金腿**：purchase_refund ×2 / 金额服务端取数 / 不回滚库存全在 0015）→ 写 public.admin_refund_audit_log」⇒ **审计行与资金事件同生同灭**。**不取 pg_advisory_xact_lock**（Z4b；同订单串行性由 0015:670 的 FOR UPDATE 行锁承担）。拒绝面 = 子事务内捕获 SQLSTATE ''LD011'' 且 reason ∈ {order_not_refundable, order_pay_missing}（白名单；严禁兜底类子句）⇒ 写 result=''rejected_state'' 审计行（落在 EXCEPTION 处理器内 ⇒ 子事务回滚不波及）+ 返回拒收回执，由路由映射 409 LD011。**本函数体内无任何 RAISE**、**无 purchase_refund 字面量**、**无 WHEN OTHERS**。同键重投 ⇒ ON CONFLICT (idempotency_key, result) DO NOTHING。';


-- ============================================================================
-- §D apply-time 自检（DL48：不通过则整迁移回滚、**不写版本行**）
-- ============================================================================
DO $$
DECLARE
  v_names   text;
  v_n       int;
  v_trg     int;
  v_covers  int;
  v_def     text;
  v_def_lpe text;
BEGIN
  -- ---------------------------------------------------------------- 结构：审计表在场
  IF to_regclass('public.admin_refund_audit_log') IS NULL THEN
    RAISE EXCEPTION '0024 self-check FAILED: public.admin_refund_audit_log missing';
  END IF;

  -- 13 列，逐名（T-1 变体①：12 语义列 + log_id 结构列）
  SELECT string_agg(column_name, ',' ORDER BY ordinal_position) INTO v_names
    FROM information_schema.columns
   WHERE table_schema = 'public' AND table_name = 'admin_refund_audit_log';
  IF v_names <> 'log_id,actor_uid,order_id,seller_uid,buyer_uid,cid,amount,result,txid,idempotency_key,request_fingerprint,memo,time_created' THEN
    RAISE EXCEPTION '0024 self-check FAILED: admin_refund_audit_log columns = %', v_names;
  END IF;

  -- 具名约束齐：PK×1 / FK×4 / CHECK×2 / UNIQUE×1
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.admin_refund_audit_log'::regclass AND contype = 'p';
  IF v_n <> 1 THEN RAISE EXCEPTION '0024 self-check FAILED: audit PK count = %', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.admin_refund_audit_log'::regclass AND contype = 'f';
  IF v_n <> 4 THEN RAISE EXCEPTION '0024 self-check FAILED: audit FK count = % (expect 4: actor/seller/buyer/cid)', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.admin_refund_audit_log'::regclass AND contype = 'c' AND conname LIKE 'admin_refund_audit_log_%_ck';
  IF v_n <> 2 THEN RAISE EXCEPTION '0024 self-check FAILED: audit CHECK count = % (expect 2)', v_n; END IF;
  -- `result` 闭集逐字 = {applied, rejected_state}（渲染无关的归一化比对：去空白 + 去 ::text 修饰）
  IF replace(replace(COALESCE((SELECT pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid='public.admin_refund_audit_log'::regclass AND conname='admin_refund_audit_log_result_ck'), '<none>'), ' ', ''), '::text', '')
     <> 'CHECK((result=ANY(ARRAY[''applied'',''rejected_state''])))' THEN
    RAISE EXCEPTION '0024 self-check FAILED: result 闭集不是 {applied, rejected_state}，实际=%',
      (SELECT COALESCE(pg_get_constraintdef(oid), '<none>') FROM pg_constraint
        WHERE conrelid='public.admin_refund_audit_log'::regclass AND conname='admin_refund_audit_log_result_ck');
  END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.admin_refund_audit_log'::regclass AND contype = 'u' AND conname = 'admin_refund_audit_log_idem_uniq';
  IF v_n <> 1 THEN RAISE EXCEPTION '0024 self-check FAILED: audit idempotency UNIQUE missing'; END IF;
  -- 唯一键必须是**复合** `(idempotency_key, result)`（恰两列、非部分索引）
  IF (SELECT pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid='public.admin_refund_audit_log'::regclass AND conname='admin_refund_audit_log_idem_uniq')
     <> 'UNIQUE (idempotency_key, result)' THEN
    RAISE EXCEPTION '0024 self-check FAILED: audit idem UNIQUE 非复合 (idempotency_key, result)，实际=%',
      (SELECT COALESCE(pg_get_constraintdef(oid), '<none>') FROM pg_constraint
        WHERE conrelid='public.admin_refund_audit_log'::regclass AND conname='admin_refund_audit_log_idem_uniq');
  END IF;
  SELECT count(*) INTO v_n
    FROM pg_index i JOIN pg_class ic ON ic.oid = i.indexrelid
   WHERE i.indrelid = 'public.admin_refund_audit_log'::regclass
     AND i.indisunique AND NOT i.indisprimary
     AND ic.relname = 'admin_refund_audit_log_idem_uniq'
     AND i.indnkeyatts = 2 AND i.indpred IS NULL
     AND pg_get_indexdef(i.indexrelid) LIKE '%(idempotency_key, result)%';
  IF v_n <> 1 THEN RAISE EXCEPTION '0024 self-check FAILED: 复合唯一索引 (idempotency_key, result) 不在场 (count=%)', v_n; END IF;

  -- 索引齐：PK + idem_uniq + actor_day_idx + order_idx ≥ 4
  SELECT count(*) INTO v_n FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'admin_refund_audit_log';
  IF v_n < 4 THEN RAISE EXCEPTION '0024 self-check FAILED: audit index count = % (expect >= 4)', v_n; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='admin_refund_audit_log'
                   AND indexname='admin_refund_audit_log_actor_day_idx') THEN
    RAISE EXCEPTION '0024 self-check FAILED: admin_refund_audit_log_actor_day_idx missing';
  END IF;

  -- append-only：恰好 1 个启用触发器，且覆盖 UPDATE OR DELETE
  SELECT count(*) INTO v_trg FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relname = 'admin_refund_audit_log' AND NOT t.tgisinternal AND t.tgenabled = 'O';
  IF v_trg <> 1 THEN RAISE EXCEPTION '0024 self-check FAILED: audit enabled triggers = %, expect 1', v_trg; END IF;
  SELECT count(*) INTO v_covers FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relname = 'admin_refund_audit_log' AND NOT t.tgisinternal
     AND (t.tgtype & 2) <> 0 AND (t.tgtype & 8) <> 0 AND (t.tgtype & 16) <> 0;
  IF v_covers <> 1 THEN RAISE EXCEPTION '0024 self-check FAILED: append-only trigger must cover UPDATE OR DELETE'; END IF;

  -- 编排函数在场 + 返回类型 + 关键机体（复用资金路径 / 审计插入 / 白名单捕获）
  IF to_regprocedure('public.listing_refund_post_event(jsonb)') IS NULL THEN
    RAISE EXCEPTION '0024 self-check FAILED: listing_refund_post_event(jsonb) missing';
  END IF;
  SELECT count(*) INTO v_n FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE n.nspname = 'public' AND p.proname = 'listing_refund_post_event'
     AND pg_get_function_identity_arguments(p.oid) = 'payload jsonb' AND pg_get_function_result(p.oid) = 'jsonb';
  IF v_n <> 1 THEN RAISE EXCEPTION '0024 self-check FAILED: listing_refund_post_event 签名/返回类型不是 (payload jsonb)->jsonb'; END IF;

  SELECT pg_get_functiondef(p.oid) INTO v_def FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE n.nspname = 'public' AND p.proname = 'listing_refund_post_event';
  IF v_def IS NULL THEN RAISE EXCEPTION '0024 self-check FAILED: listing_refund_post_event not found in public'; END IF;

  -- ★ Z4 硬约束（防双真源）：必须复用既有资金路径；**不得**出现资金腿字面量（AC-12）
  IF position('listing_post_event' IN v_def) = 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 编排函数未复用 listing_post_event（Z4 硬约束：复用资金路径）';
  END IF;
  -- ★ 加严（本单）：必须是**调用**（`public.listing_post_event(`），不只是注释里提到名字
  IF position('public.listing_post_event(' IN v_def) = 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 编排函数体内无对既有资金路径的**调用**（public.listing_post_event(）';
  END IF;
  IF position('purchase_refund' IN v_def) <> 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 编排函数体内出现 purchase_refund 字面量（复制退款资金腿 = 第二真源；AC-12）';
  END IF;
  IF position('admin_refund_audit_log' IN v_def) = 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 编排函数体内未压进审计插入（同函数、同一次 DB 调用）';
  END IF;
  -- ★ Z3① / T-2：**无 RAISE**（异常会回滚同函数内已写的拒绝留痕行）
  IF position('RAISE' IN v_def) <> 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 编排函数体内出现 RAISE（Z3①：异常会回滚已写的拒绝留痕行）';
  END IF;
  -- ★ §12.12.3①：白名单式捕获 —— 必须有捕获块、必须捕 LD011；**严禁 WHEN OTHERS**
  IF position('EXCEPTION' IN v_def) = 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 编排函数体内无捕获块（T-2 变体①）';
  END IF;
  IF position('LD011' IN v_def) = 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 编排函数体内无 LD011 白名单（T-2 / §12.12.3①）';
  END IF;
  IF position('WHEN OTHERS' IN v_def) <> 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 编排函数体内出现兜底类捕获子句（AC-14：会把基础设施错吞成「被拒」）';
  END IF;
  IF position('PG_EXCEPTION_DETAIL' IN v_def) = 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 编排函数体内未读取 PG_EXCEPTION_DETAIL（reason 载体）';
  END IF;
  IF position('rejected_state' IN v_def) = 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 编排函数体内无拒绝留痕分支（result = rejected_state）';
  END IF;
  -- ★ Z4b：不取 advisory lock
  IF position('pg_advisory' IN v_def) <> 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 编排函数体内出现 pg_advisory（Z4b：本批不取 advisory lock）';
  END IF;
  -- 幂等键字面量：编排函数与既有资金函数**同一格式串**（防「自造键」漂移）
  IF position('biz:listing:refund:' IN v_def) = 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 编排函数体内无资金事件根键格式串 biz:listing:refund:';
  END IF;
  SELECT pg_get_functiondef(p.oid) INTO v_def_lpe FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE n.nspname = 'public' AND p.proname = 'listing_post_event';
  IF position('biz:listing:refund:' IN COALESCE(v_def_lpe, '')) = 0 THEN
    RAISE EXCEPTION '0024 self-check FAILED: 被调方 listing_post_event 内无资金事件根键格式串（指纹漂移守卫）';
  END IF;

  IF to_regprocedure('public.admin_refund_audit_log_append_only()') IS NULL THEN
    RAISE EXCEPTION '0024 self-check FAILED: admin_refund_audit_log_append_only() missing';
  END IF;

  -- 指纹守卫：`listing_post_event` 签名/返回类型未变（**只新增调用方、不改被调方**）
  SELECT count(*) INTO v_n FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE n.nspname = 'public' AND p.proname = 'listing_post_event'
     AND pg_get_function_identity_arguments(p.oid) = 'payload jsonb' AND pg_get_function_result(p.oid) = 'jsonb';
  IF v_n <> 1 THEN RAISE EXCEPTION '0024 self-check FAILED: listing_post_event fingerprint changed'; END IF;

  -- ★ 既有迁移链指纹未变（0022 / 0023 的版本行在场 ⇒ 本迁移**未改写**上游）
  SELECT count(*) INTO v_n FROM public.schema_migration WHERE version IN ('0022', '0023');
  IF v_n <> 2 THEN RAISE EXCEPTION '0024 self-check FAILED: upstream migration rows 0022/0023 = % (expect 2)', v_n; END IF;

  RAISE NOTICE '0024 self-check OK: admin_refund_audit_log 13 cols / PK×1 FK×4 CHECK×2 UNIQUE×1 / idx×4 / trg×1(O,UPDATE|DELETE) / listing_refund_post_event(jsonb) 在场（复用 listing_post_event + 审计 insert + LD011 白名单捕获[无兜底子句] + 无 RAISE + 无 purchase_refund + 无 advisory lock）/ listing_post_event 指纹不变';
END $$;
