-- 0025_currency_review_log.sql
-- ============================================================================
-- 批 8 第 4 片（8④）· 自建单位审核闸（变体 Ⅱ = 旁路台账型）· 审核台账表（Kong）
-- ============================================================================
-- 上游：`0024_admin_refund_audit.sql`。**不改 `0001`–`0024` 任何字节。**
--
-- 契约真源（已冻结 · 逐字遵守 · 不得改写）：
--   · `docs/data-layer.spec.md` **v0.15 §26.7 `★ 迁移内容契约`** —— 表名 / 8 列 / 5 约束 /
--     4 索引 / append-only 手法 / `time_created`（每项逐一溯源自 `0023`/`0024`/`0017` 先例）；
--   · 同册 §26.3（载体 = append-only 台账）、§26.4（留痕：通过 ⇒ 台账 + `draft→listed` +
--     `currency_status_log`；驳回 ⇒ 必须落台账、`currency.status` 不动、不写状态日志）、
--     §26.8（FK 引用关系）。
--   · 姊妹册 `docs/route-layer.spec.md` **v2.8 §23**（读口 / 动作口 / 注册点 69→70→71 / 权限键 /
--     后台页契约）—— **本文件只承载数据侧**（表 + append-only + 索引 + 自检）。
--
-- ★★ 本文件硬约束（逐字 · 派单口径）：
--   · **只新建、不 apply**（apply 由 Zang 执行，参照 `0024` 流程）；本文件**不含任何
--     `INSERT/UPDATE/DELETE` 数据行**、**不改任何既有迁移 / 既有表**（零 `ALTER`）。
--   · **不发明列名 / 类型 / 约束 / 索引 / 数值**：逐字照 §26.7；每列 / 每约束 / 每索引后带
--     `文件:行` 先例锚（`0023` / `0024` / `0017`）。
--   · **幂等 / 可重放**：`CREATE TABLE IF NOT EXISTS` / `CREATE OR REPLACE FUNCTION` /
--     `DROP TRIGGER IF EXISTS` + `CREATE TRIGGER` / `CREATE INDEX IF NOT EXISTS`（承 `0017`/`0023`/`0024`）。
--   · **自带 apply-time 自检**（`DL48`：不通过则整迁移回滚、**不写版本行**）。
--   · `result` 闭集值域 `{'pending','approved','rejected'}` = `R-8-21` 逐字给定（**非本单发明**）。
--   · append-only 触发器 `BEFORE UPDATE OR DELETE` **无条件 `RAISE`**（原生 `P0001`，
--     **不借账本错误码** ⇒ 不建账本类对象）；手法逐字照抄 `0017:236-239` / `0023:112-127`。
--   · **无 `create_key` / 无 `ledger_event_keys` / 无 `time_updated`**（照抄 `0023`/`0024` 审计表
--     格局 + `0017:297` 反断言 + `DL156` 精神；§26.7(e)(f)）。
--   · **诚实边界**：append-only 触发器不拦 `TRUNCATE` / `DISABLE TRIGGER USER`（同 `0017` / `0023`）。
-- ============================================================================


-- ============================================================================
-- §A `public.currency_review_log`（审核台账 · append-only · 逐列照 §26.7(b)）
-- ============================================================================
-- 命名依据（§26.7(a)）：承同资源同后缀先例 `public.currency_status_log`（`0017:139`）⇒
--   资源词 `currency` + append-only 台账后缀 `_log`（`currency_status_log` /
--   `admin_ops_audit_log`（`0023:64`）/ `admin_refund_audit_log`（`0024:50`））。
-- 与既有 `currency_status_log` 的分工（§26.3）：本表 = 「**审核动作**」留痕
--   （`pending`/`approved`/`rejected`）；`currency_status_log` = 「**状态迁移**」留痕
--   （仍只记 `draft → listed` 一条边）。两者职责不重叠。
CREATE TABLE IF NOT EXISTS public.currency_review_log (
  log_id              bigint      GENERATED BY DEFAULT AS IDENTITY,          -- 0023:65 / 0024:54 / 0017:140（身份证 PK 先例）
  cid                 bigint      NOT NULL,                                   -- 0023:71 / 0017:141
  actor_uid           bigint      NOT NULL,                                   -- 0023:66 / 0024:55 / 0017:144（发起人 uid；token 侧；不得由客户端声明）
  result              text        NOT NULL,                                   -- 0023:78 / 0024:60（结论位手法；值域 = 下方 CHECK）
  request_fingerprint text        NOT NULL,                                   -- 0023:76 / 0024:58（DL96；服务端派生）
  idempotency_key     text        NOT NULL,                                   -- 0023:77 / 0024:57（DL146② / DL36 的 `ops:` 系）
  memo                text,                                                   -- 0017:145 / 0023:80 / 0024:61（驳回 = reason；可空）
  time_created        timestamptz NOT NULL DEFAULT now(),                     -- 0023:81 / 0024:62 / 0017:146（DB 生成，不得客户端传）
  CONSTRAINT currency_review_log_pk        PRIMARY KEY (log_id),                                         -- 0023:82 / 0024:64
  CONSTRAINT currency_review_log_actor_fk  FOREIGN KEY (actor_uid) REFERENCES public.users(uid),          -- 0023:83 / 0024:66
  CONSTRAINT currency_review_log_cid_fk    FOREIGN KEY (cid)       REFERENCES public.currency(cid),       -- 0023:85 / 0024:68
  CONSTRAINT currency_review_log_result_ck CHECK (result IN ('pending', 'approved', 'rejected')),         -- 0023:89（result 闭集手法）；值域 = R-8-21 给定（非本单发明）
  -- ★ 沿用 `0023` 裁定四（「幂等键的语义约束**效果**、不约束**尝试**」）：
  --   同键同 `result` 重投 ⇒ `(key, result)` 冲突 ⇒ `DO NOTHING`（幂等重放，拒绝行不放大）；
  --   同键异 `result`（先驳后成 / 先成后驳）⇒ 允许，各留一行（§23.3(a) / §26.7(c)）。
  CONSTRAINT currency_review_log_idem_uniq UNIQUE (idempotency_key, result)                               -- 0023:99 / 0024:72
);

COMMENT ON TABLE public.currency_review_log IS
  '批 8④（Kong；依据 data-layer.spec v0.15 §26.7 + route-layer.spec v2.8 §23）：自建单位（currency）**审核动作的旁路台账**（变体 Ⅱ）。列风格 / 约束命名 / 索引形态 / append-only 手法照抄 0023 的 admin_ops_audit_log。**只增不删**：BEFORE UPDATE OR DELETE 无条件 RAISE。actor_uid FK users(uid)、cid FK currency(cid)。**成功行（approved）与拒绝行（rejected）同表**（result 闭集 = {pending, approved, rejected}）。**与既有 currency_status_log 分工不重叠**：本表记「审核动作」，后者记「状态迁移」。**零 ALTER 既有表**。诚实边界：append-only 触发器不拦 TRUNCATE / DISABLE TRIGGER USER（同 0017 / 0023）。';

COMMENT ON COLUMN public.currency_review_log.result IS
  '结论位（R-8-21 给定的三态值域）。''pending'' = 待审（写入者 / 写入时机 = 待实现单，§26.2(c)）；''approved'' = 审核通过（同事务 currency.status draft→listed + currency_status_log 恰 1 行）；''rejected'' = 审核驳回（currency.status 仍 draft、不写 currency_status_log，但**本行必须落** ⇒ 驳回不得静默）。';
COMMENT ON COLUMN public.currency_review_log.memo IS
  '审核说明 / 原因（= 动作口请求体的 reason）。驳回路径必须携带非空 reason；通过路径可选。';
COMMENT ON COLUMN public.currency_review_log.actor_uid IS
  '审核人 uid（= admin）；**不得记成 owner**（§26.4 写死者）。token 侧取值，不得由客户端声明。';
COMMENT ON COLUMN public.currency_review_log.idempotency_key IS
  '审核动作的 ops: 幂等键，规范形 = ops:<admin_uid>:currency_review:<cid>（DL36 / DL93；键形 = 姊妹册 §23.3）。';
COMMENT ON COLUMN public.currency_review_log.request_fingerprint IS
  '请求指纹（DL96；由路由层按 business 字段集合服务端派生，具体拼接式 = 实现单现取）。';


-- ============================================================================
-- §B append-only 守卫（手法逐字照抄 0017:236-239 / 0023:112-127 / 0024 §B）
-- ============================================================================
CREATE OR REPLACE FUNCTION public.currency_review_log_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'currency_review_log is append-only: % forbidden (log_id=%)',
        TG_OP, COALESCE(OLD.log_id, 0);
END $$;

COMMENT ON FUNCTION public.currency_review_log_append_only() IS
  '批 8④：审核台账 append-only（BEFORE UPDATE OR DELETE 无条件 RAISE，原生 P0001，不借账本错误码 ⇒ 不建账本类对象）。只由迁移创建；体内无 DDL。诚实边界：不拦 TRUNCATE / DISABLE TRIGGER USER。';

DROP TRIGGER IF EXISTS trg_currency_review_log_append_only ON public.currency_review_log;
CREATE TRIGGER trg_currency_review_log_append_only
  BEFORE UPDATE OR DELETE ON public.currency_review_log
  FOR EACH ROW EXECUTE FUNCTION public.currency_review_log_append_only();


-- ============================================================================
-- §C 索引（逐条照 §26.7(d) · 0023:133-136 手法）
-- ============================================================================
-- PK 索引与 `currency_review_log_idem_uniq` 唯一索引由约束自带 ⇒ 连同下列 2 个具名索引共 4 个：
--   · `currency_review_log_cid_idx`       —— 按**单位**轴 + 时间检索（某单位的审核历史）；
--   · `currency_review_log_actor_day_idx` —— 按**审核人** + 时间检索。
CREATE INDEX IF NOT EXISTS currency_review_log_cid_idx
  ON public.currency_review_log (cid, time_created);
CREATE INDEX IF NOT EXISTS currency_review_log_actor_day_idx
  ON public.currency_review_log (actor_uid, time_created);


-- ============================================================================
-- §D apply-time 自检（DL48：不通过则整迁移回滚、**不写版本行**）
-- ============================================================================
DO $$
DECLARE
  v_names  text;
  v_n      int;
  v_trg    int;
  v_covers int;
BEGIN
  -- ---------------------------------------------------------------- 结构：台账表在场
  IF to_regclass('public.currency_review_log') IS NULL THEN
    RAISE EXCEPTION '0025 self-check FAILED: public.currency_review_log missing';
  END IF;

  -- 8 列，逐名（§26.7(b) 逐字顺序；只增不删：名字齐全即通过）
  SELECT string_agg(column_name, ',' ORDER BY ordinal_position) INTO v_names
    FROM information_schema.columns
   WHERE table_schema = 'public' AND table_name = 'currency_review_log';
  IF v_names <> 'log_id,cid,actor_uid,result,request_fingerprint,idempotency_key,memo,time_created' THEN
    RAISE EXCEPTION '0025 self-check FAILED: currency_review_log columns = % (expect 8)', v_names;
  END IF;

  -- 具名约束齐：PK×1 / FK×2 / CHECK×1 / UNIQUE×1
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.currency_review_log'::regclass AND contype = 'p';
  IF v_n <> 1 THEN RAISE EXCEPTION '0025 self-check FAILED: ledger PK count = %', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.currency_review_log'::regclass AND contype = 'f';
  IF v_n <> 2 THEN RAISE EXCEPTION '0025 self-check FAILED: ledger FK count = % (expect 2: actor/cid)', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.currency_review_log'::regclass AND contype = 'c' AND conname LIKE 'currency_review_log_%_ck';
  IF v_n <> 1 THEN RAISE EXCEPTION '0025 self-check FAILED: ledger CHECK count = % (expect 1)', v_n; END IF;
  -- `result` 闭集逐字 = {pending, approved, rejected}（渲染无关的归一化比对）
  IF replace(replace(COALESCE((SELECT pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid='public.currency_review_log'::regclass AND conname='currency_review_log_result_ck'), '<none>'), ' ', ''), '::text', '')
     <> 'CHECK((result=ANY(ARRAY[''pending'',''approved'',''rejected''])))' THEN
    RAISE EXCEPTION '0025 self-check FAILED: result 闭集不是 {pending, approved, rejected}，实际=%',
      (SELECT COALESCE(pg_get_constraintdef(oid), '<none>') FROM pg_constraint
        WHERE conrelid='public.currency_review_log'::regclass AND conname='currency_review_log_result_ck');
  END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.currency_review_log'::regclass AND contype = 'u' AND conname = 'currency_review_log_idem_uniq';
  IF v_n <> 1 THEN RAISE EXCEPTION '0025 self-check FAILED: ledger idempotency UNIQUE missing'; END IF;
  -- 唯一键必须是**复合** `(idempotency_key, result)`（恰两列、非部分索引）
  IF (SELECT pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid='public.currency_review_log'::regclass AND conname='currency_review_log_idem_uniq')
     <> 'UNIQUE (idempotency_key, result)' THEN
    RAISE EXCEPTION '0025 self-check FAILED: ledger idem UNIQUE 非复合 (idempotency_key, result)，实际=%',
      (SELECT COALESCE(pg_get_constraintdef(oid), '<none>') FROM pg_constraint
        WHERE conrelid='public.currency_review_log'::regclass AND conname='currency_review_log_idem_uniq');
  END IF;
  SELECT count(*) INTO v_n
    FROM pg_index i JOIN pg_class ic ON ic.oid = i.indexrelid
   WHERE i.indrelid = 'public.currency_review_log'::regclass
     AND i.indisunique AND NOT i.indisprimary
     AND ic.relname = 'currency_review_log_idem_uniq'
     AND i.indnkeyatts = 2 AND i.indpred IS NULL
     AND pg_get_indexdef(i.indexrelid) LIKE '%(idempotency_key, result)%';
  IF v_n <> 1 THEN RAISE EXCEPTION '0025 self-check FAILED: 复合唯一索引 (idempotency_key, result) 不在场 (count=%)', v_n; END IF;

  -- 索引齐：PK + idem_uniq + cid_idx + actor_day_idx ≥ 4
  SELECT count(*) INTO v_n FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'currency_review_log';
  IF v_n < 4 THEN RAISE EXCEPTION '0025 self-check FAILED: ledger index count = % (expect >= 4)', v_n; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='currency_review_log'
                   AND indexname='currency_review_log_cid_idx') THEN
    RAISE EXCEPTION '0025 self-check FAILED: currency_review_log_cid_idx missing';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='currency_review_log'
                   AND indexname='currency_review_log_actor_day_idx') THEN
    RAISE EXCEPTION '0025 self-check FAILED: currency_review_log_actor_day_idx missing';
  END IF;

  -- append-only：恰好 1 个启用触发器，且覆盖 UPDATE OR DELETE
  SELECT count(*) INTO v_trg FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relname = 'currency_review_log' AND NOT t.tgisinternal AND t.tgenabled = 'O';
  IF v_trg <> 1 THEN RAISE EXCEPTION '0025 self-check FAILED: ledger enabled triggers = %, expect 1', v_trg; END IF;
  SELECT count(*) INTO v_covers FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relname = 'currency_review_log' AND NOT t.tgisinternal
     AND (t.tgtype & 2) <> 0 AND (t.tgtype & 8) <> 0 AND (t.tgtype & 16) <> 0;
  IF v_covers <> 1 THEN RAISE EXCEPTION '0025 self-check FAILED: append-only trigger must cover UPDATE OR DELETE'; END IF;

  IF to_regprocedure('public.currency_review_log_append_only()') IS NULL THEN
    RAISE EXCEPTION '0025 self-check FAILED: currency_review_log_append_only() missing';
  END IF;

  -- ★ 反断言（§26.7(e)(f)）：本表**无 `time_updated`**、**无 `create_key`**、**无 `ledger_event_keys`**
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public'
               AND table_name='currency_review_log' AND column_name IN ('time_updated','create_key','ledger_event_keys')) THEN
    RAISE EXCEPTION '0025 self-check FAILED: 台账表出现 time_updated / create_key / ledger_event_keys（违 §26.7(e)(f)）';
  END IF;

  -- ★ 零 ALTER 既有表：既有 `currency` / `currency_status_log` 结构指纹未变（列数与列名）
  IF (SELECT string_agg(column_name, ',' ORDER BY ordinal_position) FROM information_schema.columns
        WHERE table_schema='public' AND table_name='currency_status_log')
     <> 'log_id,cid,from_status,to_status,actor_uid,memo,time_created' THEN
    RAISE EXCEPTION '0025 self-check FAILED: currency_status_log 列指纹变化（本迁移应零 ALTER 既有表）';
  END IF;

  -- ★ 既有迁移链指纹未变（0023 / 0024 的版本行在场 ⇒ 本迁移**未改写**上游）
  SELECT count(*) INTO v_n FROM public.schema_migration WHERE version IN ('0023', '0024');
  IF v_n <> 2 THEN RAISE EXCEPTION '0025 self-check FAILED: upstream migration rows 0023/0024 = % (expect 2)', v_n; END IF;

  RAISE NOTICE '0025 self-check OK: currency_review_log 8 cols / PK×1 FK×2 CHECK×1 UNIQUE×1 / idx×4(PK+idem_uniq+cid_idx+actor_day_idx) / trg×1(O,UPDATE|DELETE) / 无 time_updated·create_key·ledger_event_keys / currency_status_log 列指纹不变 / upstream 0023/0024 在场';
END $$;
