-- 0026_listing_review_log.sql
-- ============================================================================
-- 批 8 第 5 片（8⑤）· 合规审核（商品）· 审核台账表（Kong）
-- ============================================================================
-- 上游：`0025_currency_review_log.sql`。**不改 `0001`–`0025` 任何字节。**
--
-- 契约真源（已冻结 · 逐字遵守 · 不得改写）：
--   · `docs/data-layer.spec.md` **v0.17 §28.6** `★ 迁移内容契约` —— 表名（§28.6(a)） /
--     **9 列**（§28.6(b)） / 5 约束（§28.6(c)） / 4 索引（§28.6(d)） / append-only 手法（§28.6(e)） /
--     `time_created`（§28.6(f)）；每列 / 每约束 / 每索引**逐字溯源自 `0023`/`0024`/`0025`/`0017` 先例**；
--   · 同册 §28.3（载体 = append-only 台账）、§28.4（留痕：通过 ⇒ 台账行 + 同事务走**既有已白名单边**；
--     驳回 ⇒ **必须落台账、不得静默**、状态不动）、§28.5（回滚与拒绝路径）、§28.7（FK 引用关系）；
--   · 姊妹册 `docs/route-layer.spec.md` **v2.10 §25**（读口 / 动作口 / 注册点 71→75 / 权限键 /
--     归属闸 / 后台页契约）—— **本文件只承载数据侧**（表 + append-only + 索引 + 自检）。
--
-- ★★ 本文件硬约束（逐字 · 派单口径）：
--   · **只新建、不 apply**（apply 由 Zang 执行，参照 `0025` 流程）；本文件**不含任何
--     `INSERT/UPDATE/DELETE` 数据行**、**不改任何既有迁移 / 既有表**（零 `ALTER`）。
--   · **不发明列名 / 类型 / 约束 / 索引 / 数值**：逐字照 §28.6；每列 / 每约束 / 每索引后带
--     `文件:行` 先例锚（`0023` / `0024` / `0025` / `0017` / `0015`）。
--   · **幂等 / 可重放**：`CREATE TABLE IF NOT EXISTS` / `CREATE OR REPLACE FUNCTION` /
--     `DROP TRIGGER IF EXISTS` + `CREATE TRIGGER` / `CREATE INDEX IF NOT EXISTS`（承 `0017`/`0023`/`0024`/`0025`）。
--   · **自带 apply-time 自检**（`DL48`：不通过则整迁移回滚、**不写版本行**）。
--   · `result` 闭集值域 `{'approved','rejected'}` = `R-8-23②` 逐字给定（**非本单发明**；两值逐字取
--     `0025:54` 的 `result` 闭集子集 —— 8⑤ 无「待审动作」⇒ 不含 `pending`）。
--   · append-only 触发器 `BEFORE UPDATE OR DELETE` **无条件 `RAISE`**（原生 `P0001`，
--     **不借账本错误码** ⇒ 不建账本类对象）；手法逐字照抄 `0017:236-239` / `0023:112-127` / `0025:79-91`。
--   · **无 `create_key` / 无 `ledger_event_keys` / 无 `time_updated`**（照抄 `0023`/`0024`/`0025` 审计表
--     格局 + `0017:297` 反断言 + `DL156` 精神；§28.6(e)(f)）。
--   · **商品下架 / 冻结无账务分录**（`DL59`）⇒ 本轴 `txid` **恒 `NULL`**（对账**显式豁免**；姊妹册 §25.8(c)）。
--   · **诚实边界**：append-only 触发器不拦 `TRUNCATE` / `DISABLE TRIGGER USER`（同 `0017` / `0023` / `0025`）。
-- ============================================================================


-- ============================================================================
-- §A `public.listing_review_log`（商品审核台账 · append-only · 逐列照 §28.6(b)）
-- ============================================================================
-- 命名依据（§28.6(a)）：资源词 `listing`（`R-8-24` 逐字路径族名）+ 台账后缀 `_review_log`
--   （同族先例 = `public.currency_review_log`（`0025:42`）—— 同后缀、同「审核台账」定性）
--   ⇒ `listing_review_log`。与后台页命名空间 `adminListingReview`（§27.6(b)）词根一致。
-- 分工（§28.2(d)）：本表 = 「**审核动作**」留痕（`approved`/`rejected`）；
--   商品**状态迁移**走**既有已白名单边** `listed → delisted` / `listed → frozen`
--   （`0015:83-93` `public.listing_status_transition_ok`）—— **不新增状态值**（`R-8-23③`）。
CREATE TABLE IF NOT EXISTS public.listing_review_log (
  log_id              bigint      GENERATED BY DEFAULT AS IDENTITY,          -- 0023:65 / 0024:49 / 0017:140（身份证 PK 先例）
  listing_id          bigint      NOT NULL,                                   -- 0023:71 / 0017:141（资源键列；本轴 = 商品；同轴先例 = listing_order.listing_id 0015:155）
  actor_uid           bigint      NOT NULL,                                   -- 0023:66 / 0024:50 / 0017:144（动作人 uid；token 侧；不得由客户端声明）
  result              text        NOT NULL,                                   -- 0023:78 / 0024:56（结论位手法；值域 = 下方 CHECK）
  request_fingerprint text        NOT NULL,                                   -- 0023:76 / 0024:59（DL96；服务端派生）
  idempotency_key     text        NOT NULL,                                   -- 0023:77 / 0024:58（DL146② / DL36 的 `ops:` 系）
  txid                bigint,                                                 -- 0023:79 / 0024:57（账本回执 txid；**商品无分录 ⇒ 本轴恒 NULL**，见 DL59）
  memo                text,                                                   -- 0017:145 / 0023:80 / 0024:60（驳回 = reason；可空）
  time_created        timestamptz NOT NULL DEFAULT now(),                     -- 0023:81 / 0024:61 / 0017:146（DB 生成，不得客户端传）
  CONSTRAINT listing_review_log_pk         PRIMARY KEY (log_id),                                              -- 0023:82 / 0024:62
  CONSTRAINT listing_review_log_actor_fk   FOREIGN KEY (actor_uid)  REFERENCES public.users(uid),             -- 0023:83 / 0024:63
  CONSTRAINT listing_review_log_listing_fk FOREIGN KEY (listing_id) REFERENCES public.listing(listing_id),    -- 0015:177（listing_order_listing_fk 同轴照抄）
  CONSTRAINT listing_review_log_result_ck  CHECK (result IN ('approved', 'rejected')),                        -- 0023:89（result 闭集手法）；值域 = R-8-23②（逐字取 0025:54 两值）
  -- ★ 沿用 `0023` 裁定四（「幂等键的语义约束**效果**、不约束**尝试**」）：
  --   同键同 `result` 重投 ⇒ `(key, result)` 冲突 ⇒ `DO NOTHING`（幂等重放，拒绝行不放大）；
  --   同键异 `result`（先驳后成 / 先成后驳）⇒ 允许，各留一行（§25.3）。
  CONSTRAINT listing_review_log_idem_uniq  UNIQUE (idempotency_key, result)                                   -- 0023:99 / 0024:72
);

COMMENT ON TABLE public.listing_review_log IS
  '批 8⑤（Kong；依据 data-layer.spec v0.17 §28.6 + route-layer.spec v2.10 §25）：商品（listing）**审核动作的旁路台账**（变体 Ⅱ）。列风格 / 约束命名 / 索引形态 / append-only 手法照抄 0023 的 admin_ops_audit_log 与 0025 的 currency_review_log。**只增不删**：BEFORE UPDATE OR DELETE 无条件 RAISE。actor_uid FK users(uid)、listing_id FK listing(listing_id)。**成功行（approved）与拒绝行（rejected）同表**（result 闭集 = {approved, rejected}）。商品下架 / 冻结无账务分录（DL59）⇒ txid 恒 NULL（对账显式豁免）。**零 ALTER 既有表**。诚实边界：append-only 触发器不拦 TRUNCATE / DISABLE TRIGGER USER（同 0017 / 0023 / 0025）。';

COMMENT ON COLUMN public.listing_review_log.result IS
  '结论位（R-8-23② 给定的两态值域，逐字取 0025:54 的 approved/rejected）。''approved'' = 审核通过（同事务 listing.status 走**既有已白名单边** listed→delisted / listed→frozen）；''rejected'' = 审核驳回（listing.status **不动**、但**本行必须落** ⇒ 驳回不得静默）。8⑤ 无「待审动作」⇒ 本闭集不含 pending。';
COMMENT ON COLUMN public.listing_review_log.txid IS
  '商品下架 / 冻结**无账务分录**（DL59 ⇒ 商品发布不收费、无「下架」账务动作）⇒ **本轴恒 NULL**，属对账**显式豁免**（姊妹册 §25.8(c)：不得因商品行无 txid 判红）。';
COMMENT ON COLUMN public.listing_review_log.memo IS
  '审核说明 / 原因（= 动作口请求体的 reason）。驳回路径必须携带非空 reason；通过路径可选。';
COMMENT ON COLUMN public.listing_review_log.actor_uid IS
  '审核人 uid（= 持 review_tasks 键的 admin）；**不得记成 seller**（§28.4 写死者）。token 侧取值，不得由客户端声明。';
COMMENT ON COLUMN public.listing_review_log.idempotency_key IS
  '审核动作的 ops: 幂等键，规范形 = ops:<admin_uid>:listing_takedown:<listingId>（DL36 / DL93；键形 = 姊妹册 §25.2）。';
COMMENT ON COLUMN public.listing_review_log.request_fingerprint IS
  '请求指纹（DL96；由路由层按 business 字段集合服务端派生，具体拼接式 = 实现单现取）。';


-- ============================================================================
-- §B append-only 守卫（手法逐字照抄 0017:236-239 / 0023:112-127 / 0025:79-91）
-- ============================================================================
CREATE OR REPLACE FUNCTION public.listing_review_log_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'listing_review_log is append-only: % forbidden (log_id=%)',
        TG_OP, COALESCE(OLD.log_id, 0);
END $$;

COMMENT ON FUNCTION public.listing_review_log_append_only() IS
  '批 8⑤：商品审核台账 append-only（BEFORE UPDATE OR DELETE 无条件 RAISE，原生 P0001，不借账本错误码 ⇒ 不建账本类对象）。只由迁移创建；体内无 DDL。诚实边界：不拦 TRUNCATE / DISABLE TRIGGER USER。';

DROP TRIGGER IF EXISTS trg_listing_review_log_append_only ON public.listing_review_log;
CREATE TRIGGER trg_listing_review_log_append_only
  BEFORE UPDATE OR DELETE ON public.listing_review_log
  FOR EACH ROW EXECUTE FUNCTION public.listing_review_log_append_only();


-- ============================================================================
-- §C 索引（逐条照 §28.6(d) · 0023:133-136 / 0025:101-104 手法）
-- ============================================================================
-- PK 索引与 `listing_review_log_idem_uniq` 唯一索引由约束自带 ⇒ 连同下列 2 个具名索引共 4 个：
--   · `listing_review_log_listing_idx`   —— 按**商品**轴 + 时间检索（某商品的审核历史）；
--   · `listing_review_log_actor_day_idx` —— 按**审核人** + 时间检索。
CREATE INDEX IF NOT EXISTS listing_review_log_listing_idx
  ON public.listing_review_log (listing_id, time_created);
CREATE INDEX IF NOT EXISTS listing_review_log_actor_day_idx
  ON public.listing_review_log (actor_uid, time_created);


-- ============================================================================
-- §D apply-time 自检（DL48：不通过则整迁移回滚、**不写版本行**）
-- ============================================================================
DO $$
DECLARE
  v_names  text;
  v_n      int;
  v_trg    int;
  v_covers int;
BEGIN
  -- ---------------------------------------------------------------- 结构：台账表在场
  IF to_regclass('public.listing_review_log') IS NULL THEN
    RAISE EXCEPTION '0026 self-check FAILED: public.listing_review_log missing';
  END IF;

  -- 9 列，逐名（§28.6(b) 逐字顺序；只增不删：名字齐全即通过）
  SELECT string_agg(column_name, ',' ORDER BY ordinal_position) INTO v_names
    FROM information_schema.columns
   WHERE table_schema = 'public' AND table_name = 'listing_review_log';
  IF v_names <> 'log_id,listing_id,actor_uid,result,request_fingerprint,idempotency_key,txid,memo,time_created' THEN
    RAISE EXCEPTION '0026 self-check FAILED: listing_review_log columns = % (expect 9)', v_names;
  END IF;

  -- 具名约束齐：PK×1 / FK×2 / CHECK×1 / UNIQUE×1
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.listing_review_log'::regclass AND contype = 'p';
  IF v_n <> 1 THEN RAISE EXCEPTION '0026 self-check FAILED: ledger PK count = %', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.listing_review_log'::regclass AND contype = 'f';
  IF v_n <> 2 THEN RAISE EXCEPTION '0026 self-check FAILED: ledger FK count = % (expect 2: actor/listing)', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.listing_review_log'::regclass AND contype = 'c' AND conname LIKE 'listing_review_log_%_ck';
  IF v_n <> 1 THEN RAISE EXCEPTION '0026 self-check FAILED: ledger CHECK count = % (expect 1)', v_n; END IF;
  -- `result` 闭集逐字 = {approved, rejected}（渲染无关的归一化比对）
  IF replace(replace(COALESCE((SELECT pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid='public.listing_review_log'::regclass AND conname='listing_review_log_result_ck'), '<none>'), ' ', ''), '::text', '')
     <> 'CHECK((result=ANY(ARRAY[''approved'',''rejected''])))' THEN
    RAISE EXCEPTION '0026 self-check FAILED: result 闭集不是 {approved, rejected}，实际=%',
      (SELECT COALESCE(pg_get_constraintdef(oid), '<none>') FROM pg_constraint
        WHERE conrelid='public.listing_review_log'::regclass AND conname='listing_review_log_result_ck');
  END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid = 'public.listing_review_log'::regclass AND contype = 'u' AND conname = 'listing_review_log_idem_uniq';
  IF v_n <> 1 THEN RAISE EXCEPTION '0026 self-check FAILED: ledger idempotency UNIQUE missing'; END IF;
  -- 唯一键必须是**复合** `(idempotency_key, result)`（恰两列、非部分索引）
  IF (SELECT pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid='public.listing_review_log'::regclass AND conname='listing_review_log_idem_uniq')
     <> 'UNIQUE (idempotency_key, result)' THEN
    RAISE EXCEPTION '0026 self-check FAILED: ledger idem UNIQUE 非复合 (idempotency_key, result)，实际=%',
      (SELECT COALESCE(pg_get_constraintdef(oid), '<none>') FROM pg_constraint
        WHERE conrelid='public.listing_review_log'::regclass AND conname='listing_review_log_idem_uniq');
  END IF;
  SELECT count(*) INTO v_n
    FROM pg_index i JOIN pg_class ic ON ic.oid = i.indexrelid
   WHERE i.indrelid = 'public.listing_review_log'::regclass
     AND i.indisunique AND NOT i.indisprimary
     AND ic.relname = 'listing_review_log_idem_uniq'
     AND i.indnkeyatts = 2 AND i.indpred IS NULL
     AND pg_get_indexdef(i.indexrelid) LIKE '%(idempotency_key, result)%';
  IF v_n <> 1 THEN RAISE EXCEPTION '0026 self-check FAILED: 复合唯一索引 (idempotency_key, result) 不在场 (count=%)', v_n; END IF;

  -- 索引齐：PK + idem_uniq + listing_idx + actor_day_idx ≥ 4
  SELECT count(*) INTO v_n FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'listing_review_log';
  IF v_n < 4 THEN RAISE EXCEPTION '0026 self-check FAILED: ledger index count = % (expect >= 4)', v_n; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='listing_review_log'
                   AND indexname='listing_review_log_listing_idx') THEN
    RAISE EXCEPTION '0026 self-check FAILED: listing_review_log_listing_idx missing';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='listing_review_log'
                   AND indexname='listing_review_log_actor_day_idx') THEN
    RAISE EXCEPTION '0026 self-check FAILED: listing_review_log_actor_day_idx missing';
  END IF;

  -- append-only：恰好 1 个启用触发器，且覆盖 UPDATE OR DELETE
  SELECT count(*) INTO v_trg FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relname = 'listing_review_log' AND NOT t.tgisinternal AND t.tgenabled = 'O';
  IF v_trg <> 1 THEN RAISE EXCEPTION '0026 self-check FAILED: ledger enabled triggers = %, expect 1', v_trg; END IF;
  SELECT count(*) INTO v_covers FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relname = 'listing_review_log' AND NOT t.tgisinternal
     AND (t.tgtype & 2) <> 0 AND (t.tgtype & 8) <> 0 AND (t.tgtype & 16) <> 0;
  IF v_covers <> 1 THEN RAISE EXCEPTION '0026 self-check FAILED: append-only trigger must cover UPDATE OR DELETE'; END IF;

  IF to_regprocedure('public.listing_review_log_append_only()') IS NULL THEN
    RAISE EXCEPTION '0026 self-check FAILED: listing_review_log_append_only() missing';
  END IF;

  -- ★ 反断言（§28.6(e)(f)）：本表**无 `time_updated`**、**无 `create_key`**、**无 `ledger_event_keys`**
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public'
               AND table_name='listing_review_log' AND column_name IN ('time_updated','create_key','ledger_event_keys')) THEN
    RAISE EXCEPTION '0026 self-check FAILED: 台账表出现 time_updated / create_key / ledger_event_keys（违 §28.6(e)(f)）';
  END IF;

  -- ★ 零 ALTER 既有表：既有 `listing` 结构指纹未变（列数与列名）
  IF (SELECT string_agg(column_name, ',' ORDER BY ordinal_position) FROM information_schema.columns
        WHERE table_schema='public' AND table_name='listing')
     <> 'listing_id,seller_uid,cid,price,stock,title,description,media_urls,status,create_key,ledger_event_keys,time_created,time_updated' THEN
    RAISE EXCEPTION '0026 self-check FAILED: listing 列指纹变化（本迁移应零 ALTER 既有表）';
  END IF;

  -- ★ 既有迁移链指纹未变（0024 / 0025 的版本行在场 ⇒ 本迁移**未改写**上游）
  SELECT count(*) INTO v_n FROM public.schema_migration WHERE version IN ('0024', '0025');
  IF v_n <> 2 THEN RAISE EXCEPTION '0026 self-check FAILED: upstream migration rows 0024/0025 = % (expect 2)', v_n; END IF;

  RAISE NOTICE '0026 self-check OK: listing_review_log 9 cols / PK×1 FK×2 CHECK×1 UNIQUE×1 / idx×4(PK+idem_uniq+listing_idx+actor_day_idx) / trg×1(O,UPDATE|DELETE) / 无 time_updated·create_key·ledger_event_keys / listing 列指纹不变 / upstream 0024/0025 在场';
END $$;
