-- ============================================================================
-- 0031_rating_and_order_event.sql · P9③（Kong）：`rating` + `listing_order_event` 两表
--   （+ append-only 触发器 / 具名索引 · **单一职责 = 载体面**）
-- ============================================================================
-- 权威口径（**只兑现已冻结的裁定 / 内容契约，不自行推导**）：
--   · `docs/data-layer.spec.md` **v0.23 §32.5(c)**（评分表列草案）+ **§32.4(e)**（订单事件表列草案）
--     + Zang 裁定 **`R-9-31`**（表名定案 = `public.rating` + `public.listing_order_event`；
--       `direction` 4 值闭集）/ **`R-9-28`**（时点真源 = 事件行 `time_created`）/
--       **`R-9-33`**（载体变体 = 最完整：双新表 + 5 新口 ⇒ 注册点 80 → 85）/ **`R-9-32`**（`0031` = 两表，
--       单一职责；**不动 `listing_order`** —— 状态机面归 `0030`）。
--   · 主计划 `docs/seafood.master-plan.md` `§5.241`（`R-9-32`/`R-9-33`）。
--
-- 承载（两表）：
--   ① `public.rating`             —— 双向互评评分行（**四要素必锚** · append-only · 聚合轴 = `ratee_uid`）；
--   ② `public.listing_order_event` —— 订单状态事件（逐订单 × 逐转移 · append-only · **时点真源**）。
-- 触发器（恰 2）：两表各一枚 `BEFORE UPDATE OR DELETE` 无条件 `RAISE`（append-only，原生 `P0001`，
--   **不借账本错误码**）。
--
-- 本迁移**不做什么**（硬约束）：
--   · **绝不改 `0001`–`0030` 任何文件**（`migrate.ts` 锁文件 checksum）；不 `ALTER listing_order`（归 `0030`）；
--   · 不新增 / 不删除 kind；不新增错误码（仍 33 码关闭集）；不写任何业务数据；
--   · 函数体内**无任何 DDL**（DL142 相邻）；不 `DELETE` / `TRUNCATE` / `DROP` 业务数据。
--
-- 幂等：`CREATE TABLE IF NOT EXISTS` / `CREATE OR REPLACE FUNCTION` / `DROP TRIGGER IF EXISTS` +
--   `CREATE TRIGGER` / `CREATE INDEX IF NOT EXISTS` 天然幂等；本文件只被 `migrate.ts` 执行一次。
-- ★ 本迁移**未 apply**（apply 顺序 `0030 → 0031` · apply 由 Zang 执行）。
-- ============================================================================


-- ============================================================================
-- §A `public.rating`（双向互评评分行 · append-only · 四要素必锚）
-- ============================================================================
-- 列 / 约束逐项溯源自 §32.5(c) 草案（先例锚逐字）：
--   · `rating_id`         bigint GENERATED BY DEFAULT AS IDENTITY (PK) ← `0017:140` / `0023:65`
--   · `rater_uid`         bigint NOT NULL（E1 发件人 · 取自 token）← `0023:66`（actor_uid）
--   · `ratee_uid`         bigint NOT NULL（E2 被评人 · 聚合轴）← `0023:67`（target_uid）
--   · `target_type`       text NOT NULL（E3 标的类型 · `job`|`listing`）← `0026:47`（单标的枚举手法）
--   · `target_id`         bigint NOT NULL（E3 标 id · **多态 ⇒ 不建单列 FK**）← `0001:65`（ref_id）/ `0015:164`
--   · `direction`         text NOT NULL（E4 方向 · 4 值闭集 `R-9-31`）← `0025:51-58`
--   · `stars`             numeric(5,4) NOT NULL（`rating_policy.storageDecimals = 4`）← `0001:59`
--   · `idempotency_key`   text NOT NULL ← `0023:77`
--   · `request_fingerprint` text NOT NULL ← `0023:76`
--   · `memo`              text NOT NULL DEFAULT '' ← `0001:69` / `0023:80`
--   · `time_created`      timestamptz NOT NULL DEFAULT now() ← `0023:81`（周期筛选轴 · UTC 自然日）
--   · `rating_pk` PRIMARY KEY (rating_id) ← `0023:82`
--   · `rating_rater_fk` / `rating_ratee_fk` FK → public.users(uid) ← `0023:83`
--   · `rating_stars_rng` CHECK (stars >= 0 AND stars <= 5)（值域 = 需求 §2.1.2「0-5 星」DB 兜底）← `0007:93`
--   · `rating_direction_target_ck`：`target_type='job'` ⇒ `direction ∈ {poster_to_worker,worker_to_poster}`；
--     `target_type='listing'` ⇒ `direction ∈ {vendor_to_customer,customer_to_vendor}`（由 `target_type`
--     决定允许子集 · `R-9-31`）← `0023:88`（语义域 CHECK 手法）
--   · `rating_once_uniq` UNIQUE (rater_uid, target_type, target_id)（同一人 / 同一标的 / 一侧恰一次）← `0001:28`
--   · `rating_idem_uniq` UNIQUE (idempotency_key) ← `0001:74`
--   · 索引 `idx_rating_ratee_time (ratee_uid, time_created DESC)`（聚合轴）+ `idx_rating_target
--     (target_type, target_id, time_created DESC)`（单标的轴）← `0023:133`
--   · append-only：`BEFORE UPDATE OR DELETE` 无条件 `RAISE`（原生 `P0001`）← `0017:236-239` / `0023:112-127`
CREATE TABLE IF NOT EXISTS public.rating (
  rating_id           bigint      GENERATED BY DEFAULT AS IDENTITY,
  rater_uid           bigint      NOT NULL,
  ratee_uid           bigint      NOT NULL,
  target_type         text        NOT NULL,
  target_id           bigint      NOT NULL,
  direction           text        NOT NULL,
  stars               numeric(5,4) NOT NULL,
  idempotency_key     text        NOT NULL,
  request_fingerprint text        NOT NULL,
  memo                text        NOT NULL DEFAULT '',
  time_created        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rating_pk               PRIMARY KEY (rating_id),
  CONSTRAINT rating_rater_fk         FOREIGN KEY (rater_uid) REFERENCES public.users(uid),
  CONSTRAINT rating_ratee_fk         FOREIGN KEY (ratee_uid) REFERENCES public.users(uid),
  -- ★ 值域 = 需求 §2.1.2「0-5 星」的 DB 兜底（越界必 23514）
  CONSTRAINT rating_stars_rng        CHECK (stars >= 0 AND stars <= 5),
  -- ★ `R-9-31`：由 `target_type` 决定 `direction` 允许子集（每侧恰 2 值）—— 同时钉死 `target_type` 闭集。
  CONSTRAINT rating_direction_target_ck CHECK (
    (target_type = 'job'     AND direction IN ('poster_to_worker', 'worker_to_poster'))
    OR (target_type = 'listing' AND direction IN ('vendor_to_customer', 'customer_to_vendor'))),
  -- ★ 同一人、同一标的、一个方向一侧恰一次（承 `R-9-4`「各打一次」）
  CONSTRAINT rating_once_uniq        UNIQUE (rater_uid, target_type, target_id),
  CONSTRAINT rating_idem_uniq        UNIQUE (idempotency_key)
);

COMMENT ON TABLE public.rating IS
  'P9③（Kong；依据 data-layer.spec v0.23 §32.5(c) + R-9-31）：**双向互评评分行**（append-only）。四要素必锚 —— E1 `rater_uid`（token 取）· E2 `ratee_uid`（聚合轴）· E3 `(target_type,target_id)`（job|listing）· E4 `direction`（4 值闭集）；缺一即不可算单边评分。`stars numeric(5,4)`（storageDecimals=4，0–5）。`UNIQUE (rater_uid,target_type,target_id)` = 一侧恰一次；`UNIQUE (idempotency_key)` = 幂等兜底。**保留原始行 + 查询期聚合（禁预聚合分桶 · R-9-1）**。append-only（BEFORE UPDATE OR DELETE 无条件 RAISE，原生 P0001，不借账本码）。护栏不拦 TRUNCATE / DISABLE TRIGGER USER。';

CREATE INDEX IF NOT EXISTS idx_rating_ratee_time
  ON public.rating (ratee_uid, time_created DESC);
CREATE INDEX IF NOT EXISTS idx_rating_target
  ON public.rating (target_type, target_id, time_created DESC);


-- ============================================================================
-- §B `public.listing_order_event`（订单状态事件 · append-only · 时点真源）
-- ============================================================================
-- 列 / 约束逐项溯源自 §32.4(e) 草案（先例锚逐字）：
--   · `event_id`   bigint GENERATED BY DEFAULT AS IDENTITY (PK) ← `0017:140` / `0023:65`
--   · `order_id`   bigint NOT NULL ← `0024:50`
--   · `event_type` text NOT NULL（闭集 6 值 = 状态集）← `0025:47`（`result IN (…)`）
--   · `from_status`/`to_status` text（迁移前后状态；`created` 事件 `from_status = NULL`）← `0017:141-142`
--   · `actor_uid`  bigint NOT NULL（**取自 token**）← `0023:66` / `0024:49`
--   · `txid`       bigint（成功资金事件 = 回执；无资金 = NULL）← `0023:79` / `0024:57`
--   · `idempotency_key` text NOT NULL ← `0023:77`
--   · `request_fingerprint` text NOT NULL ← `0023:76`
--   · `ref_type`/`ref_id` text/bigint ← `0001:64-65`
--   · `memo`       text ← `0023:80`
--   · `time_created` timestamptz NOT NULL DEFAULT now()（**时点真源 · R-9-28**）← `0023:81`
--   · `listing_order_event_pk` PRIMARY KEY (event_id) ← `0023:82`
--   · `listing_order_event_order_fk` FK (order_id) → public.listing_order(order_id) ← `0024:63`
--   · `listing_order_event_actor_fk` FK (actor_uid) → public.users(uid) ← `0023:83`
--   · `listing_order_event_type_enum` CHECK (event_type IN (… 6 值 …)) ← `0025:51-58`
--   · `listing_order_event_idem_uniq` UNIQUE (idempotency_key) ← `0001:74`
--   · 索引 `idx_listing_order_event_order_time (order_id, time_created)` ← `0024:107` / `0023:133`
--   · append-only ← `0017:236-239` / `0023:112-127`
CREATE TABLE IF NOT EXISTS public.listing_order_event (
  event_id            bigint      GENERATED BY DEFAULT AS IDENTITY,
  order_id            bigint      NOT NULL,
  event_type          text        NOT NULL,
  from_status         text,
  to_status           text,
  actor_uid           bigint      NOT NULL,
  txid                bigint,
  idempotency_key     text        NOT NULL,
  request_fingerprint text        NOT NULL,
  ref_type            text,
  ref_id              bigint,
  memo                text,
  time_created        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT listing_order_event_pk             PRIMARY KEY (event_id),
  CONSTRAINT listing_order_event_order_fk       FOREIGN KEY (order_id)  REFERENCES public.listing_order(order_id),
  CONSTRAINT listing_order_event_actor_fk       FOREIGN KEY (actor_uid) REFERENCES public.users(uid),
  -- 闭集 = 订单状态集 6 值（created/paid/shipped/received/refunded/cancelled）
  CONSTRAINT listing_order_event_type_enum      CHECK (event_type IN ('created','paid','shipped','received','refunded','cancelled')),
  CONSTRAINT listing_order_event_idem_uniq      UNIQUE (idempotency_key)
);

COMMENT ON TABLE public.listing_order_event IS
  'P9③（Kong；依据 data-layer.spec v0.23 §32.4(e) + R-9-28/R-9-32）：**订单状态事件表**（append-only）。逐订单 × 逐状态转移一行；「下单 / 付款 / 发货 / 收货」四时点由事件行 `time_created` 承载（**时点真源 · R-9-28**；`listing_order` 仅 `time_created`/`time_updated` 无逐状态时点 ⇒ T3/T4 必须由本表承载）。`event_type` 闭集 = 6 值。append-only（BEFORE UPDATE OR DELETE 无条件 RAISE，原生 P0001，不借账本码）。护栏不拦 TRUNCATE / DISABLE TRIGGER USER。';

CREATE INDEX IF NOT EXISTS idx_listing_order_event_order_time
  ON public.listing_order_event (order_id, time_created);


-- ============================================================================
-- §C 守卫函数（DL142 相邻纪律：函数**只由迁移创建**、体内**禁任何 DDL**）
-- ============================================================================
-- C1 rating append-only（手法同 0017:236-239 / 0023:114-119）
CREATE OR REPLACE FUNCTION public.rating_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'rating is append-only: % forbidden (rating_id=%)',
        TG_OP, COALESCE(OLD.rating_id, 0);
END $$;

COMMENT ON FUNCTION public.rating_append_only() IS
  'rating 为 append-only（BEFORE UPDATE OR DELETE 无条件 RAISE，原生 P0001，不借账本错误码）。只由迁移创建；体内无 DDL。诚实边界：不拦 TRUNCATE / DISABLE TRIGGER USER。';

-- C2 listing_order_event append-only
CREATE OR REPLACE FUNCTION public.listing_order_event_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'listing_order_event is append-only: % forbidden (event_id=%)',
        TG_OP, COALESCE(OLD.event_id, 0);
END $$;

COMMENT ON FUNCTION public.listing_order_event_append_only() IS
  'listing_order_event 为 append-only（BEFORE UPDATE OR DELETE 无条件 RAISE，原生 P0001）。只由迁移创建；体内无 DDL。诚实边界：不拦 TRUNCATE / DISABLE TRIGGER USER。';

-- ---------------------------------------------------------------------------
-- C3 触发器挂载（**恰 2** 枚；幂等：DROP IF EXISTS + CREATE）
-- ---------------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_rating_append_only ON public.rating;
CREATE TRIGGER trg_rating_append_only
  BEFORE UPDATE OR DELETE ON public.rating
  FOR EACH ROW EXECUTE FUNCTION public.rating_append_only();

DROP TRIGGER IF EXISTS trg_listing_order_event_append_only ON public.listing_order_event;
CREATE TRIGGER trg_listing_order_event_append_only
  BEFORE UPDATE OR DELETE ON public.listing_order_event
  FOR EACH ROW EXECUTE FUNCTION public.listing_order_event_append_only();


-- ============================================================================
-- §D apply-time 自检（不通过 ⇒ 整迁移回滚、**不写版本行**）
-- ============================================================================
DO $$
DECLARE
  v_names  text;
  v_n      int;
  v_trg    int;
  v_covers int;
BEGIN
  -- ---------------------------------------------------------------- 两表在场
  IF to_regclass('public.rating')             IS NULL THEN RAISE EXCEPTION '0031 self-check FAILED: public.rating missing'; END IF;
  IF to_regclass('public.listing_order_event') IS NULL THEN RAISE EXCEPTION '0031 self-check FAILED: public.listing_order_event missing'; END IF;

  -- ---------------------------------------------------------------- 逐表列名逐字
  SELECT string_agg(column_name, ',' ORDER BY ordinal_position) INTO v_names
    FROM information_schema.columns WHERE table_schema='public' AND table_name='rating';
  IF v_names <> 'rating_id,rater_uid,ratee_uid,target_type,target_id,direction,stars,idempotency_key,request_fingerprint,memo,time_created' THEN
    RAISE EXCEPTION '0031 self-check FAILED: rating columns = %', v_names; END IF;

  SELECT string_agg(column_name, ',' ORDER BY ordinal_position) INTO v_names
    FROM information_schema.columns WHERE table_schema='public' AND table_name='listing_order_event';
  IF v_names <> 'event_id,order_id,event_type,from_status,to_status,actor_uid,txid,idempotency_key,request_fingerprint,ref_type,ref_id,memo,time_created' THEN
    RAISE EXCEPTION '0031 self-check FAILED: listing_order_event columns = %', v_names; END IF;

  -- ---------------------------------------------------------------- rating：PK×1 / FK×2 / CHECK×2 / UNIQUE×2
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid='public.rating'::regclass AND contype='p';
  IF v_n <> 1 THEN RAISE EXCEPTION '0031 self-check FAILED: rating PK count = %', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid='public.rating'::regclass AND contype='f';
  IF v_n <> 2 THEN RAISE EXCEPTION '0031 self-check FAILED: rating FK count = % (expect 2: rater/ratee)', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid='public.rating'::regclass AND contype='c';
  IF v_n <> 2 THEN RAISE EXCEPTION '0031 self-check FAILED: rating CHECK count = % (expect 2: stars_rng/direction_target)', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid='public.rating'::regclass AND contype='u'
    AND conname IN ('rating_once_uniq','rating_idem_uniq');
  IF v_n <> 2 THEN RAISE EXCEPTION '0031 self-check FAILED: rating UNIQUE count = % (expect 2)', v_n; END IF;
  IF (SELECT pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid='public.rating'::regclass AND conname='rating_once_uniq')
     <> 'UNIQUE (rater_uid, target_type, target_id)' THEN
    RAISE EXCEPTION '0031 self-check FAILED: rating_once_uniq 非 (rater_uid,target_type,target_id)'; END IF;
  IF position('stars >= ' IN (SELECT pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid='public.rating'::regclass AND conname='rating_stars_rng')) = 0 THEN
    RAISE EXCEPTION '0031 self-check FAILED: rating_stars_rng 缺下界'; END IF;
  IF position('stars <= ' IN (SELECT pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid='public.rating'::regclass AND conname='rating_stars_rng')) = 0 THEN
    RAISE EXCEPTION '0031 self-check FAILED: rating_stars_rng 缺上界'; END IF;
  -- direction 4 值闭集逐字在 rating_direction_target_ck 内
  IF (SELECT pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid='public.rating'::regclass AND conname='rating_direction_target_ck')
     NOT LIKE '%poster_to_worker%' THEN
    RAISE EXCEPTION '0031 self-check FAILED: rating_direction_target_ck 缺 poster_to_worker'; END IF;
  IF (SELECT pg_get_constraintdef(oid) FROM pg_constraint
        WHERE conrelid='public.rating'::regclass AND conname='rating_direction_target_ck')
     NOT LIKE '%customer_to_vendor%' THEN
    RAISE EXCEPTION '0031 self-check FAILED: rating_direction_target_ck 缺 customer_to_vendor'; END IF;

  -- ---------------------------------------------------------------- listing_order_event：PK×1 / FK×2 / CHECK×1 / UNIQUE×1
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid='public.listing_order_event'::regclass AND contype='p';
  IF v_n <> 1 THEN RAISE EXCEPTION '0031 self-check FAILED: listing_order_event PK count = %', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid='public.listing_order_event'::regclass AND contype='f';
  IF v_n <> 2 THEN RAISE EXCEPTION '0031 self-check FAILED: listing_order_event FK count = % (expect 2: order/actor)', v_n; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid='public.listing_order_event'::regclass AND contype='c'
    AND conname='listing_order_event_type_enum';
  IF v_n <> 1 THEN RAISE EXCEPTION '0031 self-check FAILED: listing_order_event type CHECK missing'; END IF;
  SELECT count(*) INTO v_n FROM pg_constraint WHERE conrelid='public.listing_order_event'::regclass AND contype='u'
    AND conname='listing_order_event_idem_uniq';
  IF v_n <> 1 THEN RAISE EXCEPTION '0031 self-check FAILED: listing_order_event idempotency UNIQUE missing'; END IF;
  -- event_type 闭集恰 6 值且含 shipped/received
  IF (SELECT count(*) FROM regexp_matches(
        (SELECT pg_get_constraintdef(oid) FROM pg_constraint
          WHERE conrelid='public.listing_order_event'::regclass AND conname='listing_order_event_type_enum'),
        '''[a-z_]+''', 'g')) <> 6 THEN
    RAISE EXCEPTION '0031 self-check FAILED: listing_order_event_type_enum 非 6 值'; END IF;

  -- ---------------------------------------------------------------- 具名索引在场
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='rating' AND indexname='idx_rating_ratee_time') THEN
    RAISE EXCEPTION '0031 self-check FAILED: idx_rating_ratee_time missing'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='rating' AND indexname='idx_rating_target') THEN
    RAISE EXCEPTION '0031 self-check FAILED: idx_rating_target missing'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='listing_order_event' AND indexname='idx_listing_order_event_order_time') THEN
    RAISE EXCEPTION '0031 self-check FAILED: idx_listing_order_event_order_time missing'; END IF;

  -- ---------------------------------------------------------------- append-only 两表：恰 1 启用触发器且覆盖 UPDATE OR DELETE
  FOR v_names IN SELECT unnest(ARRAY['rating','listing_order_event']) LOOP
    SELECT count(*) INTO v_trg FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid
      JOIN pg_namespace n ON n.oid=c.relnamespace
     WHERE n.nspname='public' AND c.relname=v_names AND NOT t.tgisinternal AND t.tgenabled='O';
    IF v_trg <> 1 THEN RAISE EXCEPTION '0031 self-check FAILED: % enabled triggers = %, expect 1', v_names, v_trg; END IF;
    SELECT count(*) INTO v_covers FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid
      JOIN pg_namespace n ON n.oid=c.relnamespace
     WHERE n.nspname='public' AND c.relname=v_names AND NOT t.tgisinternal
       AND (t.tgtype & 2) <> 0 AND (t.tgtype & 8) <> 0 AND (t.tgtype & 16) <> 0;
    IF v_covers <> 1 THEN RAISE EXCEPTION '0031 self-check FAILED: % append-only trigger must cover UPDATE OR DELETE', v_names; END IF;
  END LOOP;

  -- ---------------------------------------------------------------- 两守卫函数在场
  IF to_regprocedure('public.rating_append_only()')              IS NULL THEN RAISE EXCEPTION '0031 self-check FAILED: rating_append_only() missing'; END IF;
  IF to_regprocedure('public.listing_order_event_append_only()') IS NULL THEN RAISE EXCEPTION '0031 self-check FAILED: listing_order_event_append_only() missing'; END IF;

  -- ---------------------------------------------------------------- kind 关闭集 / listing_order 状态机未被本迁移改动（归 0030）
  SELECT count(*) INTO v_n FROM pg_constraint
   WHERE conrelid='public.ledger_entry'::regclass AND conname='ledger_kind_enum' AND contype='c';
  IF v_n <> 1 THEN RAISE EXCEPTION '0031 self-check FAILED: ledger_kind_enum CHECK count = %（应恰 1，本迁移不动 kind）', v_n; END IF;

  RAISE NOTICE '0031 self-check OK: rating (11 cols / PK×1 FK×2 CHECK×2 UNIQUE×2 / 2 indexes) + listing_order_event (13 cols / PK×1 FK×2 CHECK×1 UNIQUE×1 / 1 index) + 2 append-only triggers';
END $$;
